// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/admin_account_api.proto

package libopsv1

import (
	common "github.com/libops/proto/libops/v1/common"
	_ "github.com/libops/proto/libops/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRole int32

const (
	AccountRole_ACCOUNT_ROLE_UNSPECIFIED AccountRole = 0
	AccountRole_ACCOUNT_ROLE_USER        AccountRole = 1 // Regular user
	AccountRole_ACCOUNT_ROLE_ADMIN       AccountRole = 2 // LibOps admin
)

// Enum value maps for AccountRole.
var (
	AccountRole_name = map[int32]string{
		0: "ACCOUNT_ROLE_UNSPECIFIED",
		1: "ACCOUNT_ROLE_USER",
		2: "ACCOUNT_ROLE_ADMIN",
	}
	AccountRole_value = map[string]int32{
		"ACCOUNT_ROLE_UNSPECIFIED": 0,
		"ACCOUNT_ROLE_USER":        1,
		"ACCOUNT_ROLE_ADMIN":       2,
	}
)

func (x AccountRole) Enum() *AccountRole {
	p := new(AccountRole)
	*p = x
	return p
}

func (x AccountRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountRole) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_admin_account_api_proto_enumTypes[0].Descriptor()
}

func (AccountRole) Type() protoreflect.EnumType {
	return &file_libops_v1_admin_account_api_proto_enumTypes[0]
}

func (x AccountRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountRole.Descriptor instead.
func (AccountRole) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{0}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_SUSPENDED   AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_DELETED     AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_SUSPENDED",
		3: "ACCOUNT_STATUS_DELETED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_SUSPENDED":   2,
		"ACCOUNT_STATUS_DELETED":     3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_admin_account_api_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_libops_v1_admin_account_api_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{1}
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                                      // Unique account identifier (UUID)
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                                               // User's email address
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                 // Display name
	GithubUsername *string                `protobuf:"bytes,4,opt,name=github_username,json=githubUsername,proto3,oneof" json:"github_username,omitempty"`                 // GitHub username for integration
	Role           AccountRole            `protobuf:"varint,5,opt,name=role,proto3,enum=libops.v1.AccountRole" json:"role,omitempty"`                                     // System-wide role
	Status         AccountStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=libops.v1.AccountStatus" json:"status,omitempty"`                               // Account status
	AuthMethod     common.AuthMethod      `protobuf:"varint,7,opt,name=auth_method,json=authMethod,proto3,enum=libops.v1.common.AuthMethod" json:"auth_method,omitempty"` // How the user authenticates
	Verified       bool                   `protobuf:"varint,8,opt,name=verified,proto3" json:"verified,omitempty"`                                                        // Email verification status
	VerifiedAt     *string                `protobuf:"bytes,9,opt,name=verified_at,json=verifiedAt,proto3,oneof" json:"verified_at,omitempty"`                             // Timestamp when verified (RFC3339)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetGithubUsername() string {
	if x != nil && x.GithubUsername != nil {
		return *x.GithubUsername
	}
	return ""
}

func (x *Account) GetRole() AccountRole {
	if x != nil {
		return x.Role
	}
	return AccountRole_ACCOUNT_ROLE_UNSPECIFIED
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetAuthMethod() common.AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return common.AuthMethod(0)
}

func (x *Account) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Account) GetVerifiedAt() string {
	if x != nil && x.VerifiedAt != nil {
		return *x.VerifiedAt
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AdminGetAccountByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetAccountByEmailRequest) Reset() {
	*x = AdminGetAccountByEmailRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetAccountByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetAccountByEmailRequest) ProtoMessage() {}

func (x *AdminGetAccountByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetAccountByEmailRequest.ProtoReflect.Descriptor instead.
func (*AdminGetAccountByEmailRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{3}
}

func (x *AdminGetAccountByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AdminGetAccountByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetAccountByEmailResponse) Reset() {
	*x = AdminGetAccountByEmailResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetAccountByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetAccountByEmailResponse) ProtoMessage() {}

func (x *AdminGetAccountByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetAccountByEmailResponse.ProtoReflect.Descriptor instead.
func (*AdminGetAccountByEmailResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{4}
}

func (x *AdminGetAccountByEmailResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GithubUsername *string                `protobuf:"bytes,3,opt,name=github_username,json=githubUsername,proto3,oneof" json:"github_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetGithubUsername() string {
	if x != nil && x.GithubUsername != nil {
		return *x.GithubUsername
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type UpdateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name           *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GithubUsername *string                `protobuf:"bytes,3,opt,name=github_username,json=githubUsername,proto3,oneof" json:"github_username,omitempty"`
	UpdateMask     *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAccountRequest) GetGithubUsername() string {
	if x != nil && x.GithubUsername != nil {
		return *x.GithubUsername
	}
	return ""
}

func (x *UpdateAccountRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Status        *AccountStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=libops.v1.AccountStatus,oneof" json:"status,omitempty"` // Filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccountsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAccountsRequest) GetStatus() AccountStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListAccountProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountProjectsRequest) Reset() {
	*x = ListAccountProjectsRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountProjectsRequest) ProtoMessage() {}

func (x *ListAccountProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountProjectsRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListAccountProjectsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListAccountProjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccountProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAccountProjectsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationIds []string               `protobuf:"bytes,1,rep,name=organization_ids,json=organizationIds,proto3" json:"organization_ids,omitempty"` // List of organization IDs the account has access to
	NextPageToken   string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAccountProjectsResponse) Reset() {
	*x = ListAccountProjectsResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountProjectsResponse) ProtoMessage() {}

func (x *ListAccountProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountProjectsResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{13}
}

func (x *ListAccountProjectsResponse) GetOrganizationIds() []string {
	if x != nil {
		return x.OrganizationIds
	}
	return nil
}

func (x *ListAccountProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListAccountRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRepositoriesRequest) Reset() {
	*x = ListAccountRepositoriesRequest{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRepositoriesRequest) ProtoMessage() {}

func (x *ListAccountRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListAccountRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListAccountRepositoriesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListAccountRepositoriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccountRepositoriesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type Repository struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoName       string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoUrl        string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{15}
}

func (x *Repository) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *Repository) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Repository) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Repository) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListAccountRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRepositoriesResponse) Reset() {
	*x = ListAccountRepositoriesResponse{}
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRepositoriesResponse) ProtoMessage() {}

func (x *ListAccountRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_account_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListAccountRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_account_api_proto_rawDescGZIP(), []int{16}
}

func (x *ListAccountRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *ListAccountRepositoriesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_libops_v1_admin_account_api_proto protoreflect.FileDescriptor

const file_libops_v1_admin_account_api_proto_rawDesc = "" +
	"\n" +
	"!libops/v1/admin_account_api.proto\x12\tlibops.v1\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1dlibops/v1/options/scope.proto\x1a\x1clibops/v1/common/types.proto\"\x83\x03\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12,\n" +
	"\x0fgithub_username\x18\x04 \x01(\tH\x00R\x0egithubUsername\x88\x01\x01\x12*\n" +
	"\x04role\x18\x05 \x01(\x0e2\x16.libops.v1.AccountRoleR\x04role\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.libops.v1.AccountStatusR\x06status\x12=\n" +
	"\vauth_method\x18\a \x01(\x0e2\x1c.libops.v1.common.AuthMethodR\n" +
	"authMethod\x12\x1a\n" +
	"\bverified\x18\b \x01(\bR\bverified\x12$\n" +
	"\vverified_at\x18\t \x01(\tH\x01R\n" +
	"verifiedAt\x88\x01\x01B\x12\n" +
	"\x10_github_usernameB\x0e\n" +
	"\f_verified_at\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"B\n" +
	"\x12GetAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.libops.v1.AccountR\aaccount\"5\n" +
	"\x1dAdminGetAccountByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"N\n" +
	"\x1eAdminGetAccountByEmailResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.libops.v1.AccountR\aaccount\"\x82\x01\n" +
	"\x14CreateAccountRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x0fgithub_username\x18\x03 \x01(\tH\x00R\x0egithubUsername\x88\x01\x01B\x12\n" +
	"\x10_github_username\"E\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.libops.v1.AccountR\aaccount\"\xd6\x01\n" +
	"\x14UpdateAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12,\n" +
	"\x0fgithub_username\x18\x03 \x01(\tH\x01R\x0egithubUsername\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\a\n" +
	"\x05_nameB\x12\n" +
	"\x10_github_username\"E\n" +
	"\x15UpdateAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.libops.v1.AccountR\aaccount\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x93\x01\n" +
	"\x13ListAccountsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.libops.v1.AccountStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"n\n" +
	"\x14ListAccountsResponse\x12.\n" +
	"\baccounts\x18\x01 \x03(\v2\x12.libops.v1.AccountR\baccounts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"w\n" +
	"\x1aListAccountProjectsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"p\n" +
	"\x1bListAccountProjectsResponse\x12)\n" +
	"\x10organization_ids\x18\x01 \x03(\tR\x0forganizationIds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"{\n" +
	"\x1eListAccountRepositoriesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\n" +
	"Repository\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"\x84\x01\n" +
	"\x1fListAccountRepositoriesResponse\x129\n" +
	"\frepositories\x18\x01 \x03(\v2\x15.libops.v1.RepositoryR\frepositories\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*Z\n" +
	"\vAccountRole\x12\x1c\n" +
	"\x18ACCOUNT_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_ROLE_USER\x10\x01\x12\x16\n" +
	"\x12ACCOUNT_ROLE_ADMIN\x10\x02*\x84\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ACCOUNT_STATUS_SUSPENDED\x10\x02\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_DELETED\x10\x032\xb6\a\n" +
	"\x13AdminAccountService\x12d\n" +
	"\n" +
	"GetAccount\x12\x1c.libops.v1.GetAccountRequest\x1a\x1d.libops.v1.GetAccountResponse\"\x19\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x90\x02\x01\x12\x83\x01\n" +
	"\x11GetAccountByEmail\x12(.libops.v1.AdminGetAccountByEmailRequest\x1a).libops.v1.AdminGetAccountByEmailResponse\"\x19\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x90\x02\x01\x12j\n" +
	"\rCreateAccount\x12\x1f.libops.v1.CreateAccountRequest\x1a .libops.v1.CreateAccountResponse\"\x16\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x12j\n" +
	"\rUpdateAccount\x12\x1f.libops.v1.UpdateAccountRequest\x1a .libops.v1.UpdateAccountResponse\"\x16\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x12`\n" +
	"\rDeleteAccount\x12\x1f.libops.v1.DeleteAccountRequest\x1a\x16.google.protobuf.Empty\"\x16\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x12j\n" +
	"\fListAccounts\x12\x1e.libops.v1.ListAccountsRequest\x1a\x1f.libops.v1.ListAccountsResponse\"\x19\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x90\x02\x01\x12\x7f\n" +
	"\x13ListAccountProjects\x12%.libops.v1.ListAccountProjectsRequest\x1a&.libops.v1.ListAccountProjectsResponse\"\x19\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x90\x02\x01\x12\x8b\x01\n" +
	"\x17ListAccountRepositories\x12).libops.v1.ListAccountRepositoriesRequest\x1a*.libops.v1.ListAccountRepositoriesResponse\"\x19\x92\xb5\x18\x12\b\x01\x10\x03\"\fadmin:system\x90\x02\x01B\x96\x01\n" +
	"\rcom.libops.v1B\x14AdminAccountApiProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_admin_account_api_proto_rawDescOnce sync.Once
	file_libops_v1_admin_account_api_proto_rawDescData []byte
)

func file_libops_v1_admin_account_api_proto_rawDescGZIP() []byte {
	file_libops_v1_admin_account_api_proto_rawDescOnce.Do(func() {
		file_libops_v1_admin_account_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_admin_account_api_proto_rawDesc), len(file_libops_v1_admin_account_api_proto_rawDesc)))
	})
	return file_libops_v1_admin_account_api_proto_rawDescData
}

var file_libops_v1_admin_account_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_libops_v1_admin_account_api_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_libops_v1_admin_account_api_proto_goTypes = []any{
	(AccountRole)(0),                        // 0: libops.v1.AccountRole
	(AccountStatus)(0),                      // 1: libops.v1.AccountStatus
	(*Account)(nil),                         // 2: libops.v1.Account
	(*GetAccountRequest)(nil),               // 3: libops.v1.GetAccountRequest
	(*GetAccountResponse)(nil),              // 4: libops.v1.GetAccountResponse
	(*AdminGetAccountByEmailRequest)(nil),   // 5: libops.v1.AdminGetAccountByEmailRequest
	(*AdminGetAccountByEmailResponse)(nil),  // 6: libops.v1.AdminGetAccountByEmailResponse
	(*CreateAccountRequest)(nil),            // 7: libops.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),           // 8: libops.v1.CreateAccountResponse
	(*UpdateAccountRequest)(nil),            // 9: libops.v1.UpdateAccountRequest
	(*UpdateAccountResponse)(nil),           // 10: libops.v1.UpdateAccountResponse
	(*DeleteAccountRequest)(nil),            // 11: libops.v1.DeleteAccountRequest
	(*ListAccountsRequest)(nil),             // 12: libops.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),            // 13: libops.v1.ListAccountsResponse
	(*ListAccountProjectsRequest)(nil),      // 14: libops.v1.ListAccountProjectsRequest
	(*ListAccountProjectsResponse)(nil),     // 15: libops.v1.ListAccountProjectsResponse
	(*ListAccountRepositoriesRequest)(nil),  // 16: libops.v1.ListAccountRepositoriesRequest
	(*Repository)(nil),                      // 17: libops.v1.Repository
	(*ListAccountRepositoriesResponse)(nil), // 18: libops.v1.ListAccountRepositoriesResponse
	(common.AuthMethod)(0),                  // 19: libops.v1.common.AuthMethod
	(*fieldmaskpb.FieldMask)(nil),           // 20: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                   // 21: google.protobuf.Empty
}
var file_libops_v1_admin_account_api_proto_depIdxs = []int32{
	0,  // 0: libops.v1.Account.role:type_name -> libops.v1.AccountRole
	1,  // 1: libops.v1.Account.status:type_name -> libops.v1.AccountStatus
	19, // 2: libops.v1.Account.auth_method:type_name -> libops.v1.common.AuthMethod
	2,  // 3: libops.v1.GetAccountResponse.account:type_name -> libops.v1.Account
	2,  // 4: libops.v1.AdminGetAccountByEmailResponse.account:type_name -> libops.v1.Account
	2,  // 5: libops.v1.CreateAccountResponse.account:type_name -> libops.v1.Account
	20, // 6: libops.v1.UpdateAccountRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 7: libops.v1.UpdateAccountResponse.account:type_name -> libops.v1.Account
	1,  // 8: libops.v1.ListAccountsRequest.status:type_name -> libops.v1.AccountStatus
	2,  // 9: libops.v1.ListAccountsResponse.accounts:type_name -> libops.v1.Account
	17, // 10: libops.v1.ListAccountRepositoriesResponse.repositories:type_name -> libops.v1.Repository
	3,  // 11: libops.v1.AdminAccountService.GetAccount:input_type -> libops.v1.GetAccountRequest
	5,  // 12: libops.v1.AdminAccountService.GetAccountByEmail:input_type -> libops.v1.AdminGetAccountByEmailRequest
	7,  // 13: libops.v1.AdminAccountService.CreateAccount:input_type -> libops.v1.CreateAccountRequest
	9,  // 14: libops.v1.AdminAccountService.UpdateAccount:input_type -> libops.v1.UpdateAccountRequest
	11, // 15: libops.v1.AdminAccountService.DeleteAccount:input_type -> libops.v1.DeleteAccountRequest
	12, // 16: libops.v1.AdminAccountService.ListAccounts:input_type -> libops.v1.ListAccountsRequest
	14, // 17: libops.v1.AdminAccountService.ListAccountProjects:input_type -> libops.v1.ListAccountProjectsRequest
	16, // 18: libops.v1.AdminAccountService.ListAccountRepositories:input_type -> libops.v1.ListAccountRepositoriesRequest
	4,  // 19: libops.v1.AdminAccountService.GetAccount:output_type -> libops.v1.GetAccountResponse
	6,  // 20: libops.v1.AdminAccountService.GetAccountByEmail:output_type -> libops.v1.AdminGetAccountByEmailResponse
	8,  // 21: libops.v1.AdminAccountService.CreateAccount:output_type -> libops.v1.CreateAccountResponse
	10, // 22: libops.v1.AdminAccountService.UpdateAccount:output_type -> libops.v1.UpdateAccountResponse
	21, // 23: libops.v1.AdminAccountService.DeleteAccount:output_type -> google.protobuf.Empty
	13, // 24: libops.v1.AdminAccountService.ListAccounts:output_type -> libops.v1.ListAccountsResponse
	15, // 25: libops.v1.AdminAccountService.ListAccountProjects:output_type -> libops.v1.ListAccountProjectsResponse
	18, // 26: libops.v1.AdminAccountService.ListAccountRepositories:output_type -> libops.v1.ListAccountRepositoriesResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_libops_v1_admin_account_api_proto_init() }
func file_libops_v1_admin_account_api_proto_init() {
	if File_libops_v1_admin_account_api_proto != nil {
		return
	}
	file_libops_v1_admin_account_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_libops_v1_admin_account_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_libops_v1_admin_account_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_libops_v1_admin_account_api_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_admin_account_api_proto_rawDesc), len(file_libops_v1_admin_account_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libops_v1_admin_account_api_proto_goTypes,
		DependencyIndexes: file_libops_v1_admin_account_api_proto_depIdxs,
		EnumInfos:         file_libops_v1_admin_account_api_proto_enumTypes,
		MessageInfos:      file_libops_v1_admin_account_api_proto_msgTypes,
	}.Build()
	File_libops_v1_admin_account_api_proto = out.File
	file_libops_v1_admin_account_api_proto_goTypes = nil
	file_libops_v1_admin_account_api_proto_depIdxs = nil
}
