// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/assistant_api.proto

package libopsv1

import (
	_ "github.com/libops/proto/libops/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssistantChatRequest sends a natural language request scoped to a context.
type AssistantChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target organization (required).
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Optional project scope for the request.
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional site scope for the request.
	SiteId string `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// The user message to execute.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Optional client-generated request identifier for idempotency.
	ClientRequestId string `protobuf:"bytes,5,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	// Optional metadata for routing or model selection.
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional coding agent model selection.
	AgentModel    string `protobuf:"bytes,7,opt,name=agent_model,json=agentModel,proto3" json:"agent_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantChatRequest) Reset() {
	*x = AssistantChatRequest{}
	mi := &file_libops_v1_assistant_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantChatRequest) ProtoMessage() {}

func (x *AssistantChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_assistant_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantChatRequest.ProtoReflect.Descriptor instead.
func (*AssistantChatRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_assistant_api_proto_rawDescGZIP(), []int{0}
}

func (x *AssistantChatRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AssistantChatRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AssistantChatRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *AssistantChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssistantChatRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *AssistantChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AssistantChatRequest) GetAgentModel() string {
	if x != nil {
		return x.AgentModel
	}
	return ""
}

// AssistantChatResponse returns the queued request details.
type AssistantChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated request identifier.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Status for the queued request (e.g., "queued").
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Optional immediate reply for UI display.
	Reply         string `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantChatResponse) Reset() {
	*x = AssistantChatResponse{}
	mi := &file_libops_v1_assistant_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantChatResponse) ProtoMessage() {}

func (x *AssistantChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_assistant_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantChatResponse.ProtoReflect.Descriptor instead.
func (*AssistantChatResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_assistant_api_proto_rawDescGZIP(), []int{1}
}

func (x *AssistantChatResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AssistantChatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssistantChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_libops_v1_assistant_api_proto protoreflect.FileDescriptor

const file_libops_v1_assistant_api_proto_rawDesc = "" +
	"\n" +
	"\x1dlibops/v1/assistant_api.proto\x12\tlibops.v1\x1a\x1dlibops/v1/options/scope.proto\"\xe6\x02\n" +
	"\x14AssistantChatRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12*\n" +
	"\x11client_request_id\x18\x05 \x01(\tR\x0fclientRequestId\x12I\n" +
	"\bmetadata\x18\x06 \x03(\v2-.libops.v1.AssistantChatRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vagent_model\x18\a \x01(\tR\n" +
	"agentModel\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x15AssistantChatResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply2\x8e\x01\n" +
	"\x10AssistantService\x12z\n" +
	"\x04Chat\x12\x1f.libops.v1.AssistantChatRequest\x1a .libops.v1.AssistantChatResponse\"/\x92\xb5\x18+\b\x03\x10\x02\x18\x01\"\x12write:organization*\x0forganization_idB\x93\x01\n" +
	"\rcom.libops.v1B\x11AssistantApiProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_assistant_api_proto_rawDescOnce sync.Once
	file_libops_v1_assistant_api_proto_rawDescData []byte
)

func file_libops_v1_assistant_api_proto_rawDescGZIP() []byte {
	file_libops_v1_assistant_api_proto_rawDescOnce.Do(func() {
		file_libops_v1_assistant_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_assistant_api_proto_rawDesc), len(file_libops_v1_assistant_api_proto_rawDesc)))
	})
	return file_libops_v1_assistant_api_proto_rawDescData
}

var file_libops_v1_assistant_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libops_v1_assistant_api_proto_goTypes = []any{
	(*AssistantChatRequest)(nil),  // 0: libops.v1.AssistantChatRequest
	(*AssistantChatResponse)(nil), // 1: libops.v1.AssistantChatResponse
	nil,                           // 2: libops.v1.AssistantChatRequest.MetadataEntry
}
var file_libops_v1_assistant_api_proto_depIdxs = []int32{
	2, // 0: libops.v1.AssistantChatRequest.metadata:type_name -> libops.v1.AssistantChatRequest.MetadataEntry
	0, // 1: libops.v1.AssistantService.Chat:input_type -> libops.v1.AssistantChatRequest
	1, // 2: libops.v1.AssistantService.Chat:output_type -> libops.v1.AssistantChatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libops_v1_assistant_api_proto_init() }
func file_libops_v1_assistant_api_proto_init() {
	if File_libops_v1_assistant_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_assistant_api_proto_rawDesc), len(file_libops_v1_assistant_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libops_v1_assistant_api_proto_goTypes,
		DependencyIndexes: file_libops_v1_assistant_api_proto_depIdxs,
		MessageInfos:      file_libops_v1_assistant_api_proto_msgTypes,
	}.Build()
	File_libops_v1_assistant_api_proto = out.File
	file_libops_v1_assistant_api_proto_goTypes = nil
	file_libops_v1_assistant_api_proto_depIdxs = nil
}
