// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/event.proto

package libopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope is the shared control-plane event contract stored in event_queue
// and consumed by workers.
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID is the CloudEvents id.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event type is the CloudEvents type.
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Event source is the CloudEvents source.
	EventSource string `protobuf:"bytes,3,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	// Event subject identifies the affected resource, when present.
	EventSubject string `protobuf:"bytes,4,opt,name=event_subject,json=eventSubject,proto3" json:"event_subject,omitempty"`
	// Event data contains the serialized event payload.
	EventData []byte `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	// Content type describes event_data.
	ContentType string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Organization ID is the internal organization row ID.
	OrganizationId int64 `protobuf:"varint,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Project ID is the internal project row ID, when scoped to a project.
	ProjectId *int64 `protobuf:"varint,8,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	// Site ID is the internal site row ID, when scoped to a site.
	SiteId *int64 `protobuf:"varint,9,opt,name=site_id,json=siteId,proto3,oneof" json:"site_id,omitempty"`
	// Created at records when the event was queued.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Request ID links the event to the originating API request.
	RequestId string `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Traceparent carries the W3C trace context across queue and Pub/Sub hops.
	Traceparent   string `protobuf:"bytes,12,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_libops_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_libops_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetEventSource() string {
	if x != nil {
		return x.EventSource
	}
	return ""
}

func (x *EventEnvelope) GetEventSubject() string {
	if x != nil {
		return x.EventSubject
	}
	return ""
}

func (x *EventEnvelope) GetEventData() []byte {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *EventEnvelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EventEnvelope) GetOrganizationId() int64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *EventEnvelope) GetProjectId() int64 {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return 0
}

func (x *EventEnvelope) GetSiteId() int64 {
	if x != nil && x.SiteId != nil {
		return *x.SiteId
	}
	return 0
}

func (x *EventEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EventEnvelope) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

// ControlPlanePubSubEnvelope is the versioned Pub/Sub contract for messages
// published by control-plane producers and consumed by Cloud Run workers.
type ControlPlanePubSubEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Envelope ID is unique for this Pub/Sub payload.
	EnvelopeId string `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	// Schema version is incremented when this envelope changes incompatibly.
	SchemaVersion int32 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Dedupe key is stable for retries of the same logical request.
	DedupeKey string `protobuf:"bytes,3,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	// Request ID links this message to the originating customer mutation.
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Traceparent carries the W3C trace context across Pub/Sub.
	Traceparent string `protobuf:"bytes,5,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	// Payload is the typed control-plane message body.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlanePubSubEnvelope_SiteReconciliation
	Payload       isControlPlanePubSubEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlanePubSubEnvelope) Reset() {
	*x = ControlPlanePubSubEnvelope{}
	mi := &file_libops_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlanePubSubEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlanePubSubEnvelope) ProtoMessage() {}

func (x *ControlPlanePubSubEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlanePubSubEnvelope.ProtoReflect.Descriptor instead.
func (*ControlPlanePubSubEnvelope) Descriptor() ([]byte, []int) {
	return file_libops_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ControlPlanePubSubEnvelope) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *ControlPlanePubSubEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ControlPlanePubSubEnvelope) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *ControlPlanePubSubEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlPlanePubSubEnvelope) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *ControlPlanePubSubEnvelope) GetPayload() isControlPlanePubSubEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlanePubSubEnvelope) GetSiteReconciliation() *SiteReconciliationPubSubRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlanePubSubEnvelope_SiteReconciliation); ok {
			return x.SiteReconciliation
		}
	}
	return nil
}

type isControlPlanePubSubEnvelope_Payload interface {
	isControlPlanePubSubEnvelope_Payload()
}

type ControlPlanePubSubEnvelope_SiteReconciliation struct {
	// Site reconciliation asks a site controller to reconcile local state.
	SiteReconciliation *SiteReconciliationPubSubRequest `protobuf:"bytes,10,opt,name=site_reconciliation,json=siteReconciliation,proto3,oneof"`
}

func (*ControlPlanePubSubEnvelope_SiteReconciliation) isControlPlanePubSubEnvelope_Payload() {}

// SiteReconciliationPubSubRequest asks a customer site controller to reconcile.
type SiteReconciliationPubSubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Site public ID is the target site UUID.
	SitePublicId string `protobuf:"bytes,1,opt,name=site_public_id,json=sitePublicId,proto3" json:"site_public_id,omitempty"`
	// Project public ID is the target project's UUID.
	ProjectPublicId string `protobuf:"bytes,2,opt,name=project_public_id,json=projectPublicId,proto3" json:"project_public_id,omitempty"`
	// Organization public ID is the owning organization's UUID.
	OrgPublicId string `protobuf:"bytes,3,opt,name=org_public_id,json=orgPublicId,proto3" json:"org_public_id,omitempty"`
	// Controller URL is the DB-pinned controller endpoint for this site.
	ControllerUrl string `protobuf:"bytes,4,opt,name=controller_url,json=controllerUrl,proto3" json:"controller_url,omitempty"`
	// Request type selects the controller reconciliation endpoint.
	RequestType string `protobuf:"bytes,5,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	// Event IDs are the outbox events collapsed into this request.
	EventIds []string `protobuf:"bytes,6,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	// Timestamp is when the request was built.
	Timestamp string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Deployment ID identifies the requested deployment, when request_type is deployment.
	DeploymentId string `protobuf:"bytes,8,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// Git ref is the branch, tag, PR ref, or commit requested for deployment.
	GitRef        string `protobuf:"bytes,9,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteReconciliationPubSubRequest) Reset() {
	*x = SiteReconciliationPubSubRequest{}
	mi := &file_libops_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteReconciliationPubSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteReconciliationPubSubRequest) ProtoMessage() {}

func (x *SiteReconciliationPubSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteReconciliationPubSubRequest.ProtoReflect.Descriptor instead.
func (*SiteReconciliationPubSubRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *SiteReconciliationPubSubRequest) GetSitePublicId() string {
	if x != nil {
		return x.SitePublicId
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetProjectPublicId() string {
	if x != nil {
		return x.ProjectPublicId
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetOrgPublicId() string {
	if x != nil {
		return x.OrgPublicId
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetControllerUrl() string {
	if x != nil {
		return x.ControllerUrl
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *SiteReconciliationPubSubRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *SiteReconciliationPubSubRequest) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

var File_libops_v1_event_proto protoreflect.FileDescriptor

const file_libops_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x15libops/v1/event.proto\x12\tlibops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x03\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fevent_source\x18\x03 \x01(\tR\veventSource\x12#\n" +
	"\revent_subject\x18\x04 \x01(\tR\feventSubject\x12\x1d\n" +
	"\n" +
	"event_data\x18\x05 \x01(\fR\teventData\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12'\n" +
	"\x0forganization_id\x18\a \x01(\x03R\x0eorganizationId\x12\"\n" +
	"\n" +
	"project_id\x18\b \x01(\x03H\x00R\tprojectId\x88\x01\x01\x12\x1c\n" +
	"\asite_id\x18\t \x01(\x03H\x01R\x06siteId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x12 \n" +
	"\vtraceparent\x18\f \x01(\tR\vtraceparentB\r\n" +
	"\v_project_idB\n" +
	"\n" +
	"\b_site_id\"\xae\x02\n" +
	"\x1aControlPlanePubSubEnvelope\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\x05R\rschemaVersion\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\x03 \x01(\tR\tdedupeKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12 \n" +
	"\vtraceparent\x18\x05 \x01(\tR\vtraceparent\x12]\n" +
	"\x13site_reconciliation\x18\n" +
	" \x01(\v2*.libops.v1.SiteReconciliationPubSubRequestH\x00R\x12siteReconciliationB\t\n" +
	"\apayload\"\xda\x02\n" +
	"\x1fSiteReconciliationPubSubRequest\x12$\n" +
	"\x0esite_public_id\x18\x01 \x01(\tR\fsitePublicId\x12*\n" +
	"\x11project_public_id\x18\x02 \x01(\tR\x0fprojectPublicId\x12\"\n" +
	"\rorg_public_id\x18\x03 \x01(\tR\vorgPublicId\x12%\n" +
	"\x0econtroller_url\x18\x04 \x01(\tR\rcontrollerUrl\x12!\n" +
	"\frequest_type\x18\x05 \x01(\tR\vrequestType\x12\x1b\n" +
	"\tevent_ids\x18\x06 \x03(\tR\beventIds\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12#\n" +
	"\rdeployment_id\x18\b \x01(\tR\fdeploymentId\x12\x17\n" +
	"\agit_ref\x18\t \x01(\tR\x06gitRefB\x8c\x01\n" +
	"\rcom.libops.v1B\n" +
	"EventProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_event_proto_rawDescOnce sync.Once
	file_libops_v1_event_proto_rawDescData []byte
)

func file_libops_v1_event_proto_rawDescGZIP() []byte {
	file_libops_v1_event_proto_rawDescOnce.Do(func() {
		file_libops_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_event_proto_rawDesc), len(file_libops_v1_event_proto_rawDesc)))
	})
	return file_libops_v1_event_proto_rawDescData
}

var file_libops_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libops_v1_event_proto_goTypes = []any{
	(*EventEnvelope)(nil),                   // 0: libops.v1.EventEnvelope
	(*ControlPlanePubSubEnvelope)(nil),      // 1: libops.v1.ControlPlanePubSubEnvelope
	(*SiteReconciliationPubSubRequest)(nil), // 2: libops.v1.SiteReconciliationPubSubRequest
	(*timestamppb.Timestamp)(nil),           // 3: google.protobuf.Timestamp
}
var file_libops_v1_event_proto_depIdxs = []int32{
	3, // 0: libops.v1.EventEnvelope.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: libops.v1.ControlPlanePubSubEnvelope.site_reconciliation:type_name -> libops.v1.SiteReconciliationPubSubRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_libops_v1_event_proto_init() }
func file_libops_v1_event_proto_init() {
	if File_libops_v1_event_proto != nil {
		return
	}
	file_libops_v1_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_libops_v1_event_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlPlanePubSubEnvelope_SiteReconciliation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_event_proto_rawDesc), len(file_libops_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_event_proto_goTypes,
		DependencyIndexes: file_libops_v1_event_proto_depIdxs,
		MessageInfos:      file_libops_v1_event_proto_msgTypes,
	}.Build()
	File_libops_v1_event_proto = out.File
	file_libops_v1_event_proto_goTypes = nil
	file_libops_v1_event_proto_depIdxs = nil
}
