// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/operation_api.proto

package libopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_RUNNING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_SUCCEEDED   OperationStatus = 2
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 3
	OperationStatus_OPERATION_STATUS_CANCELED    OperationStatus = 4
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_RUNNING",
		2: "OPERATION_STATUS_SUCCEEDED",
		3: "OPERATION_STATUS_FAILED",
		4: "OPERATION_STATUS_CANCELED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_RUNNING":     1,
		"OPERATION_STATUS_SUCCEEDED":   2,
		"OPERATION_STATUS_FAILED":      3,
		"OPERATION_STATUS_CANCELED":    4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_operation_api_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_libops_v1_operation_api_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_operation_api_proto_rawDescGZIP(), []int{0}
}

type Operation struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	OperationId                  string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RequestId                    string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OperationType                string                 `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Status                       OperationStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=libops.v1.OperationStatus" json:"status,omitempty"`
	EventCount                   int64                  `protobuf:"varint,5,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	EventCompletedCount          int64                  `protobuf:"varint,6,opt,name=event_completed_count,json=eventCompletedCount,proto3" json:"event_completed_count,omitempty"`
	EventFailedCount             int64                  `protobuf:"varint,7,opt,name=event_failed_count,json=eventFailedCount,proto3" json:"event_failed_count,omitempty"`
	PublishCount                 int64                  `protobuf:"varint,8,opt,name=publish_count,json=publishCount,proto3" json:"publish_count,omitempty"`
	PublishCompletedCount        int64                  `protobuf:"varint,9,opt,name=publish_completed_count,json=publishCompletedCount,proto3" json:"publish_completed_count,omitempty"`
	PublishFailedCount           int64                  `protobuf:"varint,10,opt,name=publish_failed_count,json=publishFailedCount,proto3" json:"publish_failed_count,omitempty"`
	ReconciliationCount          int64                  `protobuf:"varint,11,opt,name=reconciliation_count,json=reconciliationCount,proto3" json:"reconciliation_count,omitempty"`
	ReconciliationCompletedCount int64                  `protobuf:"varint,12,opt,name=reconciliation_completed_count,json=reconciliationCompletedCount,proto3" json:"reconciliation_completed_count,omitempty"`
	ReconciliationFailedCount    int64                  `protobuf:"varint,13,opt,name=reconciliation_failed_count,json=reconciliationFailedCount,proto3" json:"reconciliation_failed_count,omitempty"`
	ErrorMessage                 string                 `protobuf:"bytes,14,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt                    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt                  *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_libops_v1_operation_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_operation_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_libops_v1_operation_api_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Operation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *Operation) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *Operation) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *Operation) GetEventCompletedCount() int64 {
	if x != nil {
		return x.EventCompletedCount
	}
	return 0
}

func (x *Operation) GetEventFailedCount() int64 {
	if x != nil {
		return x.EventFailedCount
	}
	return 0
}

func (x *Operation) GetPublishCount() int64 {
	if x != nil {
		return x.PublishCount
	}
	return 0
}

func (x *Operation) GetPublishCompletedCount() int64 {
	if x != nil {
		return x.PublishCompletedCount
	}
	return 0
}

func (x *Operation) GetPublishFailedCount() int64 {
	if x != nil {
		return x.PublishFailedCount
	}
	return 0
}

func (x *Operation) GetReconciliationCount() int64 {
	if x != nil {
		return x.ReconciliationCount
	}
	return 0
}

func (x *Operation) GetReconciliationCompletedCount() int64 {
	if x != nil {
		return x.ReconciliationCompletedCount
	}
	return 0
}

func (x *Operation) GetReconciliationFailedCount() int64 {
	if x != nil {
		return x.ReconciliationFailedCount
	}
	return 0
}

func (x *Operation) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Operation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Operation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_libops_v1_operation_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_operation_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_operation_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_libops_v1_operation_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_operation_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_operation_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_libops_v1_operation_api_proto protoreflect.FileDescriptor

const file_libops_v1_operation_api_proto_rawDesc = "" +
	"\n" +
	"\x1dlibops/v1/operation_api.proto\x12\tlibops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x06\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12%\n" +
	"\x0eoperation_type\x18\x03 \x01(\tR\roperationType\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.libops.v1.OperationStatusR\x06status\x12\x1f\n" +
	"\vevent_count\x18\x05 \x01(\x03R\n" +
	"eventCount\x122\n" +
	"\x15event_completed_count\x18\x06 \x01(\x03R\x13eventCompletedCount\x12,\n" +
	"\x12event_failed_count\x18\a \x01(\x03R\x10eventFailedCount\x12#\n" +
	"\rpublish_count\x18\b \x01(\x03R\fpublishCount\x126\n" +
	"\x17publish_completed_count\x18\t \x01(\x03R\x15publishCompletedCount\x120\n" +
	"\x14publish_failed_count\x18\n" +
	" \x01(\x03R\x12publishFailedCount\x121\n" +
	"\x14reconciliation_count\x18\v \x01(\x03R\x13reconciliationCount\x12D\n" +
	"\x1ereconciliation_completed_count\x18\f \x01(\x03R\x1creconciliationCompletedCount\x12>\n" +
	"\x1breconciliation_failed_count\x18\r \x01(\x03R\x19reconciliationFailedCount\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"J\n" +
	"\x14GetOperationResponse\x122\n" +
	"\toperation\x18\x01 \x01(\v2\x14.libops.v1.OperationR\toperation*\xad\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x01\x12\x1e\n" +
	"\x1aOPERATION_STATUS_SUCCEEDED\x10\x02\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19OPERATION_STATUS_CANCELED\x10\x042h\n" +
	"\x10OperationService\x12T\n" +
	"\fGetOperation\x12\x1e.libops.v1.GetOperationRequest\x1a\x1f.libops.v1.GetOperationResponse\"\x03\x90\x02\x01B\x93\x01\n" +
	"\rcom.libops.v1B\x11OperationApiProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_operation_api_proto_rawDescOnce sync.Once
	file_libops_v1_operation_api_proto_rawDescData []byte
)

func file_libops_v1_operation_api_proto_rawDescGZIP() []byte {
	file_libops_v1_operation_api_proto_rawDescOnce.Do(func() {
		file_libops_v1_operation_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_operation_api_proto_rawDesc), len(file_libops_v1_operation_api_proto_rawDesc)))
	})
	return file_libops_v1_operation_api_proto_rawDescData
}

var file_libops_v1_operation_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libops_v1_operation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libops_v1_operation_api_proto_goTypes = []any{
	(OperationStatus)(0),          // 0: libops.v1.OperationStatus
	(*Operation)(nil),             // 1: libops.v1.Operation
	(*GetOperationRequest)(nil),   // 2: libops.v1.GetOperationRequest
	(*GetOperationResponse)(nil),  // 3: libops.v1.GetOperationResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_libops_v1_operation_api_proto_depIdxs = []int32{
	0, // 0: libops.v1.Operation.status:type_name -> libops.v1.OperationStatus
	4, // 1: libops.v1.Operation.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: libops.v1.Operation.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: libops.v1.Operation.completed_at:type_name -> google.protobuf.Timestamp
	1, // 4: libops.v1.GetOperationResponse.operation:type_name -> libops.v1.Operation
	2, // 5: libops.v1.OperationService.GetOperation:input_type -> libops.v1.GetOperationRequest
	3, // 6: libops.v1.OperationService.GetOperation:output_type -> libops.v1.GetOperationResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_libops_v1_operation_api_proto_init() }
func file_libops_v1_operation_api_proto_init() {
	if File_libops_v1_operation_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_operation_api_proto_rawDesc), len(file_libops_v1_operation_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libops_v1_operation_api_proto_goTypes,
		DependencyIndexes: file_libops_v1_operation_api_proto_depIdxs,
		EnumInfos:         file_libops_v1_operation_api_proto_enumTypes,
		MessageInfos:      file_libops_v1_operation_api_proto_msgTypes,
	}.Build()
	File_libops_v1_operation_api_proto = out.File
	file_libops_v1_operation_api_proto_goTypes = nil
	file_libops_v1_operation_api_proto_depIdxs = nil
}
