// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/settings.proto

package libopsv1

import (
	common "github.com/libops/proto/libops/v1/common"
	_ "github.com/libops/proto/libops/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationSetting struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SettingId      string                 `protobuf:"bytes,1,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`                // UUID
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // UUID
	Key            string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                                             // e.g., "max_projects"
	Value          string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                                         // Stored as string
	Editable       bool                   `protobuf:"varint,5,opt,name=editable,proto3" json:"editable,omitempty"`                                  // Can users modify this?
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                             // Optional description
	Status         common.Status          `protobuf:"varint,7,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationSetting) Reset() {
	*x = OrganizationSetting{}
	mi := &file_libops_v1_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSetting) ProtoMessage() {}

func (x *OrganizationSetting) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationSetting.ProtoReflect.Descriptor instead.
func (*OrganizationSetting) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationSetting) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *OrganizationSetting) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OrganizationSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OrganizationSetting) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *OrganizationSetting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationSetting) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

type ProjectSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingId     string                 `protobuf:"bytes,1,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"` // UUID
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // UUID
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                              // e.g., "php_op_mode", "ENV_LOG_LEVEL"
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Editable      bool                   `protobuf:"varint,5,opt,name=editable,proto3" json:"editable,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        common.Status          `protobuf:"varint,7,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSetting) Reset() {
	*x = ProjectSetting{}
	mi := &file_libops_v1_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSetting) ProtoMessage() {}

func (x *ProjectSetting) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSetting.ProtoReflect.Descriptor instead.
func (*ProjectSetting) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectSetting) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *ProjectSetting) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProjectSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProjectSetting) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *ProjectSetting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectSetting) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

type SiteSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingId     string                 `protobuf:"bytes,1,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"` // UUID
	SiteId        string                 `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`          // UUID
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                              // e.g., "ENV_LOG_LEVEL" (overrides project)
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Editable      bool                   `protobuf:"varint,5,opt,name=editable,proto3" json:"editable,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        common.Status          `protobuf:"varint,7,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteSetting) Reset() {
	*x = SiteSetting{}
	mi := &file_libops_v1_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSetting) ProtoMessage() {}

func (x *SiteSetting) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSetting.ProtoReflect.Descriptor instead.
func (*SiteSetting) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{2}
}

func (x *SiteSetting) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *SiteSetting) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SiteSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SiteSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SiteSetting) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *SiteSetting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SiteSetting) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

type CreateOrganizationSettingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value          string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Editable       bool                   `protobuf:"varint,4,opt,name=editable,proto3" json:"editable,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrganizationSettingRequest) Reset() {
	*x = CreateOrganizationSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationSettingRequest) ProtoMessage() {}

func (x *CreateOrganizationSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrganizationSettingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateOrganizationSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateOrganizationSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateOrganizationSettingRequest) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *CreateOrganizationSettingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateOrganizationSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *OrganizationSetting   `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationSettingResponse) Reset() {
	*x = CreateOrganizationSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationSettingResponse) ProtoMessage() {}

func (x *CreateOrganizationSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrganizationSettingResponse) GetSetting() *OrganizationSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type GetOrganizationSettingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SettingId      string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationSettingRequest) Reset() {
	*x = GetOrganizationSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationSettingRequest) ProtoMessage() {}

func (x *GetOrganizationSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationSettingRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrganizationSettingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOrganizationSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

type GetOrganizationSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *OrganizationSetting   `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationSettingResponse) Reset() {
	*x = GetOrganizationSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationSettingResponse) ProtoMessage() {}

func (x *GetOrganizationSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationSettingResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizationSettingResponse) GetSetting() *OrganizationSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type ListOrganizationSettingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrganizationSettingsRequest) Reset() {
	*x = ListOrganizationSettingsRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationSettingsRequest) ProtoMessage() {}

func (x *ListOrganizationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrganizationSettingsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListOrganizationSettingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationSettingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOrganizationSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*OrganizationSetting `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationSettingsResponse) Reset() {
	*x = ListOrganizationSettingsResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationSettingsResponse) ProtoMessage() {}

func (x *ListOrganizationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrganizationSettingsResponse) GetSettings() []*OrganizationSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ListOrganizationSettingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateOrganizationSettingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SettingId      string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	Value          *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	UpdateMask     *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrganizationSettingRequest) Reset() {
	*x = UpdateOrganizationSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationSettingRequest) ProtoMessage() {}

func (x *UpdateOrganizationSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrganizationSettingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *UpdateOrganizationSettingRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *UpdateOrganizationSettingRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateOrganizationSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *OrganizationSetting   `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationSettingResponse) Reset() {
	*x = UpdateOrganizationSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationSettingResponse) ProtoMessage() {}

func (x *UpdateOrganizationSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrganizationSettingResponse) GetSetting() *OrganizationSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type DeleteOrganizationSettingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SettingId      string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteOrganizationSettingRequest) Reset() {
	*x = DeleteOrganizationSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationSettingRequest) ProtoMessage() {}

func (x *DeleteOrganizationSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteOrganizationSettingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeleteOrganizationSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

type CreateProjectSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Editable      bool                   `protobuf:"varint,4,opt,name=editable,proto3" json:"editable,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectSettingRequest) Reset() {
	*x = CreateProjectSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectSettingRequest) ProtoMessage() {}

func (x *CreateProjectSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{12}
}

func (x *CreateProjectSettingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateProjectSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateProjectSettingRequest) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *CreateProjectSettingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProjectSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProjectSetting        `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectSettingResponse) Reset() {
	*x = CreateProjectSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectSettingResponse) ProtoMessage() {}

func (x *CreateProjectSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProjectSettingResponse) GetSetting() *ProjectSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type GetProjectSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSettingRequest) Reset() {
	*x = GetProjectSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSettingRequest) ProtoMessage() {}

func (x *GetProjectSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSettingRequest.ProtoReflect.Descriptor instead.
func (*GetProjectSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{14}
}

func (x *GetProjectSettingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetProjectSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

type GetProjectSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProjectSetting        `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSettingResponse) Reset() {
	*x = GetProjectSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSettingResponse) ProtoMessage() {}

func (x *GetProjectSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSettingResponse.ProtoReflect.Descriptor instead.
func (*GetProjectSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{15}
}

func (x *GetProjectSettingResponse) GetSetting() *ProjectSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type ListProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSettingsRequest) Reset() {
	*x = ListProjectSettingsRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSettingsRequest) ProtoMessage() {}

func (x *ListProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{16}
}

func (x *ListProjectSettingsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListProjectSettingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectSettingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProjectSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*ProjectSetting      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSettingsResponse) Reset() {
	*x = ListProjectSettingsResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSettingsResponse) ProtoMessage() {}

func (x *ListProjectSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectSettingsResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{17}
}

func (x *ListProjectSettingsResponse) GetSettings() []*ProjectSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ListProjectSettingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateProjectSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectSettingRequest) Reset() {
	*x = UpdateProjectSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectSettingRequest) ProtoMessage() {}

func (x *UpdateProjectSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProjectSettingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *UpdateProjectSettingRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *UpdateProjectSettingRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateProjectSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProjectSetting        `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectSettingResponse) Reset() {
	*x = UpdateProjectSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectSettingResponse) ProtoMessage() {}

func (x *UpdateProjectSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateProjectSettingResponse) GetSetting() *ProjectSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type DeleteProjectSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectSettingRequest) Reset() {
	*x = DeleteProjectSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectSettingRequest) ProtoMessage() {}

func (x *DeleteProjectSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteProjectSettingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteProjectSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

type CreateSiteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Editable      bool                   `protobuf:"varint,4,opt,name=editable,proto3" json:"editable,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteSettingRequest) Reset() {
	*x = CreateSiteSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteSettingRequest) ProtoMessage() {}

func (x *CreateSiteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSiteSettingRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *CreateSiteSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSiteSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateSiteSettingRequest) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *CreateSiteSettingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSiteSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *SiteSetting           `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteSettingResponse) Reset() {
	*x = CreateSiteSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteSettingResponse) ProtoMessage() {}

func (x *CreateSiteSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateSiteSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSiteSettingResponse) GetSetting() *SiteSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type GetSiteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingRequest) Reset() {
	*x = GetSiteSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingRequest) ProtoMessage() {}

func (x *GetSiteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSiteSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{23}
}

func (x *GetSiteSettingRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *GetSiteSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

type GetSiteSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *SiteSetting           `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingResponse) Reset() {
	*x = GetSiteSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingResponse) ProtoMessage() {}

func (x *GetSiteSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSiteSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{24}
}

func (x *GetSiteSettingResponse) GetSetting() *SiteSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type ListSiteSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSiteSettingsRequest) Reset() {
	*x = ListSiteSettingsRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSiteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSiteSettingsRequest) ProtoMessage() {}

func (x *ListSiteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSiteSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListSiteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{25}
}

func (x *ListSiteSettingsRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ListSiteSettingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSiteSettingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSiteSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*SiteSetting         `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSiteSettingsResponse) Reset() {
	*x = ListSiteSettingsResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSiteSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSiteSettingsResponse) ProtoMessage() {}

func (x *ListSiteSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSiteSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListSiteSettingsResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{26}
}

func (x *ListSiteSettingsResponse) GetSettings() []*SiteSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ListSiteSettingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateSiteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteSettingRequest) Reset() {
	*x = UpdateSiteSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingRequest) ProtoMessage() {}

func (x *UpdateSiteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateSiteSettingRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *UpdateSiteSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *UpdateSiteSettingRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *UpdateSiteSettingRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateSiteSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *SiteSetting           `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteSettingResponse) Reset() {
	*x = UpdateSiteSettingResponse{}
	mi := &file_libops_v1_settings_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingResponse) ProtoMessage() {}

func (x *UpdateSiteSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateSiteSettingResponse) GetSetting() *SiteSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type DeleteSiteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SettingId     string                 `protobuf:"bytes,2,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSiteSettingRequest) Reset() {
	*x = DeleteSiteSettingRequest{}
	mi := &file_libops_v1_settings_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSiteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSiteSettingRequest) ProtoMessage() {}

func (x *DeleteSiteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_settings_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSiteSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSiteSettingRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_settings_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteSiteSettingRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *DeleteSiteSettingRequest) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

var File_libops_v1_settings_proto protoreflect.FileDescriptor

const file_libops_v1_settings_proto_rawDesc = "" +
	"\n" +
	"\x18libops/v1/settings.proto\x12\tlibops.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a!libops/v1/options/assistant.proto\x1a\x1dlibops/v1/options/audit.proto\x1a\x1dlibops/v1/options/scope.proto\x1a\x1clibops/v1/common/types.proto\"\xf5\x01\n" +
	"\x13OrganizationSetting\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x01 \x01(\tR\tsettingId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x05 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.libops.v1.common.StatusR\x06status\"\xe6\x01\n" +
	"\x0eProjectSetting\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x01 \x01(\tR\tsettingId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x05 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.libops.v1.common.StatusR\x06status\"\xdd\x01\n" +
	"\vSiteSetting\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x01 \x01(\tR\tsettingId\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\tR\x06siteId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x05 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.libops.v1.common.StatusR\x06status\"\xb1\x01\n" +
	" CreateOrganizationSettingRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x04 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"]\n" +
	"!CreateOrganizationSettingResponse\x128\n" +
	"\asetting\x18\x01 \x01(\v2\x1e.libops.v1.OrganizationSettingR\asetting\"g\n" +
	"\x1dGetOrganizationSettingRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\"Z\n" +
	"\x1eGetOrganizationSettingResponse\x128\n" +
	"\asetting\x18\x01 \x01(\v2\x1e.libops.v1.OrganizationSettingR\asetting\"\x86\x01\n" +
	"\x1fListOrganizationSettingsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x86\x01\n" +
	" ListOrganizationSettingsResponse\x12:\n" +
	"\bsettings\x18\x01 \x03(\v2\x1e.libops.v1.OrganizationSettingR\bsettings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcc\x01\n" +
	" UpdateOrganizationSettingRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\b\n" +
	"\x06_value\"]\n" +
	"!UpdateOrganizationSettingResponse\x128\n" +
	"\asetting\x18\x01 \x01(\v2\x1e.libops.v1.OrganizationSettingR\asetting\"j\n" +
	" DeleteOrganizationSettingRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\"\xa2\x01\n" +
	"\x1bCreateProjectSettingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x04 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"S\n" +
	"\x1cCreateProjectSettingResponse\x123\n" +
	"\asetting\x18\x01 \x01(\v2\x19.libops.v1.ProjectSettingR\asetting\"X\n" +
	"\x18GetProjectSettingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\"P\n" +
	"\x19GetProjectSettingResponse\x123\n" +
	"\asetting\x18\x01 \x01(\v2\x19.libops.v1.ProjectSettingR\asetting\"w\n" +
	"\x1aListProjectSettingsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"|\n" +
	"\x1bListProjectSettingsResponse\x125\n" +
	"\bsettings\x18\x01 \x03(\v2\x19.libops.v1.ProjectSettingR\bsettings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xbd\x01\n" +
	"\x1bUpdateProjectSettingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\b\n" +
	"\x06_value\"S\n" +
	"\x1cUpdateProjectSettingResponse\x123\n" +
	"\asetting\x18\x01 \x01(\v2\x19.libops.v1.ProjectSettingR\asetting\"[\n" +
	"\x1bDeleteProjectSettingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\"\x99\x01\n" +
	"\x18CreateSiteSettingRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1a\n" +
	"\beditable\x18\x04 \x01(\bR\beditable\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"M\n" +
	"\x19CreateSiteSettingResponse\x120\n" +
	"\asetting\x18\x01 \x01(\v2\x16.libops.v1.SiteSettingR\asetting\"O\n" +
	"\x15GetSiteSettingRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\"J\n" +
	"\x16GetSiteSettingResponse\x120\n" +
	"\asetting\x18\x01 \x01(\v2\x16.libops.v1.SiteSettingR\asetting\"n\n" +
	"\x17ListSiteSettingsRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x18ListSiteSettingsResponse\x122\n" +
	"\bsettings\x18\x01 \x03(\v2\x16.libops.v1.SiteSettingR\bsettings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb4\x01\n" +
	"\x18UpdateSiteSettingRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\b\n" +
	"\x06_value\"M\n" +
	"\x19UpdateSiteSettingResponse\x120\n" +
	"\asetting\x18\x01 \x01(\v2\x16.libops.v1.SiteSettingR\asetting\"R\n" +
	"\x18DeleteSiteSettingRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x02 \x01(\tR\tsettingId2\xcd\x06\n" +
	"\x1aOrganizationSettingService\x12\xaa\x01\n" +
	"\x19CreateOrganizationSetting\x12+.libops.v1.CreateOrganizationSettingRequest\x1a,.libops.v1.CreateOrganizationSettingResponse\"2\x92\xb5\x18*\b\x03\x10\x02\x18\x01\"\x0fmanage_settings2\x0forganization_id8\x03\x98\xb5\x18\x01\x12\x9c\x01\n" +
	"\x16GetOrganizationSetting\x12(.libops.v1.GetOrganizationSettingRequest\x1a).libops.v1.GetOrganizationSettingResponse\"-\x92\xb5\x18&\b\x03\x10\x01\x18\x01\"\rread_settings*\x0forganization_id\x90\x02\x01\x12\xa2\x01\n" +
	"\x18ListOrganizationSettings\x12*.libops.v1.ListOrganizationSettingsRequest\x1a+.libops.v1.ListOrganizationSettingsResponse\"-\x92\xb5\x18&\b\x03\x10\x01\x18\x01\"\rread_settings*\x0forganization_id\x90\x02\x01\x12\xa8\x01\n" +
	"\x19UpdateOrganizationSetting\x12+.libops.v1.UpdateOrganizationSettingRequest\x1a,.libops.v1.UpdateOrganizationSettingResponse\"0\x92\xb5\x18(\b\x03\x10\x02\x18\x01\"\x0fmanage_settings*\x0forganization_id\x98\xb5\x18\x01\x12\x92\x01\n" +
	"\x19DeleteOrganizationSetting\x12+.libops.v1.DeleteOrganizationSettingRequest\x1a\x16.google.protobuf.Empty\"0\x92\xb5\x18(\b\x03\x10\x02\x18\x01\"\x0fmanage_settings*\x0forganization_id\x98\xb5\x18\x012\xe9\x05\n" +
	"\x15ProjectSettingService\x12\x96\x01\n" +
	"\x14CreateProjectSetting\x12&.libops.v1.CreateProjectSettingRequest\x1a'.libops.v1.CreateProjectSettingResponse\"-\x92\xb5\x18%\b\x04\x10\x02\x18\x01\"\x0fmanage_settings2\n" +
	"project_id8\x04\x98\xb5\x18\x01\x12\x88\x01\n" +
	"\x11GetProjectSetting\x12#.libops.v1.GetProjectSettingRequest\x1a$.libops.v1.GetProjectSettingResponse\"(\x92\xb5\x18!\b\x04\x10\x01\x18\x01\"\rread_settings*\n" +
	"project_id\x90\x02\x01\x12\x8e\x01\n" +
	"\x13ListProjectSettings\x12%.libops.v1.ListProjectSettingsRequest\x1a&.libops.v1.ListProjectSettingsResponse\"(\x92\xb5\x18!\b\x04\x10\x01\x18\x01\"\rread_settings*\n" +
	"project_id\x90\x02\x01\x12\x94\x01\n" +
	"\x14UpdateProjectSetting\x12&.libops.v1.UpdateProjectSettingRequest\x1a'.libops.v1.UpdateProjectSettingResponse\"+\x92\xb5\x18#\b\x04\x10\x02\x18\x01\"\x0fmanage_settings*\n" +
	"project_id\x98\xb5\x18\x01\x12\x83\x01\n" +
	"\x14DeleteProjectSetting\x12&.libops.v1.DeleteProjectSettingRequest\x1a\x16.google.protobuf.Empty\"+\x92\xb5\x18#\b\x04\x10\x02\x18\x01\"\x0fmanage_settings*\n" +
	"project_id\x98\xb5\x18\x012\xab\x05\n" +
	"\x12SiteSettingService\x12\x8a\x01\n" +
	"\x11CreateSiteSetting\x12#.libops.v1.CreateSiteSettingRequest\x1a$.libops.v1.CreateSiteSettingResponse\"*\x92\xb5\x18\"\b\x05\x10\x02\x18\x01\"\x0fmanage_settings2\asite_id8\x05\x98\xb5\x18\x01\x12|\n" +
	"\x0eGetSiteSetting\x12 .libops.v1.GetSiteSettingRequest\x1a!.libops.v1.GetSiteSettingResponse\"%\x92\xb5\x18\x1e\b\x05\x10\x01\x18\x01\"\rread_settings*\asite_id\x90\x02\x01\x12\x82\x01\n" +
	"\x10ListSiteSettings\x12\".libops.v1.ListSiteSettingsRequest\x1a#.libops.v1.ListSiteSettingsResponse\"%\x92\xb5\x18\x1e\b\x05\x10\x01\x18\x01\"\rread_settings*\asite_id\x90\x02\x01\x12\x88\x01\n" +
	"\x11UpdateSiteSetting\x12#.libops.v1.UpdateSiteSettingRequest\x1a$.libops.v1.UpdateSiteSettingResponse\"(\x92\xb5\x18 \b\x05\x10\x02\x18\x01\"\x0fmanage_settings*\asite_id\x98\xb5\x18\x01\x12z\n" +
	"\x11DeleteSiteSetting\x12#.libops.v1.DeleteSiteSettingRequest\x1a\x16.google.protobuf.Empty\"(\x92\xb5\x18 \b\x05\x10\x02\x18\x01\"\x0fmanage_settings*\asite_id\x98\xb5\x18\x01B\x8f\x01\n" +
	"\rcom.libops.v1B\rSettingsProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_settings_proto_rawDescOnce sync.Once
	file_libops_v1_settings_proto_rawDescData []byte
)

func file_libops_v1_settings_proto_rawDescGZIP() []byte {
	file_libops_v1_settings_proto_rawDescOnce.Do(func() {
		file_libops_v1_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_settings_proto_rawDesc), len(file_libops_v1_settings_proto_rawDesc)))
	})
	return file_libops_v1_settings_proto_rawDescData
}

var file_libops_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_libops_v1_settings_proto_goTypes = []any{
	(*OrganizationSetting)(nil),               // 0: libops.v1.OrganizationSetting
	(*ProjectSetting)(nil),                    // 1: libops.v1.ProjectSetting
	(*SiteSetting)(nil),                       // 2: libops.v1.SiteSetting
	(*CreateOrganizationSettingRequest)(nil),  // 3: libops.v1.CreateOrganizationSettingRequest
	(*CreateOrganizationSettingResponse)(nil), // 4: libops.v1.CreateOrganizationSettingResponse
	(*GetOrganizationSettingRequest)(nil),     // 5: libops.v1.GetOrganizationSettingRequest
	(*GetOrganizationSettingResponse)(nil),    // 6: libops.v1.GetOrganizationSettingResponse
	(*ListOrganizationSettingsRequest)(nil),   // 7: libops.v1.ListOrganizationSettingsRequest
	(*ListOrganizationSettingsResponse)(nil),  // 8: libops.v1.ListOrganizationSettingsResponse
	(*UpdateOrganizationSettingRequest)(nil),  // 9: libops.v1.UpdateOrganizationSettingRequest
	(*UpdateOrganizationSettingResponse)(nil), // 10: libops.v1.UpdateOrganizationSettingResponse
	(*DeleteOrganizationSettingRequest)(nil),  // 11: libops.v1.DeleteOrganizationSettingRequest
	(*CreateProjectSettingRequest)(nil),       // 12: libops.v1.CreateProjectSettingRequest
	(*CreateProjectSettingResponse)(nil),      // 13: libops.v1.CreateProjectSettingResponse
	(*GetProjectSettingRequest)(nil),          // 14: libops.v1.GetProjectSettingRequest
	(*GetProjectSettingResponse)(nil),         // 15: libops.v1.GetProjectSettingResponse
	(*ListProjectSettingsRequest)(nil),        // 16: libops.v1.ListProjectSettingsRequest
	(*ListProjectSettingsResponse)(nil),       // 17: libops.v1.ListProjectSettingsResponse
	(*UpdateProjectSettingRequest)(nil),       // 18: libops.v1.UpdateProjectSettingRequest
	(*UpdateProjectSettingResponse)(nil),      // 19: libops.v1.UpdateProjectSettingResponse
	(*DeleteProjectSettingRequest)(nil),       // 20: libops.v1.DeleteProjectSettingRequest
	(*CreateSiteSettingRequest)(nil),          // 21: libops.v1.CreateSiteSettingRequest
	(*CreateSiteSettingResponse)(nil),         // 22: libops.v1.CreateSiteSettingResponse
	(*GetSiteSettingRequest)(nil),             // 23: libops.v1.GetSiteSettingRequest
	(*GetSiteSettingResponse)(nil),            // 24: libops.v1.GetSiteSettingResponse
	(*ListSiteSettingsRequest)(nil),           // 25: libops.v1.ListSiteSettingsRequest
	(*ListSiteSettingsResponse)(nil),          // 26: libops.v1.ListSiteSettingsResponse
	(*UpdateSiteSettingRequest)(nil),          // 27: libops.v1.UpdateSiteSettingRequest
	(*UpdateSiteSettingResponse)(nil),         // 28: libops.v1.UpdateSiteSettingResponse
	(*DeleteSiteSettingRequest)(nil),          // 29: libops.v1.DeleteSiteSettingRequest
	(common.Status)(0),                        // 30: libops.v1.common.Status
	(*fieldmaskpb.FieldMask)(nil),             // 31: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                     // 32: google.protobuf.Empty
}
var file_libops_v1_settings_proto_depIdxs = []int32{
	30, // 0: libops.v1.OrganizationSetting.status:type_name -> libops.v1.common.Status
	30, // 1: libops.v1.ProjectSetting.status:type_name -> libops.v1.common.Status
	30, // 2: libops.v1.SiteSetting.status:type_name -> libops.v1.common.Status
	0,  // 3: libops.v1.CreateOrganizationSettingResponse.setting:type_name -> libops.v1.OrganizationSetting
	0,  // 4: libops.v1.GetOrganizationSettingResponse.setting:type_name -> libops.v1.OrganizationSetting
	0,  // 5: libops.v1.ListOrganizationSettingsResponse.settings:type_name -> libops.v1.OrganizationSetting
	31, // 6: libops.v1.UpdateOrganizationSettingRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 7: libops.v1.UpdateOrganizationSettingResponse.setting:type_name -> libops.v1.OrganizationSetting
	1,  // 8: libops.v1.CreateProjectSettingResponse.setting:type_name -> libops.v1.ProjectSetting
	1,  // 9: libops.v1.GetProjectSettingResponse.setting:type_name -> libops.v1.ProjectSetting
	1,  // 10: libops.v1.ListProjectSettingsResponse.settings:type_name -> libops.v1.ProjectSetting
	31, // 11: libops.v1.UpdateProjectSettingRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 12: libops.v1.UpdateProjectSettingResponse.setting:type_name -> libops.v1.ProjectSetting
	2,  // 13: libops.v1.CreateSiteSettingResponse.setting:type_name -> libops.v1.SiteSetting
	2,  // 14: libops.v1.GetSiteSettingResponse.setting:type_name -> libops.v1.SiteSetting
	2,  // 15: libops.v1.ListSiteSettingsResponse.settings:type_name -> libops.v1.SiteSetting
	31, // 16: libops.v1.UpdateSiteSettingRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 17: libops.v1.UpdateSiteSettingResponse.setting:type_name -> libops.v1.SiteSetting
	3,  // 18: libops.v1.OrganizationSettingService.CreateOrganizationSetting:input_type -> libops.v1.CreateOrganizationSettingRequest
	5,  // 19: libops.v1.OrganizationSettingService.GetOrganizationSetting:input_type -> libops.v1.GetOrganizationSettingRequest
	7,  // 20: libops.v1.OrganizationSettingService.ListOrganizationSettings:input_type -> libops.v1.ListOrganizationSettingsRequest
	9,  // 21: libops.v1.OrganizationSettingService.UpdateOrganizationSetting:input_type -> libops.v1.UpdateOrganizationSettingRequest
	11, // 22: libops.v1.OrganizationSettingService.DeleteOrganizationSetting:input_type -> libops.v1.DeleteOrganizationSettingRequest
	12, // 23: libops.v1.ProjectSettingService.CreateProjectSetting:input_type -> libops.v1.CreateProjectSettingRequest
	14, // 24: libops.v1.ProjectSettingService.GetProjectSetting:input_type -> libops.v1.GetProjectSettingRequest
	16, // 25: libops.v1.ProjectSettingService.ListProjectSettings:input_type -> libops.v1.ListProjectSettingsRequest
	18, // 26: libops.v1.ProjectSettingService.UpdateProjectSetting:input_type -> libops.v1.UpdateProjectSettingRequest
	20, // 27: libops.v1.ProjectSettingService.DeleteProjectSetting:input_type -> libops.v1.DeleteProjectSettingRequest
	21, // 28: libops.v1.SiteSettingService.CreateSiteSetting:input_type -> libops.v1.CreateSiteSettingRequest
	23, // 29: libops.v1.SiteSettingService.GetSiteSetting:input_type -> libops.v1.GetSiteSettingRequest
	25, // 30: libops.v1.SiteSettingService.ListSiteSettings:input_type -> libops.v1.ListSiteSettingsRequest
	27, // 31: libops.v1.SiteSettingService.UpdateSiteSetting:input_type -> libops.v1.UpdateSiteSettingRequest
	29, // 32: libops.v1.SiteSettingService.DeleteSiteSetting:input_type -> libops.v1.DeleteSiteSettingRequest
	4,  // 33: libops.v1.OrganizationSettingService.CreateOrganizationSetting:output_type -> libops.v1.CreateOrganizationSettingResponse
	6,  // 34: libops.v1.OrganizationSettingService.GetOrganizationSetting:output_type -> libops.v1.GetOrganizationSettingResponse
	8,  // 35: libops.v1.OrganizationSettingService.ListOrganizationSettings:output_type -> libops.v1.ListOrganizationSettingsResponse
	10, // 36: libops.v1.OrganizationSettingService.UpdateOrganizationSetting:output_type -> libops.v1.UpdateOrganizationSettingResponse
	32, // 37: libops.v1.OrganizationSettingService.DeleteOrganizationSetting:output_type -> google.protobuf.Empty
	13, // 38: libops.v1.ProjectSettingService.CreateProjectSetting:output_type -> libops.v1.CreateProjectSettingResponse
	15, // 39: libops.v1.ProjectSettingService.GetProjectSetting:output_type -> libops.v1.GetProjectSettingResponse
	17, // 40: libops.v1.ProjectSettingService.ListProjectSettings:output_type -> libops.v1.ListProjectSettingsResponse
	19, // 41: libops.v1.ProjectSettingService.UpdateProjectSetting:output_type -> libops.v1.UpdateProjectSettingResponse
	32, // 42: libops.v1.ProjectSettingService.DeleteProjectSetting:output_type -> google.protobuf.Empty
	22, // 43: libops.v1.SiteSettingService.CreateSiteSetting:output_type -> libops.v1.CreateSiteSettingResponse
	24, // 44: libops.v1.SiteSettingService.GetSiteSetting:output_type -> libops.v1.GetSiteSettingResponse
	26, // 45: libops.v1.SiteSettingService.ListSiteSettings:output_type -> libops.v1.ListSiteSettingsResponse
	28, // 46: libops.v1.SiteSettingService.UpdateSiteSetting:output_type -> libops.v1.UpdateSiteSettingResponse
	32, // 47: libops.v1.SiteSettingService.DeleteSiteSetting:output_type -> google.protobuf.Empty
	33, // [33:48] is the sub-list for method output_type
	18, // [18:33] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_libops_v1_settings_proto_init() }
func file_libops_v1_settings_proto_init() {
	if File_libops_v1_settings_proto != nil {
		return
	}
	file_libops_v1_settings_proto_msgTypes[9].OneofWrappers = []any{}
	file_libops_v1_settings_proto_msgTypes[18].OneofWrappers = []any{}
	file_libops_v1_settings_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_settings_proto_rawDesc), len(file_libops_v1_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_libops_v1_settings_proto_goTypes,
		DependencyIndexes: file_libops_v1_settings_proto_depIdxs,
		MessageInfos:      file_libops_v1_settings_proto_msgTypes,
	}.Build()
	File_libops_v1_settings_proto = out.File
	file_libops_v1_settings_proto_goTypes = nil
	file_libops_v1_settings_proto_depIdxs = nil
}
