// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/task_api.proto

package libopsv1

import (
	_ "github.com/libops/proto/libops/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_NEEDS_INPUT TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 5
	TaskStatus_TASK_STATUS_CANCELED    TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_QUEUED",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_NEEDS_INPUT",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_COMPLETED",
		6: "TASK_STATUS_CANCELED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_QUEUED":      1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_NEEDS_INPUT": 3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_COMPLETED":   5,
		"TASK_STATUS_CANCELED":    6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_task_api_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_libops_v1_task_api_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{0}
}

type TaskResultType int32

const (
	TaskResultType_TASK_RESULT_UNSPECIFIED     TaskResultType = 0
	TaskResultType_TASK_RESULT_PROJECT_CREATED TaskResultType = 1
	TaskResultType_TASK_RESULT_PR_CREATED      TaskResultType = 2
	TaskResultType_TASK_RESULT_DEPLOYMENT      TaskResultType = 3
	TaskResultType_TASK_RESULT_API_ACTION      TaskResultType = 4
)

// Enum value maps for TaskResultType.
var (
	TaskResultType_name = map[int32]string{
		0: "TASK_RESULT_UNSPECIFIED",
		1: "TASK_RESULT_PROJECT_CREATED",
		2: "TASK_RESULT_PR_CREATED",
		3: "TASK_RESULT_DEPLOYMENT",
		4: "TASK_RESULT_API_ACTION",
	}
	TaskResultType_value = map[string]int32{
		"TASK_RESULT_UNSPECIFIED":     0,
		"TASK_RESULT_PROJECT_CREATED": 1,
		"TASK_RESULT_PR_CREATED":      2,
		"TASK_RESULT_DEPLOYMENT":      3,
		"TASK_RESULT_API_ACTION":      4,
	}
)

func (x TaskResultType) Enum() *TaskResultType {
	p := new(TaskResultType)
	*p = x
	return p
}

func (x TaskResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_task_api_proto_enumTypes[1].Descriptor()
}

func (TaskResultType) Type() protoreflect.EnumType {
	return &file_libops_v1_task_api_proto_enumTypes[1]
}

func (x TaskResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResultType.Descriptor instead.
func (TaskResultType) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{1}
}

type TaskLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogEntry) Reset() {
	*x = TaskLogEntry{}
	mi := &file_libops_v1_task_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogEntry) ProtoMessage() {}

func (x *TaskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogEntry.ProtoReflect.Descriptor instead.
func (*TaskLogEntry) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{0}
}

func (x *TaskLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *TaskLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLogEntry) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type TaskInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Fields        *structpb.Struct       `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInput) Reset() {
	*x = TaskInput{}
	mi := &file_libops_v1_task_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInput) ProtoMessage() {}

func (x *TaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInput.ProtoReflect.Descriptor instead.
func (*TaskInput) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskInput) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_libops_v1_task_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TaskMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskResultType         `protobuf:"varint,1,opt,name=type,proto3,enum=libops.v1.TaskResultType" json:"type,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteId        string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	PrUrl         string                 `protobuf:"bytes,4,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,5,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ApiAction     *TaskApiAction         `protobuf:"bytes,7,opt,name=api_action,json=apiAction,proto3" json:"api_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_libops_v1_task_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetType() TaskResultType {
	if x != nil {
		return x.Type
	}
	return TaskResultType_TASK_RESULT_UNSPECIFIED
}

func (x *TaskResult) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TaskResult) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *TaskResult) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *TaskResult) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *TaskResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskResult) GetApiAction() *TaskApiAction {
	if x != nil {
		return x.ApiAction
	}
	return nil
}

type TaskApiAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       *structpb.Struct       `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskApiAction) Reset() {
	*x = TaskApiAction{}
	mi := &file_libops_v1_task_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskApiAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskApiAction) ProtoMessage() {}

func (x *TaskApiAction) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskApiAction.ProtoReflect.Descriptor instead.
func (*TaskApiAction) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{4}
}

func (x *TaskApiAction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TaskApiAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TaskApiAction) GetHeaders() *structpb.Struct {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TaskApiAction) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TaskApiAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteId         string                 `protobuf:"bytes,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Status         TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=libops.v1.TaskStatus" json:"status,omitempty"`
	Logs           []*TaskLogEntry        `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	Results        []*TaskResult          `protobuf:"bytes,8,rep,name=results,proto3" json:"results,omitempty"`
	InputRequest   *TaskInput             `protobuf:"bytes,9,opt,name=input_request,json=inputRequest,proto3" json:"input_request,omitempty"`
	InputResponse  *TaskInput             `protobuf:"bytes,10,opt,name=input_response,json=inputResponse,proto3" json:"input_response,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Messages       []*TaskMessage         `protobuf:"bytes,15,rep,name=messages,proto3" json:"messages,omitempty"`
	AgentModel     string                 `protobuf:"bytes,16,opt,name=agent_model,json=agentModel,proto3" json:"agent_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_libops_v1_task_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Task) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetLogs() []*TaskLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Task) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Task) GetInputRequest() *TaskInput {
	if x != nil {
		return x.InputRequest
	}
	return nil
}

func (x *Task) GetInputResponse() *TaskInput {
	if x != nil {
		return x.InputResponse
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetMessages() []*TaskMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Task) GetAgentModel() string {
	if x != nil {
		return x.AgentModel
	}
	return ""
}

type TaskUsageBudget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricKey     string                 `protobuf:"bytes,1,opt,name=metric_key,json=metricKey,proto3" json:"metric_key,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Used          int64                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Remaining     int64                  `protobuf:"varint,5,opt,name=remaining,proto3" json:"remaining,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUsageBudget) Reset() {
	*x = TaskUsageBudget{}
	mi := &file_libops_v1_task_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUsageBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUsageBudget) ProtoMessage() {}

func (x *TaskUsageBudget) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUsageBudget.ProtoReflect.Descriptor instead.
func (*TaskUsageBudget) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{6}
}

func (x *TaskUsageBudget) GetMetricKey() string {
	if x != nil {
		return x.MetricKey
	}
	return ""
}

func (x *TaskUsageBudget) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TaskUsageBudget) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *TaskUsageBudget) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TaskUsageBudget) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *TaskUsageBudget) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *TaskUsageBudget) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *TaskUsageBudget) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteId          string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ClientRequestId string                 `protobuf:"bytes,5,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AgentModel      string                 `protobuf:"bytes,7,opt,name=agent_model,json=agentModel,proto3" json:"agent_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *CreateTaskRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateTaskRequest) GetAgentModel() string {
	if x != nil {
		return x.AgentModel
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteId         string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListTasksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListTasksRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TaskUsage     *TaskUsageBudget       `protobuf:"bytes,2,opt,name=task_usage,json=taskUsage,proto3" json:"task_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTaskUsage() *TaskUsageBudget {
	if x != nil {
		return x.TaskUsage
	}
	return nil
}

type UpdateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=libops.v1.TaskStatus" json:"status,omitempty"`
	Prompt         string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	InputRequest   *TaskInput             `protobuf:"bytes,5,opt,name=input_request,json=inputRequest,proto3" json:"input_request,omitempty"`
	InputResponse  *TaskInput             `protobuf:"bytes,6,opt,name=input_response,json=inputResponse,proto3" json:"input_response,omitempty"`
	Results        []*TaskResult          `protobuf:"bytes,7,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTaskRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTaskRequest) GetInputRequest() *TaskInput {
	if x != nil {
		return x.InputRequest
	}
	return nil
}

func (x *UpdateTaskRequest) GetInputResponse() *TaskInput {
	if x != nil {
		return x.InputResponse
	}
	return nil
}

func (x *UpdateTaskRequest) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CancelTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTaskRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AppendTaskLogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Entry          *TaskLogEntry          `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendTaskLogRequest) Reset() {
	*x = AppendTaskLogRequest{}
	mi := &file_libops_v1_task_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendTaskLogRequest) ProtoMessage() {}

func (x *AppendTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendTaskLogRequest.ProtoReflect.Descriptor instead.
func (*AppendTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{17}
}

func (x *AppendTaskLogRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AppendTaskLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AppendTaskLogRequest) GetEntry() *TaskLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AppendTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendTaskLogResponse) Reset() {
	*x = AppendTaskLogResponse{}
	mi := &file_libops_v1_task_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendTaskLogResponse) ProtoMessage() {}

func (x *AppendTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_task_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendTaskLogResponse.ProtoReflect.Descriptor instead.
func (*AppendTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_libops_v1_task_api_proto_rawDescGZIP(), []int{18}
}

func (x *AppendTaskLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_libops_v1_task_api_proto protoreflect.FileDescriptor

const file_libops_v1_task_api_proto_rawDesc = "" +
	"\n" +
	"\x18libops/v1/task_api.proto\x12\tlibops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1dlibops/v1/options/scope.proto\"\xb1\x01\n" +
	"\fTaskLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x127\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\"V\n" +
	"\tTaskInput\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x06fields\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06fields\"v\n" +
	"\vTaskMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9d\x02\n" +
	"\n" +
	"TaskResult\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.libops.v1.TaskResultTypeR\x04type\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x15\n" +
	"\x06pr_url\x18\x04 \x01(\tR\x05prUrl\x12#\n" +
	"\rdeployment_id\x18\x05 \x01(\tR\fdeploymentId\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\n" +
	"api_action\x18\a \x01(\v2\x18.libops.v1.TaskApiActionR\tapiAction\"\xbd\x01\n" +
	"\rTaskApiAction\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x121\n" +
	"\aheaders\x18\x03 \x01(\v2\x17.google.protobuf.StructR\aheaders\x12+\n" +
	"\x04body\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04body\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xe2\x05\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\tR\x06siteId\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.libops.v1.TaskStatusR\x06status\x12+\n" +
	"\x04logs\x18\a \x03(\v2\x17.libops.v1.TaskLogEntryR\x04logs\x12/\n" +
	"\aresults\x18\b \x03(\v2\x15.libops.v1.TaskResultR\aresults\x129\n" +
	"\rinput_request\x18\t \x01(\v2\x14.libops.v1.TaskInputR\finputRequest\x12;\n" +
	"\x0einput_response\x18\n" +
	" \x01(\v2\x14.libops.v1.TaskInputR\rinputResponse\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x122\n" +
	"\bmessages\x18\x0f \x03(\v2\x16.libops.v1.TaskMessageR\bmessages\x12\x1f\n" +
	"\vagent_model\x18\x10 \x01(\tR\n" +
	"agentModel\"\xa2\x02\n" +
	"\x0fTaskUsageBudget\x12\x1d\n" +
	"\n" +
	"metric_key\x18\x01 \x01(\tR\tmetricKey\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x05 \x01(\x03R\tremaining\x12=\n" +
	"\fperiod_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\x8e\x02\n" +
	"\x11CreateTaskRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12*\n" +
	"\x11client_request_id\x18\x05 \x01(\tR\x0fclientRequestId\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1f\n" +
	"\vagent_model\x18\a \x01(\tR\n" +
	"agentModel\"9\n" +
	"\x12CreateTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.libops.v1.TaskR\x04task\"R\n" +
	"\x0eGetTaskRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"6\n" +
	"\x0fGetTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.libops.v1.TaskR\x04task\"\xa1\x01\n" +
	"\x10ListTasksRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"u\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.libops.v1.TaskR\x05tasks\x129\n" +
	"\n" +
	"task_usage\x18\x02 \x01(\v2\x1a.libops.v1.TaskUsageBudgetR\ttaskUsage\"\xc5\x02\n" +
	"\x11UpdateTaskRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.libops.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x129\n" +
	"\rinput_request\x18\x05 \x01(\v2\x14.libops.v1.TaskInputR\finputRequest\x12;\n" +
	"\x0einput_response\x18\x06 \x01(\v2\x14.libops.v1.TaskInputR\rinputResponse\x12/\n" +
	"\aresults\x18\a \x03(\v2\x15.libops.v1.TaskResultR\aresults\"9\n" +
	"\x12UpdateTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.libops.v1.TaskR\x04task\"U\n" +
	"\x11CancelTaskRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"9\n" +
	"\x12CancelTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.libops.v1.TaskR\x04task\"\x87\x01\n" +
	"\x14AppendTaskLogRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12-\n" +
	"\x05entry\x18\x03 \x01(\v2\x17.libops.v1.TaskLogEntryR\x05entry\"1\n" +
	"\x15AppendTaskLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xc4\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17TASK_STATUS_NEEDS_INPUT\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x05\x12\x18\n" +
	"\x14TASK_STATUS_CANCELED\x10\x06*\xa2\x01\n" +
	"\x0eTaskResultType\x12\x1b\n" +
	"\x17TASK_RESULT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTASK_RESULT_PROJECT_CREATED\x10\x01\x12\x1a\n" +
	"\x16TASK_RESULT_PR_CREATED\x10\x02\x12\x1a\n" +
	"\x16TASK_RESULT_DEPLOYMENT\x10\x03\x12\x1a\n" +
	"\x16TASK_RESULT_API_ACTION\x10\x042\xf7\x05\n" +
	"\vTaskService\x12z\n" +
	"\n" +
	"CreateTask\x12\x1c.libops.v1.CreateTaskRequest\x1a\x1d.libops.v1.CreateTaskResponse\"/\x92\xb5\x18+\b\x03\x10\x02\x18\x01\"\x12write:organization*\x0forganization_id\x12s\n" +
	"\aGetTask\x12\x19.libops.v1.GetTaskRequest\x1a\x1a.libops.v1.GetTaskResponse\"1\x92\xb5\x18*\b\x03\x10\x01\x18\x01\"\x11read:organization*\x0forganization_id\x90\x02\x01\x12y\n" +
	"\tListTasks\x12\x1b.libops.v1.ListTasksRequest\x1a\x1c.libops.v1.ListTasksResponse\"1\x92\xb5\x18*\b\x03\x10\x01\x18\x01\"\x11read:organization*\x0forganization_id\x90\x02\x01\x12z\n" +
	"\n" +
	"UpdateTask\x12\x1c.libops.v1.UpdateTaskRequest\x1a\x1d.libops.v1.UpdateTaskResponse\"/\x92\xb5\x18+\b\x03\x10\x02\x18\x01\"\x12write:organization*\x0forganization_id\x12z\n" +
	"\n" +
	"CancelTask\x12\x1c.libops.v1.CancelTaskRequest\x1a\x1d.libops.v1.CancelTaskResponse\"/\x92\xb5\x18+\b\x03\x10\x02\x18\x01\"\x12write:organization*\x0forganization_id\x12\x83\x01\n" +
	"\rAppendTaskLog\x12\x1f.libops.v1.AppendTaskLogRequest\x1a .libops.v1.AppendTaskLogResponse\"/\x92\xb5\x18+\b\x03\x10\x02\x18\x01\"\x12write:organization*\x0forganization_idB\x8e\x01\n" +
	"\rcom.libops.v1B\fTaskApiProtoP\x01Z*github.com/libops/proto/libops/v1;libopsv1\xa2\x02\x03LXX\xaa\x02\tLibops.V1\xca\x02\tLibops\\V1\xe2\x02\x15Libops\\V1\\GPBMetadata\xea\x02\n" +
	"Libops::V1b\x06proto3"

var (
	file_libops_v1_task_api_proto_rawDescOnce sync.Once
	file_libops_v1_task_api_proto_rawDescData []byte
)

func file_libops_v1_task_api_proto_rawDescGZIP() []byte {
	file_libops_v1_task_api_proto_rawDescOnce.Do(func() {
		file_libops_v1_task_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_task_api_proto_rawDesc), len(file_libops_v1_task_api_proto_rawDesc)))
	})
	return file_libops_v1_task_api_proto_rawDescData
}

var file_libops_v1_task_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_libops_v1_task_api_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_libops_v1_task_api_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: libops.v1.TaskStatus
	(TaskResultType)(0),           // 1: libops.v1.TaskResultType
	(*TaskLogEntry)(nil),          // 2: libops.v1.TaskLogEntry
	(*TaskInput)(nil),             // 3: libops.v1.TaskInput
	(*TaskMessage)(nil),           // 4: libops.v1.TaskMessage
	(*TaskResult)(nil),            // 5: libops.v1.TaskResult
	(*TaskApiAction)(nil),         // 6: libops.v1.TaskApiAction
	(*Task)(nil),                  // 7: libops.v1.Task
	(*TaskUsageBudget)(nil),       // 8: libops.v1.TaskUsageBudget
	(*CreateTaskRequest)(nil),     // 9: libops.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 10: libops.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),        // 11: libops.v1.GetTaskRequest
	(*GetTaskResponse)(nil),       // 12: libops.v1.GetTaskResponse
	(*ListTasksRequest)(nil),      // 13: libops.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 14: libops.v1.ListTasksResponse
	(*UpdateTaskRequest)(nil),     // 15: libops.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),    // 16: libops.v1.UpdateTaskResponse
	(*CancelTaskRequest)(nil),     // 17: libops.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 18: libops.v1.CancelTaskResponse
	(*AppendTaskLogRequest)(nil),  // 19: libops.v1.AppendTaskLogRequest
	(*AppendTaskLogResponse)(nil), // 20: libops.v1.AppendTaskLogResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 22: google.protobuf.Struct
}
var file_libops_v1_task_api_proto_depIdxs = []int32{
	21, // 0: libops.v1.TaskLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	22, // 1: libops.v1.TaskLogEntry.attributes:type_name -> google.protobuf.Struct
	22, // 2: libops.v1.TaskInput.fields:type_name -> google.protobuf.Struct
	21, // 3: libops.v1.TaskMessage.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: libops.v1.TaskResult.type:type_name -> libops.v1.TaskResultType
	22, // 5: libops.v1.TaskResult.metadata:type_name -> google.protobuf.Struct
	6,  // 6: libops.v1.TaskResult.api_action:type_name -> libops.v1.TaskApiAction
	22, // 7: libops.v1.TaskApiAction.headers:type_name -> google.protobuf.Struct
	22, // 8: libops.v1.TaskApiAction.body:type_name -> google.protobuf.Struct
	0,  // 9: libops.v1.Task.status:type_name -> libops.v1.TaskStatus
	2,  // 10: libops.v1.Task.logs:type_name -> libops.v1.TaskLogEntry
	5,  // 11: libops.v1.Task.results:type_name -> libops.v1.TaskResult
	3,  // 12: libops.v1.Task.input_request:type_name -> libops.v1.TaskInput
	3,  // 13: libops.v1.Task.input_response:type_name -> libops.v1.TaskInput
	21, // 14: libops.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	21, // 15: libops.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	21, // 16: libops.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	21, // 17: libops.v1.Task.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 18: libops.v1.Task.messages:type_name -> libops.v1.TaskMessage
	21, // 19: libops.v1.TaskUsageBudget.period_start:type_name -> google.protobuf.Timestamp
	21, // 20: libops.v1.TaskUsageBudget.period_end:type_name -> google.protobuf.Timestamp
	22, // 21: libops.v1.CreateTaskRequest.metadata:type_name -> google.protobuf.Struct
	7,  // 22: libops.v1.CreateTaskResponse.task:type_name -> libops.v1.Task
	7,  // 23: libops.v1.GetTaskResponse.task:type_name -> libops.v1.Task
	7,  // 24: libops.v1.ListTasksResponse.tasks:type_name -> libops.v1.Task
	8,  // 25: libops.v1.ListTasksResponse.task_usage:type_name -> libops.v1.TaskUsageBudget
	0,  // 26: libops.v1.UpdateTaskRequest.status:type_name -> libops.v1.TaskStatus
	3,  // 27: libops.v1.UpdateTaskRequest.input_request:type_name -> libops.v1.TaskInput
	3,  // 28: libops.v1.UpdateTaskRequest.input_response:type_name -> libops.v1.TaskInput
	5,  // 29: libops.v1.UpdateTaskRequest.results:type_name -> libops.v1.TaskResult
	7,  // 30: libops.v1.UpdateTaskResponse.task:type_name -> libops.v1.Task
	7,  // 31: libops.v1.CancelTaskResponse.task:type_name -> libops.v1.Task
	2,  // 32: libops.v1.AppendTaskLogRequest.entry:type_name -> libops.v1.TaskLogEntry
	9,  // 33: libops.v1.TaskService.CreateTask:input_type -> libops.v1.CreateTaskRequest
	11, // 34: libops.v1.TaskService.GetTask:input_type -> libops.v1.GetTaskRequest
	13, // 35: libops.v1.TaskService.ListTasks:input_type -> libops.v1.ListTasksRequest
	15, // 36: libops.v1.TaskService.UpdateTask:input_type -> libops.v1.UpdateTaskRequest
	17, // 37: libops.v1.TaskService.CancelTask:input_type -> libops.v1.CancelTaskRequest
	19, // 38: libops.v1.TaskService.AppendTaskLog:input_type -> libops.v1.AppendTaskLogRequest
	10, // 39: libops.v1.TaskService.CreateTask:output_type -> libops.v1.CreateTaskResponse
	12, // 40: libops.v1.TaskService.GetTask:output_type -> libops.v1.GetTaskResponse
	14, // 41: libops.v1.TaskService.ListTasks:output_type -> libops.v1.ListTasksResponse
	16, // 42: libops.v1.TaskService.UpdateTask:output_type -> libops.v1.UpdateTaskResponse
	18, // 43: libops.v1.TaskService.CancelTask:output_type -> libops.v1.CancelTaskResponse
	20, // 44: libops.v1.TaskService.AppendTaskLog:output_type -> libops.v1.AppendTaskLogResponse
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_libops_v1_task_api_proto_init() }
func file_libops_v1_task_api_proto_init() {
	if File_libops_v1_task_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_task_api_proto_rawDesc), len(file_libops_v1_task_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libops_v1_task_api_proto_goTypes,
		DependencyIndexes: file_libops_v1_task_api_proto_depIdxs,
		EnumInfos:         file_libops_v1_task_api_proto_enumTypes,
		MessageInfos:      file_libops_v1_task_api_proto_msgTypes,
	}.Build()
	File_libops_v1_task_api_proto = out.File
	file_libops_v1_task_api_proto_goTypes = nil
	file_libops_v1_task_api_proto_depIdxs = nil
}
