// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/common/site.proto

package common

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainKind int32

const (
	DomainKind_DOMAIN_KIND_UNSPECIFIED DomainKind = 0
	DomainKind_DOMAIN_KIND_MANAGED     DomainKind = 1
	DomainKind_DOMAIN_KIND_VANITY      DomainKind = 2
)

// Enum value maps for DomainKind.
var (
	DomainKind_name = map[int32]string{
		0: "DOMAIN_KIND_UNSPECIFIED",
		1: "DOMAIN_KIND_MANAGED",
		2: "DOMAIN_KIND_VANITY",
	}
	DomainKind_value = map[string]int32{
		"DOMAIN_KIND_UNSPECIFIED": 0,
		"DOMAIN_KIND_MANAGED":     1,
		"DOMAIN_KIND_VANITY":      2,
	}
)

func (x DomainKind) Enum() *DomainKind {
	p := new(DomainKind)
	*p = x
	return p
}

func (x DomainKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainKind) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_site_proto_enumTypes[0].Descriptor()
}

func (DomainKind) Type() protoreflect.EnumType {
	return &file_libops_v1_common_site_proto_enumTypes[0]
}

func (x DomainKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainKind.Descriptor instead.
func (DomainKind) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{0}
}

type DomainProvisioningState int32

const (
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_UNSPECIFIED                 DomainProvisioningState = 0
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_AWAITING_OWNERSHIP_PROOF    DomainProvisioningState = 1
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_PREPARING_DNS_AUTHORIZATION DomainProvisioningState = 2
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_AWAITING_CERTIFICATE_DNS    DomainProvisioningState = 3
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_PROVISIONING_CERTIFICATE    DomainProvisioningState = 4
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_PROVISIONING_MAP_ENTRY      DomainProvisioningState = 5
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_READY_FOR_TRAFFIC           DomainProvisioningState = 6
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_ACTIVE                      DomainProvisioningState = 7
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_DEGRADED                    DomainProvisioningState = 8
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_FAILED                      DomainProvisioningState = 9
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_DELETING                    DomainProvisioningState = 10
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_DELETED                     DomainProvisioningState = 11
	DomainProvisioningState_DOMAIN_PROVISIONING_STATE_EXPIRED                     DomainProvisioningState = 12
)

// Enum value maps for DomainProvisioningState.
var (
	DomainProvisioningState_name = map[int32]string{
		0:  "DOMAIN_PROVISIONING_STATE_UNSPECIFIED",
		1:  "DOMAIN_PROVISIONING_STATE_AWAITING_OWNERSHIP_PROOF",
		2:  "DOMAIN_PROVISIONING_STATE_PREPARING_DNS_AUTHORIZATION",
		3:  "DOMAIN_PROVISIONING_STATE_AWAITING_CERTIFICATE_DNS",
		4:  "DOMAIN_PROVISIONING_STATE_PROVISIONING_CERTIFICATE",
		5:  "DOMAIN_PROVISIONING_STATE_PROVISIONING_MAP_ENTRY",
		6:  "DOMAIN_PROVISIONING_STATE_READY_FOR_TRAFFIC",
		7:  "DOMAIN_PROVISIONING_STATE_ACTIVE",
		8:  "DOMAIN_PROVISIONING_STATE_DEGRADED",
		9:  "DOMAIN_PROVISIONING_STATE_FAILED",
		10: "DOMAIN_PROVISIONING_STATE_DELETING",
		11: "DOMAIN_PROVISIONING_STATE_DELETED",
		12: "DOMAIN_PROVISIONING_STATE_EXPIRED",
	}
	DomainProvisioningState_value = map[string]int32{
		"DOMAIN_PROVISIONING_STATE_UNSPECIFIED":                 0,
		"DOMAIN_PROVISIONING_STATE_AWAITING_OWNERSHIP_PROOF":    1,
		"DOMAIN_PROVISIONING_STATE_PREPARING_DNS_AUTHORIZATION": 2,
		"DOMAIN_PROVISIONING_STATE_AWAITING_CERTIFICATE_DNS":    3,
		"DOMAIN_PROVISIONING_STATE_PROVISIONING_CERTIFICATE":    4,
		"DOMAIN_PROVISIONING_STATE_PROVISIONING_MAP_ENTRY":      5,
		"DOMAIN_PROVISIONING_STATE_READY_FOR_TRAFFIC":           6,
		"DOMAIN_PROVISIONING_STATE_ACTIVE":                      7,
		"DOMAIN_PROVISIONING_STATE_DEGRADED":                    8,
		"DOMAIN_PROVISIONING_STATE_FAILED":                      9,
		"DOMAIN_PROVISIONING_STATE_DELETING":                    10,
		"DOMAIN_PROVISIONING_STATE_DELETED":                     11,
		"DOMAIN_PROVISIONING_STATE_EXPIRED":                     12,
	}
)

func (x DomainProvisioningState) Enum() *DomainProvisioningState {
	p := new(DomainProvisioningState)
	*p = x
	return p
}

func (x DomainProvisioningState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainProvisioningState) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_site_proto_enumTypes[1].Descriptor()
}

func (DomainProvisioningState) Type() protoreflect.EnumType {
	return &file_libops_v1_common_site_proto_enumTypes[1]
}

func (x DomainProvisioningState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainProvisioningState.Descriptor instead.
func (DomainProvisioningState) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{1}
}

type DomainRouteState int32

const (
	DomainRouteState_DOMAIN_ROUTE_STATE_UNSPECIFIED DomainRouteState = 0
	DomainRouteState_DOMAIN_ROUTE_STATE_PENDING     DomainRouteState = 1
	DomainRouteState_DOMAIN_ROUTE_STATE_ENABLED     DomainRouteState = 2
	DomainRouteState_DOMAIN_ROUTE_STATE_BLOCKED     DomainRouteState = 3
	DomainRouteState_DOMAIN_ROUTE_STATE_DELETING    DomainRouteState = 4
	DomainRouteState_DOMAIN_ROUTE_STATE_DELETED     DomainRouteState = 5
)

// Enum value maps for DomainRouteState.
var (
	DomainRouteState_name = map[int32]string{
		0: "DOMAIN_ROUTE_STATE_UNSPECIFIED",
		1: "DOMAIN_ROUTE_STATE_PENDING",
		2: "DOMAIN_ROUTE_STATE_ENABLED",
		3: "DOMAIN_ROUTE_STATE_BLOCKED",
		4: "DOMAIN_ROUTE_STATE_DELETING",
		5: "DOMAIN_ROUTE_STATE_DELETED",
	}
	DomainRouteState_value = map[string]int32{
		"DOMAIN_ROUTE_STATE_UNSPECIFIED": 0,
		"DOMAIN_ROUTE_STATE_PENDING":     1,
		"DOMAIN_ROUTE_STATE_ENABLED":     2,
		"DOMAIN_ROUTE_STATE_BLOCKED":     3,
		"DOMAIN_ROUTE_STATE_DELETING":    4,
		"DOMAIN_ROUTE_STATE_DELETED":     5,
	}
)

func (x DomainRouteState) Enum() *DomainRouteState {
	p := new(DomainRouteState)
	*p = x
	return p
}

func (x DomainRouteState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainRouteState) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_site_proto_enumTypes[2].Descriptor()
}

func (DomainRouteState) Type() protoreflect.EnumType {
	return &file_libops_v1_common_site_proto_enumTypes[2]
}

func (x DomainRouteState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainRouteState.Descriptor instead.
func (DomainRouteState) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{2}
}

type DnsRecordPurpose int32

const (
	DnsRecordPurpose_DNS_RECORD_PURPOSE_UNSPECIFIED               DnsRecordPurpose = 0
	DnsRecordPurpose_DNS_RECORD_PURPOSE_OWNERSHIP_PROOF           DnsRecordPurpose = 1
	DnsRecordPurpose_DNS_RECORD_PURPOSE_CERTIFICATE_AUTHORIZATION DnsRecordPurpose = 2
	DnsRecordPurpose_DNS_RECORD_PURPOSE_TRAFFIC                   DnsRecordPurpose = 3
	DnsRecordPurpose_DNS_RECORD_PURPOSE_SSH                       DnsRecordPurpose = 4
)

// Enum value maps for DnsRecordPurpose.
var (
	DnsRecordPurpose_name = map[int32]string{
		0: "DNS_RECORD_PURPOSE_UNSPECIFIED",
		1: "DNS_RECORD_PURPOSE_OWNERSHIP_PROOF",
		2: "DNS_RECORD_PURPOSE_CERTIFICATE_AUTHORIZATION",
		3: "DNS_RECORD_PURPOSE_TRAFFIC",
		4: "DNS_RECORD_PURPOSE_SSH",
	}
	DnsRecordPurpose_value = map[string]int32{
		"DNS_RECORD_PURPOSE_UNSPECIFIED":               0,
		"DNS_RECORD_PURPOSE_OWNERSHIP_PROOF":           1,
		"DNS_RECORD_PURPOSE_CERTIFICATE_AUTHORIZATION": 2,
		"DNS_RECORD_PURPOSE_TRAFFIC":                   3,
		"DNS_RECORD_PURPOSE_SSH":                       4,
	}
)

func (x DnsRecordPurpose) Enum() *DnsRecordPurpose {
	p := new(DnsRecordPurpose)
	*p = x
	return p
}

func (x DnsRecordPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DnsRecordPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_site_proto_enumTypes[3].Descriptor()
}

func (DnsRecordPurpose) Type() protoreflect.EnumType {
	return &file_libops_v1_common_site_proto_enumTypes[3]
}

func (x DnsRecordPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DnsRecordPurpose.Descriptor instead.
func (DnsRecordPurpose) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{3}
}

type DnsRecordInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Purpose       DnsRecordPurpose       `protobuf:"varint,5,opt,name=purpose,proto3,enum=libops.v1.common.DnsRecordPurpose" json:"purpose,omitempty"`
	Retain        bool                   `protobuf:"varint,6,opt,name=retain,proto3" json:"retain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecordInstruction) Reset() {
	*x = DnsRecordInstruction{}
	mi := &file_libops_v1_common_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecordInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecordInstruction) ProtoMessage() {}

func (x *DnsRecordInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_common_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecordInstruction.ProtoReflect.Descriptor instead.
func (*DnsRecordInstruction) Descriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{0}
}

func (x *DnsRecordInstruction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecordInstruction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DnsRecordInstruction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DnsRecordInstruction) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DnsRecordInstruction) GetPurpose() DnsRecordPurpose {
	if x != nil {
		return x.Purpose
	}
	return DnsRecordPurpose_DNS_RECORD_PURPOSE_UNSPECIFIED
}

func (x *DnsRecordInstruction) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

type DomainConfig struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	DomainId          string                  `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	SiteId            string                  `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Hostname          string                  `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Kind              DomainKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=libops.v1.common.DomainKind" json:"kind,omitempty"`
	ProvisioningState DomainProvisioningState `protobuf:"varint,5,opt,name=provisioning_state,json=provisioningState,proto3,enum=libops.v1.common.DomainProvisioningState" json:"provisioning_state,omitempty"`
	RouteState        DomainRouteState        `protobuf:"varint,6,opt,name=route_state,json=routeState,proto3,enum=libops.v1.common.DomainRouteState" json:"route_state,omitempty"`
	DnsInstructions   []*DnsRecordInstruction `protobuf:"bytes,7,rep,name=dns_instructions,json=dnsInstructions,proto3" json:"dns_instructions,omitempty"`
	ManagedHostname   string                  `protobuf:"bytes,8,opt,name=managed_hostname,json=managedHostname,proto3" json:"managed_hostname,omitempty"`
	SshHostname       string                  `protobuf:"bytes,9,opt,name=ssh_hostname,json=sshHostname,proto3" json:"ssh_hostname,omitempty"`
	RouteReady        bool                    `protobuf:"varint,10,opt,name=route_ready,json=routeReady,proto3" json:"route_ready,omitempty"`
	FailureReason     string                  `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	FailureMessage    string                  `protobuf:"bytes,12,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	Retryable         bool                    `protobuf:"varint,13,opt,name=retryable,proto3" json:"retryable,omitempty"`
	CreatedAt         *timestamppb.Timestamp  `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp  `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VerifiedAt        *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	RouteReadyAt      *timestamppb.Timestamp  `protobuf:"bytes,17,opt,name=route_ready_at,json=routeReadyAt,proto3" json:"route_ready_at,omitempty"`
	ActivatedAt       *timestamppb.Timestamp  `protobuf:"bytes,18,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	DeleteRequestedAt *timestamppb.Timestamp  `protobuf:"bytes,19,opt,name=delete_requested_at,json=deleteRequestedAt,proto3" json:"delete_requested_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DomainConfig) Reset() {
	*x = DomainConfig{}
	mi := &file_libops_v1_common_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainConfig) ProtoMessage() {}

func (x *DomainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_common_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainConfig.ProtoReflect.Descriptor instead.
func (*DomainConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{1}
}

func (x *DomainConfig) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *DomainConfig) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *DomainConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainConfig) GetKind() DomainKind {
	if x != nil {
		return x.Kind
	}
	return DomainKind_DOMAIN_KIND_UNSPECIFIED
}

func (x *DomainConfig) GetProvisioningState() DomainProvisioningState {
	if x != nil {
		return x.ProvisioningState
	}
	return DomainProvisioningState_DOMAIN_PROVISIONING_STATE_UNSPECIFIED
}

func (x *DomainConfig) GetRouteState() DomainRouteState {
	if x != nil {
		return x.RouteState
	}
	return DomainRouteState_DOMAIN_ROUTE_STATE_UNSPECIFIED
}

func (x *DomainConfig) GetDnsInstructions() []*DnsRecordInstruction {
	if x != nil {
		return x.DnsInstructions
	}
	return nil
}

func (x *DomainConfig) GetManagedHostname() string {
	if x != nil {
		return x.ManagedHostname
	}
	return ""
}

func (x *DomainConfig) GetSshHostname() string {
	if x != nil {
		return x.SshHostname
	}
	return ""
}

func (x *DomainConfig) GetRouteReady() bool {
	if x != nil {
		return x.RouteReady
	}
	return false
}

func (x *DomainConfig) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *DomainConfig) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *DomainConfig) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *DomainConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DomainConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DomainConfig) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *DomainConfig) GetRouteReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RouteReadyAt
	}
	return nil
}

func (x *DomainConfig) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *DomainConfig) GetDeleteRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteRequestedAt
	}
	return nil
}

// SiteConfig is the organization-facing site configuration
// Contains only safe, non-sensitive fields
type SiteConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SiteId         string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"` // Unique site identifier (UUID)
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteName       string                 `protobuf:"bytes,4,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"` // "production", "staging", "development"
	// GitHub repository configuration
	GithubRepository string `protobuf:"bytes,5,opt,name=github_repository,json=githubRepository,proto3" json:"github_repository,omitempty"` // GitHub repository URL
	GithubRef        string `protobuf:"bytes,6,opt,name=github_ref,json=githubRef,proto3" json:"github_ref,omitempty"`                      // GitHub reference: heads/{branch_name}, tags/{tag_name}, or "release"
	ComposePath      string `protobuf:"bytes,7,opt,name=compose_path,json=composePath,proto3" json:"compose_path,omitempty"`                // Path to docker-compose directory (default: "")
	ComposeFile      string `protobuf:"bytes,8,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"`                // Docker compose file name (default: "docker-compose.yml")
	// Application configuration
	Port            int32  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`                                              // Port the application listens on (default: 80)
	ApplicationType string `protobuf:"bytes,10,opt,name=application_type,json=applicationType,proto3" json:"application_type,omitempty"` // Type of application (default: "generic")
	// Docker compose commands
	UpCmd          []string `protobuf:"bytes,12,rep,name=up_cmd,json=upCmd,proto3" json:"up_cmd,omitempty"`                            // Commands to start containers
	InitCmd        []string `protobuf:"bytes,13,rep,name=init_cmd,json=initCmd,proto3" json:"init_cmd,omitempty"`                      // Commands to run on initial setup
	RolloutCmd     []string `protobuf:"bytes,14,rep,name=rollout_cmd,json=rolloutCmd,proto3" json:"rollout_cmd,omitempty"`             // Commands to run during rollout
	OverlayVolumes []string `protobuf:"bytes,15,rep,name=overlay_volumes,json=overlayVolumes,proto3" json:"overlay_volumes,omitempty"` // Overlay volume paths
	// GCP deployment configuration
	Os           string `protobuf:"bytes,16,opt,name=os,proto3" json:"os,omitempty"`                                          // OS image (default: "cos-125-19216-104-74")
	IsProduction bool   `protobuf:"varint,17,opt,name=is_production,json=isProduction,proto3" json:"is_production,omitempty"` // Whether this is the production instance
	// Runtime/VM placement. On create, set one of project_runtime_id,
	// project_runtime_name, or project_runtime_role to choose a runtime. If unset,
	// production sites use the production runtime and other sites use ephemeral.
	ProjectRuntimeId   string             `protobuf:"bytes,18,opt,name=project_runtime_id,json=projectRuntimeId,proto3" json:"project_runtime_id,omitempty"`
	ProjectRuntimeName string             `protobuf:"bytes,19,opt,name=project_runtime_name,json=projectRuntimeName,proto3" json:"project_runtime_name,omitempty"`
	ProjectRuntimeRole ProjectRuntimeRole `protobuf:"varint,20,opt,name=project_runtime_role,json=projectRuntimeRole,proto3,enum=libops.v1.common.ProjectRuntimeRole" json:"project_runtime_role,omitempty"`
	// Status (organization-visible)
	Status        Status `protobuf:"varint,11,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteConfig) Reset() {
	*x = SiteConfig{}
	mi := &file_libops_v1_common_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteConfig) ProtoMessage() {}

func (x *SiteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_common_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteConfig.ProtoReflect.Descriptor instead.
func (*SiteConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{2}
}

func (x *SiteConfig) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SiteConfig) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SiteConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SiteConfig) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *SiteConfig) GetGithubRepository() string {
	if x != nil {
		return x.GithubRepository
	}
	return ""
}

func (x *SiteConfig) GetGithubRef() string {
	if x != nil {
		return x.GithubRef
	}
	return ""
}

func (x *SiteConfig) GetComposePath() string {
	if x != nil {
		return x.ComposePath
	}
	return ""
}

func (x *SiteConfig) GetComposeFile() string {
	if x != nil {
		return x.ComposeFile
	}
	return ""
}

func (x *SiteConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SiteConfig) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *SiteConfig) GetUpCmd() []string {
	if x != nil {
		return x.UpCmd
	}
	return nil
}

func (x *SiteConfig) GetInitCmd() []string {
	if x != nil {
		return x.InitCmd
	}
	return nil
}

func (x *SiteConfig) GetRolloutCmd() []string {
	if x != nil {
		return x.RolloutCmd
	}
	return nil
}

func (x *SiteConfig) GetOverlayVolumes() []string {
	if x != nil {
		return x.OverlayVolumes
	}
	return nil
}

func (x *SiteConfig) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SiteConfig) GetIsProduction() bool {
	if x != nil {
		return x.IsProduction
	}
	return false
}

func (x *SiteConfig) GetProjectRuntimeId() string {
	if x != nil {
		return x.ProjectRuntimeId
	}
	return ""
}

func (x *SiteConfig) GetProjectRuntimeName() string {
	if x != nil {
		return x.ProjectRuntimeName
	}
	return ""
}

func (x *SiteConfig) GetProjectRuntimeRole() ProjectRuntimeRole {
	if x != nil {
		return x.ProjectRuntimeRole
	}
	return ProjectRuntimeRole_PROJECT_RUNTIME_ROLE_UNSPECIFIED
}

func (x *SiteConfig) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_libops_v1_common_site_proto protoreflect.FileDescriptor

const file_libops_v1_common_site_proto_rawDesc = "" +
	"\n" +
	"\x1blibops/v1/common/site.proto\x12\x10libops.v1.common\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1elibops/v1/common/project.proto\x1a\x1clibops/v1/common/types.proto\"\xba\x01\n" +
	"\x14DnsRecordInstruction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12<\n" +
	"\apurpose\x18\x05 \x01(\x0e2\".libops.v1.common.DnsRecordPurposeR\apurpose\x12\x16\n" +
	"\x06retain\x18\x06 \x01(\bR\x06retain\"\xf9\a\n" +
	"\fDomainConfig\x12'\n" +
	"\tdomain_id\x18\x01 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\bdomainId\x12#\n" +
	"\asite_id\x18\x02 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x06siteId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x120\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1c.libops.v1.common.DomainKindR\x04kind\x12X\n" +
	"\x12provisioning_state\x18\x05 \x01(\x0e2).libops.v1.common.DomainProvisioningStateR\x11provisioningState\x12C\n" +
	"\vroute_state\x18\x06 \x01(\x0e2\".libops.v1.common.DomainRouteStateR\n" +
	"routeState\x12Q\n" +
	"\x10dns_instructions\x18\a \x03(\v2&.libops.v1.common.DnsRecordInstructionR\x0fdnsInstructions\x12)\n" +
	"\x10managed_hostname\x18\b \x01(\tR\x0fmanagedHostname\x12!\n" +
	"\fssh_hostname\x18\t \x01(\tR\vsshHostname\x12\x1f\n" +
	"\vroute_ready\x18\n" +
	" \x01(\bR\n" +
	"routeReady\x12%\n" +
	"\x0efailure_reason\x18\v \x01(\tR\rfailureReason\x12'\n" +
	"\x0ffailure_message\x18\f \x01(\tR\x0efailureMessage\x12\x1c\n" +
	"\tretryable\x18\r \x01(\bR\tretryable\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vverified_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12@\n" +
	"\x0eroute_ready_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\frouteReadyAt\x12=\n" +
	"\factivated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\vactivatedAt\x12J\n" +
	"\x13delete_requested_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\x11deleteRequestedAt\"\xa6\x06\n" +
	"\n" +
	"SiteConfig\x12#\n" +
	"\asite_id\x18\x01 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x06siteId\x123\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x0eorganizationId\x12)\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\tprojectId\x12\x1b\n" +
	"\tsite_name\x18\x04 \x01(\tR\bsiteName\x12+\n" +
	"\x11github_repository\x18\x05 \x01(\tR\x10githubRepository\x12\x1d\n" +
	"\n" +
	"github_ref\x18\x06 \x01(\tR\tgithubRef\x12!\n" +
	"\fcompose_path\x18\a \x01(\tR\vcomposePath\x12!\n" +
	"\fcompose_file\x18\b \x01(\tR\vcomposeFile\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12)\n" +
	"\x10application_type\x18\n" +
	" \x01(\tR\x0fapplicationType\x12\x15\n" +
	"\x06up_cmd\x18\f \x03(\tR\x05upCmd\x12\x19\n" +
	"\binit_cmd\x18\r \x03(\tR\ainitCmd\x12\x1f\n" +
	"\vrollout_cmd\x18\x0e \x03(\tR\n" +
	"rolloutCmd\x12'\n" +
	"\x0foverlay_volumes\x18\x0f \x03(\tR\x0eoverlayVolumes\x12\x0e\n" +
	"\x02os\x18\x10 \x01(\tR\x02os\x12#\n" +
	"\ris_production\x18\x11 \x01(\bR\fisProduction\x128\n" +
	"\x12project_runtime_id\x18\x12 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x10projectRuntimeId\x120\n" +
	"\x14project_runtime_name\x18\x13 \x01(\tR\x12projectRuntimeName\x12V\n" +
	"\x14project_runtime_role\x18\x14 \x01(\x0e2$.libops.v1.common.ProjectRuntimeRoleR\x12projectRuntimeRole\x120\n" +
	"\x06status\x18\v \x01(\x0e2\x18.libops.v1.common.StatusR\x06status*Z\n" +
	"\n" +
	"DomainKind\x12\x1b\n" +
	"\x17DOMAIN_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DOMAIN_KIND_MANAGED\x10\x01\x12\x16\n" +
	"\x12DOMAIN_KIND_VANITY\x10\x02*\xf8\x04\n" +
	"\x17DomainProvisioningState\x12)\n" +
	"%DOMAIN_PROVISIONING_STATE_UNSPECIFIED\x10\x00\x126\n" +
	"2DOMAIN_PROVISIONING_STATE_AWAITING_OWNERSHIP_PROOF\x10\x01\x129\n" +
	"5DOMAIN_PROVISIONING_STATE_PREPARING_DNS_AUTHORIZATION\x10\x02\x126\n" +
	"2DOMAIN_PROVISIONING_STATE_AWAITING_CERTIFICATE_DNS\x10\x03\x126\n" +
	"2DOMAIN_PROVISIONING_STATE_PROVISIONING_CERTIFICATE\x10\x04\x124\n" +
	"0DOMAIN_PROVISIONING_STATE_PROVISIONING_MAP_ENTRY\x10\x05\x12/\n" +
	"+DOMAIN_PROVISIONING_STATE_READY_FOR_TRAFFIC\x10\x06\x12$\n" +
	" DOMAIN_PROVISIONING_STATE_ACTIVE\x10\a\x12&\n" +
	"\"DOMAIN_PROVISIONING_STATE_DEGRADED\x10\b\x12$\n" +
	" DOMAIN_PROVISIONING_STATE_FAILED\x10\t\x12&\n" +
	"\"DOMAIN_PROVISIONING_STATE_DELETING\x10\n" +
	"\x12%\n" +
	"!DOMAIN_PROVISIONING_STATE_DELETED\x10\v\x12%\n" +
	"!DOMAIN_PROVISIONING_STATE_EXPIRED\x10\f*\xd7\x01\n" +
	"\x10DomainRouteState\x12\"\n" +
	"\x1eDOMAIN_ROUTE_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDOMAIN_ROUTE_STATE_PENDING\x10\x01\x12\x1e\n" +
	"\x1aDOMAIN_ROUTE_STATE_ENABLED\x10\x02\x12\x1e\n" +
	"\x1aDOMAIN_ROUTE_STATE_BLOCKED\x10\x03\x12\x1f\n" +
	"\x1bDOMAIN_ROUTE_STATE_DELETING\x10\x04\x12\x1e\n" +
	"\x1aDOMAIN_ROUTE_STATE_DELETED\x10\x05*\xcc\x01\n" +
	"\x10DnsRecordPurpose\x12\"\n" +
	"\x1eDNS_RECORD_PURPOSE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DNS_RECORD_PURPOSE_OWNERSHIP_PROOF\x10\x01\x120\n" +
	",DNS_RECORD_PURPOSE_CERTIFICATE_AUTHORIZATION\x10\x02\x12\x1e\n" +
	"\x1aDNS_RECORD_PURPOSE_TRAFFIC\x10\x03\x12\x1a\n" +
	"\x16DNS_RECORD_PURPOSE_SSH\x10\x04B\xad\x01\n" +
	"\x14com.libops.v1.commonB\tSiteProtoP\x01Z(github.com/libops/proto/libops/v1/common\xa2\x02\x03LVC\xaa\x02\x10Libops.V1.Common\xca\x02\x10Libops\\V1\\Common\xe2\x02\x1cLibops\\V1\\Common\\GPBMetadata\xea\x02\x12Libops::V1::Commonb\x06proto3"

var (
	file_libops_v1_common_site_proto_rawDescOnce sync.Once
	file_libops_v1_common_site_proto_rawDescData []byte
)

func file_libops_v1_common_site_proto_rawDescGZIP() []byte {
	file_libops_v1_common_site_proto_rawDescOnce.Do(func() {
		file_libops_v1_common_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_common_site_proto_rawDesc), len(file_libops_v1_common_site_proto_rawDesc)))
	})
	return file_libops_v1_common_site_proto_rawDescData
}

var file_libops_v1_common_site_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_libops_v1_common_site_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libops_v1_common_site_proto_goTypes = []any{
	(DomainKind)(0),               // 0: libops.v1.common.DomainKind
	(DomainProvisioningState)(0),  // 1: libops.v1.common.DomainProvisioningState
	(DomainRouteState)(0),         // 2: libops.v1.common.DomainRouteState
	(DnsRecordPurpose)(0),         // 3: libops.v1.common.DnsRecordPurpose
	(*DnsRecordInstruction)(nil),  // 4: libops.v1.common.DnsRecordInstruction
	(*DomainConfig)(nil),          // 5: libops.v1.common.DomainConfig
	(*SiteConfig)(nil),            // 6: libops.v1.common.SiteConfig
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(ProjectRuntimeRole)(0),       // 8: libops.v1.common.ProjectRuntimeRole
	(Status)(0),                   // 9: libops.v1.common.Status
}
var file_libops_v1_common_site_proto_depIdxs = []int32{
	3,  // 0: libops.v1.common.DnsRecordInstruction.purpose:type_name -> libops.v1.common.DnsRecordPurpose
	0,  // 1: libops.v1.common.DomainConfig.kind:type_name -> libops.v1.common.DomainKind
	1,  // 2: libops.v1.common.DomainConfig.provisioning_state:type_name -> libops.v1.common.DomainProvisioningState
	2,  // 3: libops.v1.common.DomainConfig.route_state:type_name -> libops.v1.common.DomainRouteState
	4,  // 4: libops.v1.common.DomainConfig.dns_instructions:type_name -> libops.v1.common.DnsRecordInstruction
	7,  // 5: libops.v1.common.DomainConfig.created_at:type_name -> google.protobuf.Timestamp
	7,  // 6: libops.v1.common.DomainConfig.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 7: libops.v1.common.DomainConfig.verified_at:type_name -> google.protobuf.Timestamp
	7,  // 8: libops.v1.common.DomainConfig.route_ready_at:type_name -> google.protobuf.Timestamp
	7,  // 9: libops.v1.common.DomainConfig.activated_at:type_name -> google.protobuf.Timestamp
	7,  // 10: libops.v1.common.DomainConfig.delete_requested_at:type_name -> google.protobuf.Timestamp
	8,  // 11: libops.v1.common.SiteConfig.project_runtime_role:type_name -> libops.v1.common.ProjectRuntimeRole
	9,  // 12: libops.v1.common.SiteConfig.status:type_name -> libops.v1.common.Status
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_libops_v1_common_site_proto_init() }
func file_libops_v1_common_site_proto_init() {
	if File_libops_v1_common_site_proto != nil {
		return
	}
	file_libops_v1_common_project_proto_init()
	file_libops_v1_common_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_common_site_proto_rawDesc), len(file_libops_v1_common_site_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_common_site_proto_goTypes,
		DependencyIndexes: file_libops_v1_common_site_proto_depIdxs,
		EnumInfos:         file_libops_v1_common_site_proto_enumTypes,
		MessageInfos:      file_libops_v1_common_site_proto_msgTypes,
	}.Build()
	File_libops_v1_common_site_proto = out.File
	file_libops_v1_common_site_proto_goTypes = nil
	file_libops_v1_common_site_proto_depIdxs = nil
}
