// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/common/site.proto

package common

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainEdgeAction int32

const (
	DomainEdgeAction_DOMAIN_EDGE_ACTION_UNSPECIFIED DomainEdgeAction = 0
	DomainEdgeAction_DOMAIN_EDGE_ACTION_ALLOW       DomainEdgeAction = 1
	DomainEdgeAction_DOMAIN_EDGE_ACTION_CHALLENGE   DomainEdgeAction = 2
	DomainEdgeAction_DOMAIN_EDGE_ACTION_BLOCK       DomainEdgeAction = 3
)

// Enum value maps for DomainEdgeAction.
var (
	DomainEdgeAction_name = map[int32]string{
		0: "DOMAIN_EDGE_ACTION_UNSPECIFIED",
		1: "DOMAIN_EDGE_ACTION_ALLOW",
		2: "DOMAIN_EDGE_ACTION_CHALLENGE",
		3: "DOMAIN_EDGE_ACTION_BLOCK",
	}
	DomainEdgeAction_value = map[string]int32{
		"DOMAIN_EDGE_ACTION_UNSPECIFIED": 0,
		"DOMAIN_EDGE_ACTION_ALLOW":       1,
		"DOMAIN_EDGE_ACTION_CHALLENGE":   2,
		"DOMAIN_EDGE_ACTION_BLOCK":       3,
	}
)

func (x DomainEdgeAction) Enum() *DomainEdgeAction {
	p := new(DomainEdgeAction)
	*p = x
	return p
}

func (x DomainEdgeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainEdgeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_site_proto_enumTypes[0].Descriptor()
}

func (DomainEdgeAction) Type() protoreflect.EnumType {
	return &file_libops_v1_common_site_proto_enumTypes[0]
}

func (x DomainEdgeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainEdgeAction.Descriptor instead.
func (DomainEdgeAction) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{0}
}

type DomainConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	SiteId               string                 `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	CloudRunHostname     string                 `protobuf:"bytes,3,opt,name=cloud_run_hostname,json=cloudRunHostname,proto3" json:"cloud_run_hostname,omitempty"`
	Tier                 string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Status               Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	EdgeAction           DomainEdgeAction       `protobuf:"varint,6,opt,name=edge_action,json=edgeAction,proto3,enum=libops.v1.common.DomainEdgeAction" json:"edge_action,omitempty"`
	SuccessLogSampleRate float64                `protobuf:"fixed64,7,opt,name=success_log_sample_rate,json=successLogSampleRate,proto3" json:"success_log_sample_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DomainConfig) Reset() {
	*x = DomainConfig{}
	mi := &file_libops_v1_common_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainConfig) ProtoMessage() {}

func (x *DomainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_common_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainConfig.ProtoReflect.Descriptor instead.
func (*DomainConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{0}
}

func (x *DomainConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainConfig) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *DomainConfig) GetCloudRunHostname() string {
	if x != nil {
		return x.CloudRunHostname
	}
	return ""
}

func (x *DomainConfig) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *DomainConfig) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *DomainConfig) GetEdgeAction() DomainEdgeAction {
	if x != nil {
		return x.EdgeAction
	}
	return DomainEdgeAction_DOMAIN_EDGE_ACTION_UNSPECIFIED
}

func (x *DomainConfig) GetSuccessLogSampleRate() float64 {
	if x != nil {
		return x.SuccessLogSampleRate
	}
	return 0
}

// SiteConfig is the organization-facing site configuration
// Contains only safe, non-sensitive fields
type SiteConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SiteId         string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"` // Unique site identifier (UUID)
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SiteName       string                 `protobuf:"bytes,4,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"` // "production", "staging", "development"
	// GitHub repository configuration
	GithubRepository string `protobuf:"bytes,5,opt,name=github_repository,json=githubRepository,proto3" json:"github_repository,omitempty"` // GitHub repository URL
	GithubRef        string `protobuf:"bytes,6,opt,name=github_ref,json=githubRef,proto3" json:"github_ref,omitempty"`                      // GitHub reference: heads/{branch_name}, tags/{tag_name}, or "release"
	ComposePath      string `protobuf:"bytes,7,opt,name=compose_path,json=composePath,proto3" json:"compose_path,omitempty"`                // Path to docker-compose directory (default: "")
	ComposeFile      string `protobuf:"bytes,8,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"`                // Docker compose file name (default: "docker-compose.yml")
	// Application configuration
	Port            int32  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`                                              // Port the application listens on (default: 80)
	ApplicationType string `protobuf:"bytes,10,opt,name=application_type,json=applicationType,proto3" json:"application_type,omitempty"` // Type of application (default: "generic")
	// Docker compose commands
	UpCmd          []string `protobuf:"bytes,12,rep,name=up_cmd,json=upCmd,proto3" json:"up_cmd,omitempty"`                            // Commands to start containers
	InitCmd        []string `protobuf:"bytes,13,rep,name=init_cmd,json=initCmd,proto3" json:"init_cmd,omitempty"`                      // Commands to run on initial setup
	RolloutCmd     []string `protobuf:"bytes,14,rep,name=rollout_cmd,json=rolloutCmd,proto3" json:"rollout_cmd,omitempty"`             // Commands to run during rollout
	OverlayVolumes []string `protobuf:"bytes,15,rep,name=overlay_volumes,json=overlayVolumes,proto3" json:"overlay_volumes,omitempty"` // Overlay volume paths
	// GCP deployment configuration
	Os           string `protobuf:"bytes,16,opt,name=os,proto3" json:"os,omitempty"`                                          // OS image (default: "cos-125-19216-104-74")
	IsProduction bool   `protobuf:"varint,17,opt,name=is_production,json=isProduction,proto3" json:"is_production,omitempty"` // Whether this is the production instance
	// Status (organization-visible)
	Status        Status `protobuf:"varint,11,opt,name=status,proto3,enum=libops.v1.common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteConfig) Reset() {
	*x = SiteConfig{}
	mi := &file_libops_v1_common_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteConfig) ProtoMessage() {}

func (x *SiteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_common_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteConfig.ProtoReflect.Descriptor instead.
func (*SiteConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_common_site_proto_rawDescGZIP(), []int{1}
}

func (x *SiteConfig) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SiteConfig) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SiteConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SiteConfig) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *SiteConfig) GetGithubRepository() string {
	if x != nil {
		return x.GithubRepository
	}
	return ""
}

func (x *SiteConfig) GetGithubRef() string {
	if x != nil {
		return x.GithubRef
	}
	return ""
}

func (x *SiteConfig) GetComposePath() string {
	if x != nil {
		return x.ComposePath
	}
	return ""
}

func (x *SiteConfig) GetComposeFile() string {
	if x != nil {
		return x.ComposeFile
	}
	return ""
}

func (x *SiteConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SiteConfig) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *SiteConfig) GetUpCmd() []string {
	if x != nil {
		return x.UpCmd
	}
	return nil
}

func (x *SiteConfig) GetInitCmd() []string {
	if x != nil {
		return x.InitCmd
	}
	return nil
}

func (x *SiteConfig) GetRolloutCmd() []string {
	if x != nil {
		return x.RolloutCmd
	}
	return nil
}

func (x *SiteConfig) GetOverlayVolumes() []string {
	if x != nil {
		return x.OverlayVolumes
	}
	return nil
}

func (x *SiteConfig) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SiteConfig) GetIsProduction() bool {
	if x != nil {
		return x.IsProduction
	}
	return false
}

func (x *SiteConfig) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_libops_v1_common_site_proto protoreflect.FileDescriptor

const file_libops_v1_common_site_proto_rawDesc = "" +
	"\n" +
	"\x1blibops/v1/common/site.proto\x12\x10libops.v1.common\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1clibops/v1/common/types.proto\"\xbb\x02\n" +
	"\fDomainConfig\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12#\n" +
	"\asite_id\x18\x02 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x06siteId\x12,\n" +
	"\x12cloud_run_hostname\x18\x03 \x01(\tR\x10cloudRunHostname\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.libops.v1.common.StatusR\x06status\x12C\n" +
	"\vedge_action\x18\x06 \x01(\x0e2\".libops.v1.common.DomainEdgeActionR\n" +
	"edgeAction\x125\n" +
	"\x17success_log_sample_rate\x18\a \x01(\x01R\x14successLogSampleRate\"\xe2\x04\n" +
	"\n" +
	"SiteConfig\x12#\n" +
	"\asite_id\x18\x01 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x06siteId\x123\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\x0eorganizationId\x12)\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\n" +
	"\xbaG\a\x9a\x02\x04uuidR\tprojectId\x12\x1b\n" +
	"\tsite_name\x18\x04 \x01(\tR\bsiteName\x12+\n" +
	"\x11github_repository\x18\x05 \x01(\tR\x10githubRepository\x12\x1d\n" +
	"\n" +
	"github_ref\x18\x06 \x01(\tR\tgithubRef\x12!\n" +
	"\fcompose_path\x18\a \x01(\tR\vcomposePath\x12!\n" +
	"\fcompose_file\x18\b \x01(\tR\vcomposeFile\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12)\n" +
	"\x10application_type\x18\n" +
	" \x01(\tR\x0fapplicationType\x12\x15\n" +
	"\x06up_cmd\x18\f \x03(\tR\x05upCmd\x12\x19\n" +
	"\binit_cmd\x18\r \x03(\tR\ainitCmd\x12\x1f\n" +
	"\vrollout_cmd\x18\x0e \x03(\tR\n" +
	"rolloutCmd\x12'\n" +
	"\x0foverlay_volumes\x18\x0f \x03(\tR\x0eoverlayVolumes\x12\x0e\n" +
	"\x02os\x18\x10 \x01(\tR\x02os\x12#\n" +
	"\ris_production\x18\x11 \x01(\bR\fisProduction\x120\n" +
	"\x06status\x18\v \x01(\x0e2\x18.libops.v1.common.StatusR\x06status*\x94\x01\n" +
	"\x10DomainEdgeAction\x12\"\n" +
	"\x1eDOMAIN_EDGE_ACTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DOMAIN_EDGE_ACTION_ALLOW\x10\x01\x12 \n" +
	"\x1cDOMAIN_EDGE_ACTION_CHALLENGE\x10\x02\x12\x1c\n" +
	"\x18DOMAIN_EDGE_ACTION_BLOCK\x10\x03B\xad\x01\n" +
	"\x14com.libops.v1.commonB\tSiteProtoP\x01Z(github.com/libops/proto/libops/v1/common\xa2\x02\x03LVC\xaa\x02\x10Libops.V1.Common\xca\x02\x10Libops\\V1\\Common\xe2\x02\x1cLibops\\V1\\Common\\GPBMetadata\xea\x02\x12Libops::V1::Commonb\x06proto3"

var (
	file_libops_v1_common_site_proto_rawDescOnce sync.Once
	file_libops_v1_common_site_proto_rawDescData []byte
)

func file_libops_v1_common_site_proto_rawDescGZIP() []byte {
	file_libops_v1_common_site_proto_rawDescOnce.Do(func() {
		file_libops_v1_common_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_common_site_proto_rawDesc), len(file_libops_v1_common_site_proto_rawDesc)))
	})
	return file_libops_v1_common_site_proto_rawDescData
}

var file_libops_v1_common_site_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libops_v1_common_site_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libops_v1_common_site_proto_goTypes = []any{
	(DomainEdgeAction)(0), // 0: libops.v1.common.DomainEdgeAction
	(*DomainConfig)(nil),  // 1: libops.v1.common.DomainConfig
	(*SiteConfig)(nil),    // 2: libops.v1.common.SiteConfig
	(Status)(0),           // 3: libops.v1.common.Status
}
var file_libops_v1_common_site_proto_depIdxs = []int32{
	3, // 0: libops.v1.common.DomainConfig.status:type_name -> libops.v1.common.Status
	0, // 1: libops.v1.common.DomainConfig.edge_action:type_name -> libops.v1.common.DomainEdgeAction
	3, // 2: libops.v1.common.SiteConfig.status:type_name -> libops.v1.common.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_libops_v1_common_site_proto_init() }
func file_libops_v1_common_site_proto_init() {
	if File_libops_v1_common_site_proto != nil {
		return
	}
	file_libops_v1_common_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_common_site_proto_rawDesc), len(file_libops_v1_common_site_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_common_site_proto_goTypes,
		DependencyIndexes: file_libops_v1_common_site_proto_depIdxs,
		EnumInfos:         file_libops_v1_common_site_proto_enumTypes,
		MessageInfos:      file_libops_v1_common_site_proto_msgTypes,
	}.Build()
	File_libops_v1_common_site_proto = out.File
	file_libops_v1_common_site_proto_goTypes = nil
	file_libops_v1_common_site_proto_depIdxs = nil
}
