// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/common/types.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the lifecycle state of libops entities
// Used across organization, project, site, member, and firewall resources
type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_ACTIVE       Status = 1 // Resource is active and operational
	Status_STATUS_PROVISIONING Status = 2 // Resource is being created/provisioned
	Status_STATUS_FAILED       Status = 3 // Resource provisioning/operation failed
	Status_STATUS_SUSPENDED    Status = 4 // Resource is suspended (can be reactivated)
	Status_STATUS_DELETED      Status = 5 // Resource is marked for deletion or deleted
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_PROVISIONING",
		3: "STATUS_FAILED",
		4: "STATUS_SUSPENDED",
		5: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_ACTIVE":       1,
		"STATUS_PROVISIONING": 2,
		"STATUS_FAILED":       3,
		"STATUS_SUSPENDED":    4,
		"STATUS_DELETED":      5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_types_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_libops_v1_common_types_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_types_proto_rawDescGZIP(), []int{0}
}

// AuthMethod represents how a user authenticates to libops
type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED AuthMethod = 0
	AuthMethod_AUTH_METHOD_GOOGLE      AuthMethod = 1 // Google OAuth
	AuthMethod_AUTH_METHOD_USERPASS    AuthMethod = 2 // Email/password
	AuthMethod_AUTH_METHOD_GCLOUD      AuthMethod = 3 // Google Cloud service account
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_GOOGLE",
		2: "AUTH_METHOD_USERPASS",
		3: "AUTH_METHOD_GCLOUD",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED": 0,
		"AUTH_METHOD_GOOGLE":      1,
		"AUTH_METHOD_USERPASS":    2,
		"AUTH_METHOD_GCLOUD":      3,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_common_types_proto_enumTypes[1].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_libops_v1_common_types_proto_enumTypes[1]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_common_types_proto_rawDescGZIP(), []int{1}
}

var File_libops_v1_common_types_proto protoreflect.FileDescriptor

const file_libops_v1_common_types_proto_rawDesc = "" +
	"\n" +
	"\x1clibops/v1/common/types.proto\x12\x10libops.v1.common*\x89\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13STATUS_PROVISIONING\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10\x05*s\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AUTH_METHOD_GOOGLE\x10\x01\x12\x18\n" +
	"\x14AUTH_METHOD_USERPASS\x10\x02\x12\x16\n" +
	"\x12AUTH_METHOD_GCLOUD\x10\x03B\xae\x01\n" +
	"\x14com.libops.v1.commonB\n" +
	"TypesProtoP\x01Z(github.com/libops/proto/libops/v1/common\xa2\x02\x03LVC\xaa\x02\x10Libops.V1.Common\xca\x02\x10Libops\\V1\\Common\xe2\x02\x1cLibops\\V1\\Common\\GPBMetadata\xea\x02\x12Libops::V1::Commonb\x06proto3"

var (
	file_libops_v1_common_types_proto_rawDescOnce sync.Once
	file_libops_v1_common_types_proto_rawDescData []byte
)

func file_libops_v1_common_types_proto_rawDescGZIP() []byte {
	file_libops_v1_common_types_proto_rawDescOnce.Do(func() {
		file_libops_v1_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_common_types_proto_rawDesc), len(file_libops_v1_common_types_proto_rawDesc)))
	})
	return file_libops_v1_common_types_proto_rawDescData
}

var file_libops_v1_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_libops_v1_common_types_proto_goTypes = []any{
	(Status)(0),     // 0: libops.v1.common.Status
	(AuthMethod)(0), // 1: libops.v1.common.AuthMethod
}
var file_libops_v1_common_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libops_v1_common_types_proto_init() }
func file_libops_v1_common_types_proto_init() {
	if File_libops_v1_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_common_types_proto_rawDesc), len(file_libops_v1_common_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_common_types_proto_goTypes,
		DependencyIndexes: file_libops_v1_common_types_proto_depIdxs,
		EnumInfos:         file_libops_v1_common_types_proto_enumTypes,
	}.Build()
	File_libops_v1_common_types_proto = out.File
	file_libops_v1_common_types_proto_goTypes = nil
	file_libops_v1_common_types_proto_depIdxs = nil
}
