// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/options/visibility.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiVisibility controls which API surface may be published to customers.
// Services must declare a visibility explicitly. Methods inherit their service
// visibility unless they declare a narrower override.
type ApiVisibility int32

const (
	ApiVisibility_API_VISIBILITY_UNSPECIFIED ApiVisibility = 0
	ApiVisibility_API_VISIBILITY_PUBLIC      ApiVisibility = 1
	ApiVisibility_API_VISIBILITY_INTERNAL    ApiVisibility = 2
)

// Enum value maps for ApiVisibility.
var (
	ApiVisibility_name = map[int32]string{
		0: "API_VISIBILITY_UNSPECIFIED",
		1: "API_VISIBILITY_PUBLIC",
		2: "API_VISIBILITY_INTERNAL",
	}
	ApiVisibility_value = map[string]int32{
		"API_VISIBILITY_UNSPECIFIED": 0,
		"API_VISIBILITY_PUBLIC":      1,
		"API_VISIBILITY_INTERNAL":    2,
	}
)

func (x ApiVisibility) Enum() *ApiVisibility {
	p := new(ApiVisibility)
	*p = x
	return p
}

func (x ApiVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_libops_v1_options_visibility_proto_enumTypes[0].Descriptor()
}

func (ApiVisibility) Type() protoreflect.EnumType {
	return &file_libops_v1_options_visibility_proto_enumTypes[0]
}

func (x ApiVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiVisibility.Descriptor instead.
func (ApiVisibility) EnumDescriptor() ([]byte, []int) {
	return file_libops_v1_options_visibility_proto_rawDescGZIP(), []int{0}
}

var file_libops_v1_options_visibility_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ApiVisibility)(nil),
		Field:         50004,
		Name:          "libops.v1.options.service_api_visibility",
		Tag:           "varint,50004,opt,name=service_api_visibility,enum=libops.v1.options.ApiVisibility",
		Filename:      "libops/v1/options/visibility.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ApiVisibility)(nil),
		Field:         50005,
		Name:          "libops.v1.options.method_api_visibility",
		Tag:           "varint,50005,opt,name=method_api_visibility,enum=libops.v1.options.ApiVisibility",
		Filename:      "libops/v1/options/visibility.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional libops.v1.options.ApiVisibility service_api_visibility = 50004;
	E_ServiceApiVisibility = &file_libops_v1_options_visibility_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional libops.v1.options.ApiVisibility method_api_visibility = 50005;
	E_MethodApiVisibility = &file_libops_v1_options_visibility_proto_extTypes[1]
)

var File_libops_v1_options_visibility_proto protoreflect.FileDescriptor

const file_libops_v1_options_visibility_proto_rawDesc = "" +
	"\n" +
	"\"libops/v1/options/visibility.proto\x12\x11libops.v1.options\x1a google/protobuf/descriptor.proto*g\n" +
	"\rApiVisibility\x12\x1e\n" +
	"\x1aAPI_VISIBILITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15API_VISIBILITY_PUBLIC\x10\x01\x12\x1b\n" +
	"\x17API_VISIBILITY_INTERNAL\x10\x02:y\n" +
	"\x16service_api_visibility\x12\x1f.google.protobuf.ServiceOptions\x18Ԇ\x03 \x01(\x0e2 .libops.v1.options.ApiVisibilityR\x14serviceApiVisibility:v\n" +
	"\x15method_api_visibility\x12\x1e.google.protobuf.MethodOptions\x18Ն\x03 \x01(\x0e2 .libops.v1.options.ApiVisibilityR\x13methodApiVisibilityB\xb9\x01\n" +
	"\x15com.libops.v1.optionsB\x0fVisibilityProtoP\x01Z)github.com/libops/proto/libops/v1/options\xa2\x02\x03LVO\xaa\x02\x11Libops.V1.Options\xca\x02\x11Libops\\V1\\Options\xe2\x02\x1dLibops\\V1\\Options\\GPBMetadata\xea\x02\x13Libops::V1::Optionsb\x06proto3"

var (
	file_libops_v1_options_visibility_proto_rawDescOnce sync.Once
	file_libops_v1_options_visibility_proto_rawDescData []byte
)

func file_libops_v1_options_visibility_proto_rawDescGZIP() []byte {
	file_libops_v1_options_visibility_proto_rawDescOnce.Do(func() {
		file_libops_v1_options_visibility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_options_visibility_proto_rawDesc), len(file_libops_v1_options_visibility_proto_rawDesc)))
	})
	return file_libops_v1_options_visibility_proto_rawDescData
}

var file_libops_v1_options_visibility_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libops_v1_options_visibility_proto_goTypes = []any{
	(ApiVisibility)(0),                  // 0: libops.v1.options.ApiVisibility
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
}
var file_libops_v1_options_visibility_proto_depIdxs = []int32{
	1, // 0: libops.v1.options.service_api_visibility:extendee -> google.protobuf.ServiceOptions
	2, // 1: libops.v1.options.method_api_visibility:extendee -> google.protobuf.MethodOptions
	0, // 2: libops.v1.options.service_api_visibility:type_name -> libops.v1.options.ApiVisibility
	0, // 3: libops.v1.options.method_api_visibility:type_name -> libops.v1.options.ApiVisibility
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libops_v1_options_visibility_proto_init() }
func file_libops_v1_options_visibility_proto_init() {
	if File_libops_v1_options_visibility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_options_visibility_proto_rawDesc), len(file_libops_v1_options_visibility_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_options_visibility_proto_goTypes,
		DependencyIndexes: file_libops_v1_options_visibility_proto_depIdxs,
		EnumInfos:         file_libops_v1_options_visibility_proto_enumTypes,
		ExtensionInfos:    file_libops_v1_options_visibility_proto_extTypes,
	}.Build()
	File_libops_v1_options_visibility_proto = out.File
	file_libops_v1_options_visibility_proto_goTypes = nil
	file_libops_v1_options_visibility_proto_depIdxs = nil
}
