// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: libops/v1/admin_api.proto

package libopsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/libops/proto/libops/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminOrganizationServiceName is the fully-qualified name of the AdminOrganizationService service.
	AdminOrganizationServiceName = "libops.v1.AdminOrganizationService"
	// AdminSiteServiceName is the fully-qualified name of the AdminSiteService service.
	AdminSiteServiceName = "libops.v1.AdminSiteService"
	// AdminProjectServiceName is the fully-qualified name of the AdminProjectService service.
	AdminProjectServiceName = "libops.v1.AdminProjectService"
	// AdminReconciliationServiceName is the fully-qualified name of the AdminReconciliationService
	// service.
	AdminReconciliationServiceName = "libops.v1.AdminReconciliationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminOrganizationServiceGetOrganizationProcedure is the fully-qualified name of the
	// AdminOrganizationService's GetOrganization RPC.
	AdminOrganizationServiceGetOrganizationProcedure = "/libops.v1.AdminOrganizationService/GetOrganization"
	// AdminOrganizationServiceCreateOrganizationProcedure is the fully-qualified name of the
	// AdminOrganizationService's CreateOrganization RPC.
	AdminOrganizationServiceCreateOrganizationProcedure = "/libops.v1.AdminOrganizationService/CreateOrganization"
	// AdminOrganizationServiceUpdateOrganizationProcedure is the fully-qualified name of the
	// AdminOrganizationService's UpdateOrganization RPC.
	AdminOrganizationServiceUpdateOrganizationProcedure = "/libops.v1.AdminOrganizationService/UpdateOrganization"
	// AdminOrganizationServiceDeleteOrganizationProcedure is the fully-qualified name of the
	// AdminOrganizationService's DeleteOrganization RPC.
	AdminOrganizationServiceDeleteOrganizationProcedure = "/libops.v1.AdminOrganizationService/DeleteOrganization"
	// AdminOrganizationServiceListOrganizationsProcedure is the fully-qualified name of the
	// AdminOrganizationService's ListOrganizations RPC.
	AdminOrganizationServiceListOrganizationsProcedure = "/libops.v1.AdminOrganizationService/ListOrganizations"
	// AdminOrganizationServiceListOrganizationProjectsProcedure is the fully-qualified name of the
	// AdminOrganizationService's ListOrganizationProjects RPC.
	AdminOrganizationServiceListOrganizationProjectsProcedure = "/libops.v1.AdminOrganizationService/ListOrganizationProjects"
	// AdminSiteServiceListSitesProcedure is the fully-qualified name of the AdminSiteService's
	// ListSites RPC.
	AdminSiteServiceListSitesProcedure = "/libops.v1.AdminSiteService/ListSites"
	// AdminSiteServiceGetSiteProcedure is the fully-qualified name of the AdminSiteService's GetSite
	// RPC.
	AdminSiteServiceGetSiteProcedure = "/libops.v1.AdminSiteService/GetSite"
	// AdminSiteServiceCreateSiteProcedure is the fully-qualified name of the AdminSiteService's
	// CreateSite RPC.
	AdminSiteServiceCreateSiteProcedure = "/libops.v1.AdminSiteService/CreateSite"
	// AdminSiteServiceUpdateSiteProcedure is the fully-qualified name of the AdminSiteService's
	// UpdateSite RPC.
	AdminSiteServiceUpdateSiteProcedure = "/libops.v1.AdminSiteService/UpdateSite"
	// AdminSiteServiceDeleteSiteProcedure is the fully-qualified name of the AdminSiteService's
	// DeleteSite RPC.
	AdminSiteServiceDeleteSiteProcedure = "/libops.v1.AdminSiteService/DeleteSite"
	// AdminSiteServiceListAllSitesProcedure is the fully-qualified name of the AdminSiteService's
	// ListAllSites RPC.
	AdminSiteServiceListAllSitesProcedure = "/libops.v1.AdminSiteService/ListAllSites"
	// AdminSiteServiceGetSiteSSHKeysProcedure is the fully-qualified name of the AdminSiteService's
	// GetSiteSSHKeys RPC.
	AdminSiteServiceGetSiteSSHKeysProcedure = "/libops.v1.AdminSiteService/GetSiteSSHKeys"
	// AdminSiteServiceGetSiteSecretsProcedure is the fully-qualified name of the AdminSiteService's
	// GetSiteSecrets RPC.
	AdminSiteServiceGetSiteSecretsProcedure = "/libops.v1.AdminSiteService/GetSiteSecrets"
	// AdminSiteServiceGetSiteFirewallProcedure is the fully-qualified name of the AdminSiteService's
	// GetSiteFirewall RPC.
	AdminSiteServiceGetSiteFirewallProcedure = "/libops.v1.AdminSiteService/GetSiteFirewall"
	// AdminSiteServiceSiteCheckInProcedure is the fully-qualified name of the AdminSiteService's
	// SiteCheckIn RPC.
	AdminSiteServiceSiteCheckInProcedure = "/libops.v1.AdminSiteService/SiteCheckIn"
	// AdminSiteServiceSyncManifestProcedure is the fully-qualified name of the AdminSiteService's
	// SyncManifest RPC.
	AdminSiteServiceSyncManifestProcedure = "/libops.v1.AdminSiteService/SyncManifest"
	// AdminSiteServiceGetBlobProcedure is the fully-qualified name of the AdminSiteService's GetBlob
	// RPC.
	AdminSiteServiceGetBlobProcedure = "/libops.v1.AdminSiteService/GetBlob"
	// AdminProjectServiceGetProjectProcedure is the fully-qualified name of the AdminProjectService's
	// GetProject RPC.
	AdminProjectServiceGetProjectProcedure = "/libops.v1.AdminProjectService/GetProject"
	// AdminProjectServiceCreateProjectProcedure is the fully-qualified name of the
	// AdminProjectService's CreateProject RPC.
	AdminProjectServiceCreateProjectProcedure = "/libops.v1.AdminProjectService/CreateProject"
	// AdminProjectServiceUpdateProjectProcedure is the fully-qualified name of the
	// AdminProjectService's UpdateProject RPC.
	AdminProjectServiceUpdateProjectProcedure = "/libops.v1.AdminProjectService/UpdateProject"
	// AdminProjectServiceDeleteProjectProcedure is the fully-qualified name of the
	// AdminProjectService's DeleteProject RPC.
	AdminProjectServiceDeleteProjectProcedure = "/libops.v1.AdminProjectService/DeleteProject"
	// AdminProjectServiceListProjectsProcedure is the fully-qualified name of the AdminProjectService's
	// ListProjects RPC.
	AdminProjectServiceListProjectsProcedure = "/libops.v1.AdminProjectService/ListProjects"
	// AdminProjectServiceListAllProjectsProcedure is the fully-qualified name of the
	// AdminProjectService's ListAllProjects RPC.
	AdminProjectServiceListAllProjectsProcedure = "/libops.v1.AdminProjectService/ListAllProjects"
	// AdminReconciliationServiceGetReconciliationRunProcedure is the fully-qualified name of the
	// AdminReconciliationService's GetReconciliationRun RPC.
	AdminReconciliationServiceGetReconciliationRunProcedure = "/libops.v1.AdminReconciliationService/GetReconciliationRun"
	// AdminReconciliationServiceUpdateReconciliationStatusProcedure is the fully-qualified name of the
	// AdminReconciliationService's UpdateReconciliationStatus RPC.
	AdminReconciliationServiceUpdateReconciliationStatusProcedure = "/libops.v1.AdminReconciliationService/UpdateReconciliationStatus"
	// AdminReconciliationServiceGenerateTerraformVarsProcedure is the fully-qualified name of the
	// AdminReconciliationService's GenerateTerraformVars RPC.
	AdminReconciliationServiceGenerateTerraformVarsProcedure = "/libops.v1.AdminReconciliationService/GenerateTerraformVars"
)

// AdminOrganizationServiceClient is a client for the libops.v1.AdminOrganizationService service.
type AdminOrganizationServiceClient interface {
	// Get organization configuration (admin view - includes sensitive fields)
	GetOrganization(context.Context, *connect.Request[v1.AdminGetOrganizationRequest]) (*connect.Response[v1.AdminGetOrganizationResponse], error)
	// Create a new organization (admin - can set all fields)
	CreateOrganization(context.Context, *connect.Request[v1.AdminCreateOrganizationRequest]) (*connect.Response[v1.AdminCreateOrganizationResponse], error)
	// Update organization metadata (admin - can update all fields)
	UpdateOrganization(context.Context, *connect.Request[v1.AdminUpdateOrganizationRequest]) (*connect.Response[v1.AdminUpdateOrganizationResponse], error)
	// Delete a organization (must have no projects)
	DeleteOrganization(context.Context, *connect.Request[v1.AdminDeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error)
	// List all organizations (admin view)
	ListOrganizations(context.Context, *connect.Request[v1.AdminListOrganizationsRequest]) (*connect.Response[v1.AdminListOrganizationsResponse], error)
	// List projects for a organization (admin view)
	ListOrganizationProjects(context.Context, *connect.Request[v1.AdminListOrganizationProjectsRequest]) (*connect.Response[v1.AdminListOrganizationProjectsResponse], error)
}

// NewAdminOrganizationServiceClient constructs a client for the libops.v1.AdminOrganizationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminOrganizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminOrganizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminOrganizationServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminOrganizationService").Methods()
	return &adminOrganizationServiceClient{
		getOrganization: connect.NewClient[v1.AdminGetOrganizationRequest, v1.AdminGetOrganizationResponse](
			httpClient,
			baseURL+AdminOrganizationServiceGetOrganizationProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("GetOrganization")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createOrganization: connect.NewClient[v1.AdminCreateOrganizationRequest, v1.AdminCreateOrganizationResponse](
			httpClient,
			baseURL+AdminOrganizationServiceCreateOrganizationProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		updateOrganization: connect.NewClient[v1.AdminUpdateOrganizationRequest, v1.AdminUpdateOrganizationResponse](
			httpClient,
			baseURL+AdminOrganizationServiceUpdateOrganizationProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("UpdateOrganization")),
			connect.WithClientOptions(opts...),
		),
		deleteOrganization: connect.NewClient[v1.AdminDeleteOrganizationRequest, emptypb.Empty](
			httpClient,
			baseURL+AdminOrganizationServiceDeleteOrganizationProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("DeleteOrganization")),
			connect.WithClientOptions(opts...),
		),
		listOrganizations: connect.NewClient[v1.AdminListOrganizationsRequest, v1.AdminListOrganizationsResponse](
			httpClient,
			baseURL+AdminOrganizationServiceListOrganizationsProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("ListOrganizations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listOrganizationProjects: connect.NewClient[v1.AdminListOrganizationProjectsRequest, v1.AdminListOrganizationProjectsResponse](
			httpClient,
			baseURL+AdminOrganizationServiceListOrganizationProjectsProcedure,
			connect.WithSchema(adminOrganizationServiceMethods.ByName("ListOrganizationProjects")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminOrganizationServiceClient implements AdminOrganizationServiceClient.
type adminOrganizationServiceClient struct {
	getOrganization          *connect.Client[v1.AdminGetOrganizationRequest, v1.AdminGetOrganizationResponse]
	createOrganization       *connect.Client[v1.AdminCreateOrganizationRequest, v1.AdminCreateOrganizationResponse]
	updateOrganization       *connect.Client[v1.AdminUpdateOrganizationRequest, v1.AdminUpdateOrganizationResponse]
	deleteOrganization       *connect.Client[v1.AdminDeleteOrganizationRequest, emptypb.Empty]
	listOrganizations        *connect.Client[v1.AdminListOrganizationsRequest, v1.AdminListOrganizationsResponse]
	listOrganizationProjects *connect.Client[v1.AdminListOrganizationProjectsRequest, v1.AdminListOrganizationProjectsResponse]
}

// GetOrganization calls libops.v1.AdminOrganizationService.GetOrganization.
func (c *adminOrganizationServiceClient) GetOrganization(ctx context.Context, req *connect.Request[v1.AdminGetOrganizationRequest]) (*connect.Response[v1.AdminGetOrganizationResponse], error) {
	return c.getOrganization.CallUnary(ctx, req)
}

// CreateOrganization calls libops.v1.AdminOrganizationService.CreateOrganization.
func (c *adminOrganizationServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[v1.AdminCreateOrganizationRequest]) (*connect.Response[v1.AdminCreateOrganizationResponse], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// UpdateOrganization calls libops.v1.AdminOrganizationService.UpdateOrganization.
func (c *adminOrganizationServiceClient) UpdateOrganization(ctx context.Context, req *connect.Request[v1.AdminUpdateOrganizationRequest]) (*connect.Response[v1.AdminUpdateOrganizationResponse], error) {
	return c.updateOrganization.CallUnary(ctx, req)
}

// DeleteOrganization calls libops.v1.AdminOrganizationService.DeleteOrganization.
func (c *adminOrganizationServiceClient) DeleteOrganization(ctx context.Context, req *connect.Request[v1.AdminDeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteOrganization.CallUnary(ctx, req)
}

// ListOrganizations calls libops.v1.AdminOrganizationService.ListOrganizations.
func (c *adminOrganizationServiceClient) ListOrganizations(ctx context.Context, req *connect.Request[v1.AdminListOrganizationsRequest]) (*connect.Response[v1.AdminListOrganizationsResponse], error) {
	return c.listOrganizations.CallUnary(ctx, req)
}

// ListOrganizationProjects calls libops.v1.AdminOrganizationService.ListOrganizationProjects.
func (c *adminOrganizationServiceClient) ListOrganizationProjects(ctx context.Context, req *connect.Request[v1.AdminListOrganizationProjectsRequest]) (*connect.Response[v1.AdminListOrganizationProjectsResponse], error) {
	return c.listOrganizationProjects.CallUnary(ctx, req)
}

// AdminOrganizationServiceHandler is an implementation of the libops.v1.AdminOrganizationService
// service.
type AdminOrganizationServiceHandler interface {
	// Get organization configuration (admin view - includes sensitive fields)
	GetOrganization(context.Context, *connect.Request[v1.AdminGetOrganizationRequest]) (*connect.Response[v1.AdminGetOrganizationResponse], error)
	// Create a new organization (admin - can set all fields)
	CreateOrganization(context.Context, *connect.Request[v1.AdminCreateOrganizationRequest]) (*connect.Response[v1.AdminCreateOrganizationResponse], error)
	// Update organization metadata (admin - can update all fields)
	UpdateOrganization(context.Context, *connect.Request[v1.AdminUpdateOrganizationRequest]) (*connect.Response[v1.AdminUpdateOrganizationResponse], error)
	// Delete a organization (must have no projects)
	DeleteOrganization(context.Context, *connect.Request[v1.AdminDeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error)
	// List all organizations (admin view)
	ListOrganizations(context.Context, *connect.Request[v1.AdminListOrganizationsRequest]) (*connect.Response[v1.AdminListOrganizationsResponse], error)
	// List projects for a organization (admin view)
	ListOrganizationProjects(context.Context, *connect.Request[v1.AdminListOrganizationProjectsRequest]) (*connect.Response[v1.AdminListOrganizationProjectsResponse], error)
}

// NewAdminOrganizationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminOrganizationServiceHandler(svc AdminOrganizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminOrganizationServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminOrganizationService").Methods()
	adminOrganizationServiceGetOrganizationHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceGetOrganizationProcedure,
		svc.GetOrganization,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("GetOrganization")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminOrganizationServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	adminOrganizationServiceUpdateOrganizationHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceUpdateOrganizationProcedure,
		svc.UpdateOrganization,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("UpdateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	adminOrganizationServiceDeleteOrganizationHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceDeleteOrganizationProcedure,
		svc.DeleteOrganization,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("DeleteOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	adminOrganizationServiceListOrganizationsHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceListOrganizationsProcedure,
		svc.ListOrganizations,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("ListOrganizations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminOrganizationServiceListOrganizationProjectsHandler := connect.NewUnaryHandler(
		AdminOrganizationServiceListOrganizationProjectsProcedure,
		svc.ListOrganizationProjects,
		connect.WithSchema(adminOrganizationServiceMethods.ByName("ListOrganizationProjects")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.AdminOrganizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminOrganizationServiceGetOrganizationProcedure:
			adminOrganizationServiceGetOrganizationHandler.ServeHTTP(w, r)
		case AdminOrganizationServiceCreateOrganizationProcedure:
			adminOrganizationServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case AdminOrganizationServiceUpdateOrganizationProcedure:
			adminOrganizationServiceUpdateOrganizationHandler.ServeHTTP(w, r)
		case AdminOrganizationServiceDeleteOrganizationProcedure:
			adminOrganizationServiceDeleteOrganizationHandler.ServeHTTP(w, r)
		case AdminOrganizationServiceListOrganizationsProcedure:
			adminOrganizationServiceListOrganizationsHandler.ServeHTTP(w, r)
		case AdminOrganizationServiceListOrganizationProjectsProcedure:
			adminOrganizationServiceListOrganizationProjectsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminOrganizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminOrganizationServiceHandler struct{}

func (UnimplementedAdminOrganizationServiceHandler) GetOrganization(context.Context, *connect.Request[v1.AdminGetOrganizationRequest]) (*connect.Response[v1.AdminGetOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.GetOrganization is not implemented"))
}

func (UnimplementedAdminOrganizationServiceHandler) CreateOrganization(context.Context, *connect.Request[v1.AdminCreateOrganizationRequest]) (*connect.Response[v1.AdminCreateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.CreateOrganization is not implemented"))
}

func (UnimplementedAdminOrganizationServiceHandler) UpdateOrganization(context.Context, *connect.Request[v1.AdminUpdateOrganizationRequest]) (*connect.Response[v1.AdminUpdateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.UpdateOrganization is not implemented"))
}

func (UnimplementedAdminOrganizationServiceHandler) DeleteOrganization(context.Context, *connect.Request[v1.AdminDeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.DeleteOrganization is not implemented"))
}

func (UnimplementedAdminOrganizationServiceHandler) ListOrganizations(context.Context, *connect.Request[v1.AdminListOrganizationsRequest]) (*connect.Response[v1.AdminListOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.ListOrganizations is not implemented"))
}

func (UnimplementedAdminOrganizationServiceHandler) ListOrganizationProjects(context.Context, *connect.Request[v1.AdminListOrganizationProjectsRequest]) (*connect.Response[v1.AdminListOrganizationProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminOrganizationService.ListOrganizationProjects is not implemented"))
}

// AdminSiteServiceClient is a client for the libops.v1.AdminSiteService service.
type AdminSiteServiceClient interface {
	// List sites (admin view)
	ListSites(context.Context, *connect.Request[v1.AdminListSitesRequest]) (*connect.Response[v1.AdminListSitesResponse], error)
	// Get site configuration (admin view - includes internal GCP details)
	GetSite(context.Context, *connect.Request[v1.AdminGetSiteRequest]) (*connect.Response[v1.AdminGetSiteResponse], error)
	// Create a new site (admin - can set all fields)
	CreateSite(context.Context, *connect.Request[v1.AdminCreateSiteRequest]) (*connect.Response[v1.AdminCreateSiteResponse], error)
	// Update site configuration (admin - can update all fields)
	UpdateSite(context.Context, *connect.Request[v1.AdminUpdateSiteRequest]) (*connect.Response[v1.AdminUpdateSiteResponse], error)
	// Delete a site
	DeleteSite(context.Context, *connect.Request[v1.AdminDeleteSiteRequest]) (*connect.Response[emptypb.Empty], error)
	// List all sites across all organizations/projects (admin only)
	ListAllSites(context.Context, *connect.Request[v1.AdminListAllSitesRequest]) (*connect.Response[v1.AdminListAllSitesResponse], error)
	// Get SSH keys for a site VM (called by VM controller with GSA auth)
	GetSiteSSHKeys(context.Context, *connect.Request[v1.GetSiteSSHKeysRequest]) (*connect.Response[v1.GetSiteSSHKeysResponse], error)
	// Get secrets for a site VM (called by VM controller with GSA auth)
	GetSiteSecrets(context.Context, *connect.Request[v1.GetSiteSecretsRequest]) (*connect.Response[v1.GetSiteSecretsResponse], error)
	// Get firewall rules for a site VM (called by VM controller with GSA auth)
	GetSiteFirewall(context.Context, *connect.Request[v1.GetSiteFirewallRequest]) (*connect.Response[v1.GetSiteFirewallResponse], error)
	// Site VM check-in (updates checkin_at timestamp)
	SiteCheckIn(context.Context, *connect.Request[v1.SiteCheckInRequest]) (*connect.Response[v1.SiteCheckInResponse], error)
	// Sync site manifest - returns state hash and signed URLs to blobs (for eventual consistency)
	// Called by site VMs every ~24h for eventual consistency
	SyncManifest(context.Context, *connect.Request[v1.SyncManifestRequest]) (*connect.Response[v1.SyncManifestResponse], error)
	// Get blob content via signed GCS URL (optional - VMs can fetch directly from GCS)
	GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error)
}

// NewAdminSiteServiceClient constructs a client for the libops.v1.AdminSiteService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminSiteServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminSiteServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminSiteServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminSiteService").Methods()
	return &adminSiteServiceClient{
		listSites: connect.NewClient[v1.AdminListSitesRequest, v1.AdminListSitesResponse](
			httpClient,
			baseURL+AdminSiteServiceListSitesProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("ListSites")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSite: connect.NewClient[v1.AdminGetSiteRequest, v1.AdminGetSiteResponse](
			httpClient,
			baseURL+AdminSiteServiceGetSiteProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("GetSite")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createSite: connect.NewClient[v1.AdminCreateSiteRequest, v1.AdminCreateSiteResponse](
			httpClient,
			baseURL+AdminSiteServiceCreateSiteProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("CreateSite")),
			connect.WithClientOptions(opts...),
		),
		updateSite: connect.NewClient[v1.AdminUpdateSiteRequest, v1.AdminUpdateSiteResponse](
			httpClient,
			baseURL+AdminSiteServiceUpdateSiteProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("UpdateSite")),
			connect.WithClientOptions(opts...),
		),
		deleteSite: connect.NewClient[v1.AdminDeleteSiteRequest, emptypb.Empty](
			httpClient,
			baseURL+AdminSiteServiceDeleteSiteProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("DeleteSite")),
			connect.WithClientOptions(opts...),
		),
		listAllSites: connect.NewClient[v1.AdminListAllSitesRequest, v1.AdminListAllSitesResponse](
			httpClient,
			baseURL+AdminSiteServiceListAllSitesProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("ListAllSites")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSiteSSHKeys: connect.NewClient[v1.GetSiteSSHKeysRequest, v1.GetSiteSSHKeysResponse](
			httpClient,
			baseURL+AdminSiteServiceGetSiteSSHKeysProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteSSHKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSiteSecrets: connect.NewClient[v1.GetSiteSecretsRequest, v1.GetSiteSecretsResponse](
			httpClient,
			baseURL+AdminSiteServiceGetSiteSecretsProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteSecrets")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSiteFirewall: connect.NewClient[v1.GetSiteFirewallRequest, v1.GetSiteFirewallResponse](
			httpClient,
			baseURL+AdminSiteServiceGetSiteFirewallProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteFirewall")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		siteCheckIn: connect.NewClient[v1.SiteCheckInRequest, v1.SiteCheckInResponse](
			httpClient,
			baseURL+AdminSiteServiceSiteCheckInProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("SiteCheckIn")),
			connect.WithClientOptions(opts...),
		),
		syncManifest: connect.NewClient[v1.SyncManifestRequest, v1.SyncManifestResponse](
			httpClient,
			baseURL+AdminSiteServiceSyncManifestProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("SyncManifest")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getBlob: connect.NewClient[v1.GetBlobRequest, v1.GetBlobResponse](
			httpClient,
			baseURL+AdminSiteServiceGetBlobProcedure,
			connect.WithSchema(adminSiteServiceMethods.ByName("GetBlob")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminSiteServiceClient implements AdminSiteServiceClient.
type adminSiteServiceClient struct {
	listSites       *connect.Client[v1.AdminListSitesRequest, v1.AdminListSitesResponse]
	getSite         *connect.Client[v1.AdminGetSiteRequest, v1.AdminGetSiteResponse]
	createSite      *connect.Client[v1.AdminCreateSiteRequest, v1.AdminCreateSiteResponse]
	updateSite      *connect.Client[v1.AdminUpdateSiteRequest, v1.AdminUpdateSiteResponse]
	deleteSite      *connect.Client[v1.AdminDeleteSiteRequest, emptypb.Empty]
	listAllSites    *connect.Client[v1.AdminListAllSitesRequest, v1.AdminListAllSitesResponse]
	getSiteSSHKeys  *connect.Client[v1.GetSiteSSHKeysRequest, v1.GetSiteSSHKeysResponse]
	getSiteSecrets  *connect.Client[v1.GetSiteSecretsRequest, v1.GetSiteSecretsResponse]
	getSiteFirewall *connect.Client[v1.GetSiteFirewallRequest, v1.GetSiteFirewallResponse]
	siteCheckIn     *connect.Client[v1.SiteCheckInRequest, v1.SiteCheckInResponse]
	syncManifest    *connect.Client[v1.SyncManifestRequest, v1.SyncManifestResponse]
	getBlob         *connect.Client[v1.GetBlobRequest, v1.GetBlobResponse]
}

// ListSites calls libops.v1.AdminSiteService.ListSites.
func (c *adminSiteServiceClient) ListSites(ctx context.Context, req *connect.Request[v1.AdminListSitesRequest]) (*connect.Response[v1.AdminListSitesResponse], error) {
	return c.listSites.CallUnary(ctx, req)
}

// GetSite calls libops.v1.AdminSiteService.GetSite.
func (c *adminSiteServiceClient) GetSite(ctx context.Context, req *connect.Request[v1.AdminGetSiteRequest]) (*connect.Response[v1.AdminGetSiteResponse], error) {
	return c.getSite.CallUnary(ctx, req)
}

// CreateSite calls libops.v1.AdminSiteService.CreateSite.
func (c *adminSiteServiceClient) CreateSite(ctx context.Context, req *connect.Request[v1.AdminCreateSiteRequest]) (*connect.Response[v1.AdminCreateSiteResponse], error) {
	return c.createSite.CallUnary(ctx, req)
}

// UpdateSite calls libops.v1.AdminSiteService.UpdateSite.
func (c *adminSiteServiceClient) UpdateSite(ctx context.Context, req *connect.Request[v1.AdminUpdateSiteRequest]) (*connect.Response[v1.AdminUpdateSiteResponse], error) {
	return c.updateSite.CallUnary(ctx, req)
}

// DeleteSite calls libops.v1.AdminSiteService.DeleteSite.
func (c *adminSiteServiceClient) DeleteSite(ctx context.Context, req *connect.Request[v1.AdminDeleteSiteRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteSite.CallUnary(ctx, req)
}

// ListAllSites calls libops.v1.AdminSiteService.ListAllSites.
func (c *adminSiteServiceClient) ListAllSites(ctx context.Context, req *connect.Request[v1.AdminListAllSitesRequest]) (*connect.Response[v1.AdminListAllSitesResponse], error) {
	return c.listAllSites.CallUnary(ctx, req)
}

// GetSiteSSHKeys calls libops.v1.AdminSiteService.GetSiteSSHKeys.
func (c *adminSiteServiceClient) GetSiteSSHKeys(ctx context.Context, req *connect.Request[v1.GetSiteSSHKeysRequest]) (*connect.Response[v1.GetSiteSSHKeysResponse], error) {
	return c.getSiteSSHKeys.CallUnary(ctx, req)
}

// GetSiteSecrets calls libops.v1.AdminSiteService.GetSiteSecrets.
func (c *adminSiteServiceClient) GetSiteSecrets(ctx context.Context, req *connect.Request[v1.GetSiteSecretsRequest]) (*connect.Response[v1.GetSiteSecretsResponse], error) {
	return c.getSiteSecrets.CallUnary(ctx, req)
}

// GetSiteFirewall calls libops.v1.AdminSiteService.GetSiteFirewall.
func (c *adminSiteServiceClient) GetSiteFirewall(ctx context.Context, req *connect.Request[v1.GetSiteFirewallRequest]) (*connect.Response[v1.GetSiteFirewallResponse], error) {
	return c.getSiteFirewall.CallUnary(ctx, req)
}

// SiteCheckIn calls libops.v1.AdminSiteService.SiteCheckIn.
func (c *adminSiteServiceClient) SiteCheckIn(ctx context.Context, req *connect.Request[v1.SiteCheckInRequest]) (*connect.Response[v1.SiteCheckInResponse], error) {
	return c.siteCheckIn.CallUnary(ctx, req)
}

// SyncManifest calls libops.v1.AdminSiteService.SyncManifest.
func (c *adminSiteServiceClient) SyncManifest(ctx context.Context, req *connect.Request[v1.SyncManifestRequest]) (*connect.Response[v1.SyncManifestResponse], error) {
	return c.syncManifest.CallUnary(ctx, req)
}

// GetBlob calls libops.v1.AdminSiteService.GetBlob.
func (c *adminSiteServiceClient) GetBlob(ctx context.Context, req *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error) {
	return c.getBlob.CallUnary(ctx, req)
}

// AdminSiteServiceHandler is an implementation of the libops.v1.AdminSiteService service.
type AdminSiteServiceHandler interface {
	// List sites (admin view)
	ListSites(context.Context, *connect.Request[v1.AdminListSitesRequest]) (*connect.Response[v1.AdminListSitesResponse], error)
	// Get site configuration (admin view - includes internal GCP details)
	GetSite(context.Context, *connect.Request[v1.AdminGetSiteRequest]) (*connect.Response[v1.AdminGetSiteResponse], error)
	// Create a new site (admin - can set all fields)
	CreateSite(context.Context, *connect.Request[v1.AdminCreateSiteRequest]) (*connect.Response[v1.AdminCreateSiteResponse], error)
	// Update site configuration (admin - can update all fields)
	UpdateSite(context.Context, *connect.Request[v1.AdminUpdateSiteRequest]) (*connect.Response[v1.AdminUpdateSiteResponse], error)
	// Delete a site
	DeleteSite(context.Context, *connect.Request[v1.AdminDeleteSiteRequest]) (*connect.Response[emptypb.Empty], error)
	// List all sites across all organizations/projects (admin only)
	ListAllSites(context.Context, *connect.Request[v1.AdminListAllSitesRequest]) (*connect.Response[v1.AdminListAllSitesResponse], error)
	// Get SSH keys for a site VM (called by VM controller with GSA auth)
	GetSiteSSHKeys(context.Context, *connect.Request[v1.GetSiteSSHKeysRequest]) (*connect.Response[v1.GetSiteSSHKeysResponse], error)
	// Get secrets for a site VM (called by VM controller with GSA auth)
	GetSiteSecrets(context.Context, *connect.Request[v1.GetSiteSecretsRequest]) (*connect.Response[v1.GetSiteSecretsResponse], error)
	// Get firewall rules for a site VM (called by VM controller with GSA auth)
	GetSiteFirewall(context.Context, *connect.Request[v1.GetSiteFirewallRequest]) (*connect.Response[v1.GetSiteFirewallResponse], error)
	// Site VM check-in (updates checkin_at timestamp)
	SiteCheckIn(context.Context, *connect.Request[v1.SiteCheckInRequest]) (*connect.Response[v1.SiteCheckInResponse], error)
	// Sync site manifest - returns state hash and signed URLs to blobs (for eventual consistency)
	// Called by site VMs every ~24h for eventual consistency
	SyncManifest(context.Context, *connect.Request[v1.SyncManifestRequest]) (*connect.Response[v1.SyncManifestResponse], error)
	// Get blob content via signed GCS URL (optional - VMs can fetch directly from GCS)
	GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error)
}

// NewAdminSiteServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminSiteServiceHandler(svc AdminSiteServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminSiteServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminSiteService").Methods()
	adminSiteServiceListSitesHandler := connect.NewUnaryHandler(
		AdminSiteServiceListSitesProcedure,
		svc.ListSites,
		connect.WithSchema(adminSiteServiceMethods.ByName("ListSites")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceGetSiteHandler := connect.NewUnaryHandler(
		AdminSiteServiceGetSiteProcedure,
		svc.GetSite,
		connect.WithSchema(adminSiteServiceMethods.ByName("GetSite")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceCreateSiteHandler := connect.NewUnaryHandler(
		AdminSiteServiceCreateSiteProcedure,
		svc.CreateSite,
		connect.WithSchema(adminSiteServiceMethods.ByName("CreateSite")),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceUpdateSiteHandler := connect.NewUnaryHandler(
		AdminSiteServiceUpdateSiteProcedure,
		svc.UpdateSite,
		connect.WithSchema(adminSiteServiceMethods.ByName("UpdateSite")),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceDeleteSiteHandler := connect.NewUnaryHandler(
		AdminSiteServiceDeleteSiteProcedure,
		svc.DeleteSite,
		connect.WithSchema(adminSiteServiceMethods.ByName("DeleteSite")),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceListAllSitesHandler := connect.NewUnaryHandler(
		AdminSiteServiceListAllSitesProcedure,
		svc.ListAllSites,
		connect.WithSchema(adminSiteServiceMethods.ByName("ListAllSites")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceGetSiteSSHKeysHandler := connect.NewUnaryHandler(
		AdminSiteServiceGetSiteSSHKeysProcedure,
		svc.GetSiteSSHKeys,
		connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteSSHKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceGetSiteSecretsHandler := connect.NewUnaryHandler(
		AdminSiteServiceGetSiteSecretsProcedure,
		svc.GetSiteSecrets,
		connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteSecrets")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceGetSiteFirewallHandler := connect.NewUnaryHandler(
		AdminSiteServiceGetSiteFirewallProcedure,
		svc.GetSiteFirewall,
		connect.WithSchema(adminSiteServiceMethods.ByName("GetSiteFirewall")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceSiteCheckInHandler := connect.NewUnaryHandler(
		AdminSiteServiceSiteCheckInProcedure,
		svc.SiteCheckIn,
		connect.WithSchema(adminSiteServiceMethods.ByName("SiteCheckIn")),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceSyncManifestHandler := connect.NewUnaryHandler(
		AdminSiteServiceSyncManifestProcedure,
		svc.SyncManifest,
		connect.WithSchema(adminSiteServiceMethods.ByName("SyncManifest")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminSiteServiceGetBlobHandler := connect.NewUnaryHandler(
		AdminSiteServiceGetBlobProcedure,
		svc.GetBlob,
		connect.WithSchema(adminSiteServiceMethods.ByName("GetBlob")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.AdminSiteService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminSiteServiceListSitesProcedure:
			adminSiteServiceListSitesHandler.ServeHTTP(w, r)
		case AdminSiteServiceGetSiteProcedure:
			adminSiteServiceGetSiteHandler.ServeHTTP(w, r)
		case AdminSiteServiceCreateSiteProcedure:
			adminSiteServiceCreateSiteHandler.ServeHTTP(w, r)
		case AdminSiteServiceUpdateSiteProcedure:
			adminSiteServiceUpdateSiteHandler.ServeHTTP(w, r)
		case AdminSiteServiceDeleteSiteProcedure:
			adminSiteServiceDeleteSiteHandler.ServeHTTP(w, r)
		case AdminSiteServiceListAllSitesProcedure:
			adminSiteServiceListAllSitesHandler.ServeHTTP(w, r)
		case AdminSiteServiceGetSiteSSHKeysProcedure:
			adminSiteServiceGetSiteSSHKeysHandler.ServeHTTP(w, r)
		case AdminSiteServiceGetSiteSecretsProcedure:
			adminSiteServiceGetSiteSecretsHandler.ServeHTTP(w, r)
		case AdminSiteServiceGetSiteFirewallProcedure:
			adminSiteServiceGetSiteFirewallHandler.ServeHTTP(w, r)
		case AdminSiteServiceSiteCheckInProcedure:
			adminSiteServiceSiteCheckInHandler.ServeHTTP(w, r)
		case AdminSiteServiceSyncManifestProcedure:
			adminSiteServiceSyncManifestHandler.ServeHTTP(w, r)
		case AdminSiteServiceGetBlobProcedure:
			adminSiteServiceGetBlobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminSiteServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminSiteServiceHandler struct{}

func (UnimplementedAdminSiteServiceHandler) ListSites(context.Context, *connect.Request[v1.AdminListSitesRequest]) (*connect.Response[v1.AdminListSitesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.ListSites is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) GetSite(context.Context, *connect.Request[v1.AdminGetSiteRequest]) (*connect.Response[v1.AdminGetSiteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.GetSite is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) CreateSite(context.Context, *connect.Request[v1.AdminCreateSiteRequest]) (*connect.Response[v1.AdminCreateSiteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.CreateSite is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) UpdateSite(context.Context, *connect.Request[v1.AdminUpdateSiteRequest]) (*connect.Response[v1.AdminUpdateSiteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.UpdateSite is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) DeleteSite(context.Context, *connect.Request[v1.AdminDeleteSiteRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.DeleteSite is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) ListAllSites(context.Context, *connect.Request[v1.AdminListAllSitesRequest]) (*connect.Response[v1.AdminListAllSitesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.ListAllSites is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) GetSiteSSHKeys(context.Context, *connect.Request[v1.GetSiteSSHKeysRequest]) (*connect.Response[v1.GetSiteSSHKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.GetSiteSSHKeys is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) GetSiteSecrets(context.Context, *connect.Request[v1.GetSiteSecretsRequest]) (*connect.Response[v1.GetSiteSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.GetSiteSecrets is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) GetSiteFirewall(context.Context, *connect.Request[v1.GetSiteFirewallRequest]) (*connect.Response[v1.GetSiteFirewallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.GetSiteFirewall is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) SiteCheckIn(context.Context, *connect.Request[v1.SiteCheckInRequest]) (*connect.Response[v1.SiteCheckInResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.SiteCheckIn is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) SyncManifest(context.Context, *connect.Request[v1.SyncManifestRequest]) (*connect.Response[v1.SyncManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.SyncManifest is not implemented"))
}

func (UnimplementedAdminSiteServiceHandler) GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminSiteService.GetBlob is not implemented"))
}

// AdminProjectServiceClient is a client for the libops.v1.AdminProjectService service.
type AdminProjectServiceClient interface {
	// Get project configuration (admin view - includes sensitive fields)
	GetProject(context.Context, *connect.Request[v1.AdminGetProjectRequest]) (*connect.Response[v1.AdminGetProjectResponse], error)
	// Create a new project (admin - can set all fields)
	CreateProject(context.Context, *connect.Request[v1.AdminCreateProjectRequest]) (*connect.Response[v1.AdminCreateProjectResponse], error)
	// Update project configuration (admin - can update all fields)
	UpdateProject(context.Context, *connect.Request[v1.AdminUpdateProjectRequest]) (*connect.Response[v1.AdminUpdateProjectResponse], error)
	// Delete a project (must have no sites)
	DeleteProject(context.Context, *connect.Request[v1.AdminDeleteProjectRequest]) (*connect.Response[emptypb.Empty], error)
	// List projects for a organization (admin view)
	ListProjects(context.Context, *connect.Request[v1.AdminListProjectsRequest]) (*connect.Response[v1.AdminListProjectsResponse], error)
	// List all projects across all organizations (admin only)
	ListAllProjects(context.Context, *connect.Request[v1.AdminListAllProjectsRequest]) (*connect.Response[v1.AdminListAllProjectsResponse], error)
}

// NewAdminProjectServiceClient constructs a client for the libops.v1.AdminProjectService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminProjectServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminProjectService").Methods()
	return &adminProjectServiceClient{
		getProject: connect.NewClient[v1.AdminGetProjectRequest, v1.AdminGetProjectResponse](
			httpClient,
			baseURL+AdminProjectServiceGetProjectProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("GetProject")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[v1.AdminCreateProjectRequest, v1.AdminCreateProjectResponse](
			httpClient,
			baseURL+AdminProjectServiceCreateProjectProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.AdminUpdateProjectRequest, v1.AdminUpdateProjectResponse](
			httpClient,
			baseURL+AdminProjectServiceUpdateProjectProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[v1.AdminDeleteProjectRequest, emptypb.Empty](
			httpClient,
			baseURL+AdminProjectServiceDeleteProjectProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.AdminListProjectsRequest, v1.AdminListProjectsResponse](
			httpClient,
			baseURL+AdminProjectServiceListProjectsProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("ListProjects")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listAllProjects: connect.NewClient[v1.AdminListAllProjectsRequest, v1.AdminListAllProjectsResponse](
			httpClient,
			baseURL+AdminProjectServiceListAllProjectsProcedure,
			connect.WithSchema(adminProjectServiceMethods.ByName("ListAllProjects")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminProjectServiceClient implements AdminProjectServiceClient.
type adminProjectServiceClient struct {
	getProject      *connect.Client[v1.AdminGetProjectRequest, v1.AdminGetProjectResponse]
	createProject   *connect.Client[v1.AdminCreateProjectRequest, v1.AdminCreateProjectResponse]
	updateProject   *connect.Client[v1.AdminUpdateProjectRequest, v1.AdminUpdateProjectResponse]
	deleteProject   *connect.Client[v1.AdminDeleteProjectRequest, emptypb.Empty]
	listProjects    *connect.Client[v1.AdminListProjectsRequest, v1.AdminListProjectsResponse]
	listAllProjects *connect.Client[v1.AdminListAllProjectsRequest, v1.AdminListAllProjectsResponse]
}

// GetProject calls libops.v1.AdminProjectService.GetProject.
func (c *adminProjectServiceClient) GetProject(ctx context.Context, req *connect.Request[v1.AdminGetProjectRequest]) (*connect.Response[v1.AdminGetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// CreateProject calls libops.v1.AdminProjectService.CreateProject.
func (c *adminProjectServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.AdminCreateProjectRequest]) (*connect.Response[v1.AdminCreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// UpdateProject calls libops.v1.AdminProjectService.UpdateProject.
func (c *adminProjectServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.AdminUpdateProjectRequest]) (*connect.Response[v1.AdminUpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// DeleteProject calls libops.v1.AdminProjectService.DeleteProject.
func (c *adminProjectServiceClient) DeleteProject(ctx context.Context, req *connect.Request[v1.AdminDeleteProjectRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// ListProjects calls libops.v1.AdminProjectService.ListProjects.
func (c *adminProjectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.AdminListProjectsRequest]) (*connect.Response[v1.AdminListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// ListAllProjects calls libops.v1.AdminProjectService.ListAllProjects.
func (c *adminProjectServiceClient) ListAllProjects(ctx context.Context, req *connect.Request[v1.AdminListAllProjectsRequest]) (*connect.Response[v1.AdminListAllProjectsResponse], error) {
	return c.listAllProjects.CallUnary(ctx, req)
}

// AdminProjectServiceHandler is an implementation of the libops.v1.AdminProjectService service.
type AdminProjectServiceHandler interface {
	// Get project configuration (admin view - includes sensitive fields)
	GetProject(context.Context, *connect.Request[v1.AdminGetProjectRequest]) (*connect.Response[v1.AdminGetProjectResponse], error)
	// Create a new project (admin - can set all fields)
	CreateProject(context.Context, *connect.Request[v1.AdminCreateProjectRequest]) (*connect.Response[v1.AdminCreateProjectResponse], error)
	// Update project configuration (admin - can update all fields)
	UpdateProject(context.Context, *connect.Request[v1.AdminUpdateProjectRequest]) (*connect.Response[v1.AdminUpdateProjectResponse], error)
	// Delete a project (must have no sites)
	DeleteProject(context.Context, *connect.Request[v1.AdminDeleteProjectRequest]) (*connect.Response[emptypb.Empty], error)
	// List projects for a organization (admin view)
	ListProjects(context.Context, *connect.Request[v1.AdminListProjectsRequest]) (*connect.Response[v1.AdminListProjectsResponse], error)
	// List all projects across all organizations (admin only)
	ListAllProjects(context.Context, *connect.Request[v1.AdminListAllProjectsRequest]) (*connect.Response[v1.AdminListAllProjectsResponse], error)
}

// NewAdminProjectServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminProjectServiceHandler(svc AdminProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminProjectServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminProjectService").Methods()
	adminProjectServiceGetProjectHandler := connect.NewUnaryHandler(
		AdminProjectServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(adminProjectServiceMethods.ByName("GetProject")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminProjectServiceCreateProjectHandler := connect.NewUnaryHandler(
		AdminProjectServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(adminProjectServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	adminProjectServiceUpdateProjectHandler := connect.NewUnaryHandler(
		AdminProjectServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(adminProjectServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	adminProjectServiceDeleteProjectHandler := connect.NewUnaryHandler(
		AdminProjectServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(adminProjectServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	adminProjectServiceListProjectsHandler := connect.NewUnaryHandler(
		AdminProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(adminProjectServiceMethods.ByName("ListProjects")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminProjectServiceListAllProjectsHandler := connect.NewUnaryHandler(
		AdminProjectServiceListAllProjectsProcedure,
		svc.ListAllProjects,
		connect.WithSchema(adminProjectServiceMethods.ByName("ListAllProjects")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.AdminProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminProjectServiceGetProjectProcedure:
			adminProjectServiceGetProjectHandler.ServeHTTP(w, r)
		case AdminProjectServiceCreateProjectProcedure:
			adminProjectServiceCreateProjectHandler.ServeHTTP(w, r)
		case AdminProjectServiceUpdateProjectProcedure:
			adminProjectServiceUpdateProjectHandler.ServeHTTP(w, r)
		case AdminProjectServiceDeleteProjectProcedure:
			adminProjectServiceDeleteProjectHandler.ServeHTTP(w, r)
		case AdminProjectServiceListProjectsProcedure:
			adminProjectServiceListProjectsHandler.ServeHTTP(w, r)
		case AdminProjectServiceListAllProjectsProcedure:
			adminProjectServiceListAllProjectsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminProjectServiceHandler struct{}

func (UnimplementedAdminProjectServiceHandler) GetProject(context.Context, *connect.Request[v1.AdminGetProjectRequest]) (*connect.Response[v1.AdminGetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.GetProject is not implemented"))
}

func (UnimplementedAdminProjectServiceHandler) CreateProject(context.Context, *connect.Request[v1.AdminCreateProjectRequest]) (*connect.Response[v1.AdminCreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.CreateProject is not implemented"))
}

func (UnimplementedAdminProjectServiceHandler) UpdateProject(context.Context, *connect.Request[v1.AdminUpdateProjectRequest]) (*connect.Response[v1.AdminUpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.UpdateProject is not implemented"))
}

func (UnimplementedAdminProjectServiceHandler) DeleteProject(context.Context, *connect.Request[v1.AdminDeleteProjectRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.DeleteProject is not implemented"))
}

func (UnimplementedAdminProjectServiceHandler) ListProjects(context.Context, *connect.Request[v1.AdminListProjectsRequest]) (*connect.Response[v1.AdminListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.ListProjects is not implemented"))
}

func (UnimplementedAdminProjectServiceHandler) ListAllProjects(context.Context, *connect.Request[v1.AdminListAllProjectsRequest]) (*connect.Response[v1.AdminListAllProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminProjectService.ListAllProjects is not implemented"))
}

// AdminReconciliationServiceClient is a client for the libops.v1.AdminReconciliationService
// service.
type AdminReconciliationServiceClient interface {
	// Get reconciliation run details from control-plane database
	GetReconciliationRun(context.Context, *connect.Request[v1.GetReconciliationRunRequest]) (*connect.Response[v1.GetReconciliationRunResponse], error)
	// Update reconciliation run status
	UpdateReconciliationStatus(context.Context, *connect.Request[v1.UpdateReconciliationStatusRequest]) (*connect.Response[v1.UpdateReconciliationStatusResponse], error)
	// Generate terraform variables JSON from database state
	GenerateTerraformVars(context.Context, *connect.Request[v1.GenerateTerraformVarsRequest]) (*connect.Response[v1.GenerateTerraformVarsResponse], error)
}

// NewAdminReconciliationServiceClient constructs a client for the
// libops.v1.AdminReconciliationService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminReconciliationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminReconciliationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminReconciliationServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminReconciliationService").Methods()
	return &adminReconciliationServiceClient{
		getReconciliationRun: connect.NewClient[v1.GetReconciliationRunRequest, v1.GetReconciliationRunResponse](
			httpClient,
			baseURL+AdminReconciliationServiceGetReconciliationRunProcedure,
			connect.WithSchema(adminReconciliationServiceMethods.ByName("GetReconciliationRun")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateReconciliationStatus: connect.NewClient[v1.UpdateReconciliationStatusRequest, v1.UpdateReconciliationStatusResponse](
			httpClient,
			baseURL+AdminReconciliationServiceUpdateReconciliationStatusProcedure,
			connect.WithSchema(adminReconciliationServiceMethods.ByName("UpdateReconciliationStatus")),
			connect.WithClientOptions(opts...),
		),
		generateTerraformVars: connect.NewClient[v1.GenerateTerraformVarsRequest, v1.GenerateTerraformVarsResponse](
			httpClient,
			baseURL+AdminReconciliationServiceGenerateTerraformVarsProcedure,
			connect.WithSchema(adminReconciliationServiceMethods.ByName("GenerateTerraformVars")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminReconciliationServiceClient implements AdminReconciliationServiceClient.
type adminReconciliationServiceClient struct {
	getReconciliationRun       *connect.Client[v1.GetReconciliationRunRequest, v1.GetReconciliationRunResponse]
	updateReconciliationStatus *connect.Client[v1.UpdateReconciliationStatusRequest, v1.UpdateReconciliationStatusResponse]
	generateTerraformVars      *connect.Client[v1.GenerateTerraformVarsRequest, v1.GenerateTerraformVarsResponse]
}

// GetReconciliationRun calls libops.v1.AdminReconciliationService.GetReconciliationRun.
func (c *adminReconciliationServiceClient) GetReconciliationRun(ctx context.Context, req *connect.Request[v1.GetReconciliationRunRequest]) (*connect.Response[v1.GetReconciliationRunResponse], error) {
	return c.getReconciliationRun.CallUnary(ctx, req)
}

// UpdateReconciliationStatus calls libops.v1.AdminReconciliationService.UpdateReconciliationStatus.
func (c *adminReconciliationServiceClient) UpdateReconciliationStatus(ctx context.Context, req *connect.Request[v1.UpdateReconciliationStatusRequest]) (*connect.Response[v1.UpdateReconciliationStatusResponse], error) {
	return c.updateReconciliationStatus.CallUnary(ctx, req)
}

// GenerateTerraformVars calls libops.v1.AdminReconciliationService.GenerateTerraformVars.
func (c *adminReconciliationServiceClient) GenerateTerraformVars(ctx context.Context, req *connect.Request[v1.GenerateTerraformVarsRequest]) (*connect.Response[v1.GenerateTerraformVarsResponse], error) {
	return c.generateTerraformVars.CallUnary(ctx, req)
}

// AdminReconciliationServiceHandler is an implementation of the
// libops.v1.AdminReconciliationService service.
type AdminReconciliationServiceHandler interface {
	// Get reconciliation run details from control-plane database
	GetReconciliationRun(context.Context, *connect.Request[v1.GetReconciliationRunRequest]) (*connect.Response[v1.GetReconciliationRunResponse], error)
	// Update reconciliation run status
	UpdateReconciliationStatus(context.Context, *connect.Request[v1.UpdateReconciliationStatusRequest]) (*connect.Response[v1.UpdateReconciliationStatusResponse], error)
	// Generate terraform variables JSON from database state
	GenerateTerraformVars(context.Context, *connect.Request[v1.GenerateTerraformVarsRequest]) (*connect.Response[v1.GenerateTerraformVarsResponse], error)
}

// NewAdminReconciliationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminReconciliationServiceHandler(svc AdminReconciliationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminReconciliationServiceMethods := v1.File_libops_v1_admin_api_proto.Services().ByName("AdminReconciliationService").Methods()
	adminReconciliationServiceGetReconciliationRunHandler := connect.NewUnaryHandler(
		AdminReconciliationServiceGetReconciliationRunProcedure,
		svc.GetReconciliationRun,
		connect.WithSchema(adminReconciliationServiceMethods.ByName("GetReconciliationRun")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	adminReconciliationServiceUpdateReconciliationStatusHandler := connect.NewUnaryHandler(
		AdminReconciliationServiceUpdateReconciliationStatusProcedure,
		svc.UpdateReconciliationStatus,
		connect.WithSchema(adminReconciliationServiceMethods.ByName("UpdateReconciliationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	adminReconciliationServiceGenerateTerraformVarsHandler := connect.NewUnaryHandler(
		AdminReconciliationServiceGenerateTerraformVarsProcedure,
		svc.GenerateTerraformVars,
		connect.WithSchema(adminReconciliationServiceMethods.ByName("GenerateTerraformVars")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.AdminReconciliationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminReconciliationServiceGetReconciliationRunProcedure:
			adminReconciliationServiceGetReconciliationRunHandler.ServeHTTP(w, r)
		case AdminReconciliationServiceUpdateReconciliationStatusProcedure:
			adminReconciliationServiceUpdateReconciliationStatusHandler.ServeHTTP(w, r)
		case AdminReconciliationServiceGenerateTerraformVarsProcedure:
			adminReconciliationServiceGenerateTerraformVarsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminReconciliationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminReconciliationServiceHandler struct{}

func (UnimplementedAdminReconciliationServiceHandler) GetReconciliationRun(context.Context, *connect.Request[v1.GetReconciliationRunRequest]) (*connect.Response[v1.GetReconciliationRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminReconciliationService.GetReconciliationRun is not implemented"))
}

func (UnimplementedAdminReconciliationServiceHandler) UpdateReconciliationStatus(context.Context, *connect.Request[v1.UpdateReconciliationStatusRequest]) (*connect.Response[v1.UpdateReconciliationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminReconciliationService.UpdateReconciliationStatus is not implemented"))
}

func (UnimplementedAdminReconciliationServiceHandler) GenerateTerraformVars(context.Context, *connect.Request[v1.GenerateTerraformVarsRequest]) (*connect.Response[v1.GenerateTerraformVarsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AdminReconciliationService.GenerateTerraformVars is not implemented"))
}
