// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: libops/v1/organization_account_api.proto

package libopsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/libops/proto/libops/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "libops.v1.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceGetAccountByEmailProcedure is the fully-qualified name of the AccountService's
	// GetAccountByEmail RPC.
	AccountServiceGetAccountByEmailProcedure = "/libops.v1.AccountService/GetAccountByEmail"
	// AccountServiceCreateApiKeyProcedure is the fully-qualified name of the AccountService's
	// CreateApiKey RPC.
	AccountServiceCreateApiKeyProcedure = "/libops.v1.AccountService/CreateApiKey"
	// AccountServiceListApiKeysProcedure is the fully-qualified name of the AccountService's
	// ListApiKeys RPC.
	AccountServiceListApiKeysProcedure = "/libops.v1.AccountService/ListApiKeys"
	// AccountServiceRevokeApiKeyProcedure is the fully-qualified name of the AccountService's
	// RevokeApiKey RPC.
	AccountServiceRevokeApiKeyProcedure = "/libops.v1.AccountService/RevokeApiKey"
)

// AccountServiceClient is a client for the libops.v1.AccountService service.
type AccountServiceClient interface {
	// Get account information by email (for Terraform provider lookups)
	GetAccountByEmail(context.Context, *connect.Request[v1.GetAccountByEmailRequest]) (*connect.Response[v1.GetAccountByEmailResponse], error)
	// Create an API key for the authenticated user
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// List API keys for the authenticated user
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// Revoke an API key for the authenticated user
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
}

// NewAccountServiceClient constructs a client for the libops.v1.AccountService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := v1.File_libops_v1_organization_account_api_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		getAccountByEmail: connect.NewClient[v1.GetAccountByEmailRequest, v1.GetAccountByEmailResponse](
			httpClient,
			baseURL+AccountServiceGetAccountByEmailProcedure,
			connect.WithSchema(accountServiceMethods.ByName("GetAccountByEmail")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+AccountServiceCreateApiKeyProcedure,
			connect.WithSchema(accountServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+AccountServiceListApiKeysProcedure,
			connect.WithSchema(accountServiceMethods.ByName("ListApiKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse](
			httpClient,
			baseURL+AccountServiceRevokeApiKeyProcedure,
			connect.WithSchema(accountServiceMethods.ByName("RevokeApiKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	getAccountByEmail *connect.Client[v1.GetAccountByEmailRequest, v1.GetAccountByEmailResponse]
	createApiKey      *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	listApiKeys       *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	revokeApiKey      *connect.Client[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse]
}

// GetAccountByEmail calls libops.v1.AccountService.GetAccountByEmail.
func (c *accountServiceClient) GetAccountByEmail(ctx context.Context, req *connect.Request[v1.GetAccountByEmailRequest]) (*connect.Response[v1.GetAccountByEmailResponse], error) {
	return c.getAccountByEmail.CallUnary(ctx, req)
}

// CreateApiKey calls libops.v1.AccountService.CreateApiKey.
func (c *accountServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls libops.v1.AccountService.ListApiKeys.
func (c *accountServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// RevokeApiKey calls libops.v1.AccountService.RevokeApiKey.
func (c *accountServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the libops.v1.AccountService service.
type AccountServiceHandler interface {
	// Get account information by email (for Terraform provider lookups)
	GetAccountByEmail(context.Context, *connect.Request[v1.GetAccountByEmailRequest]) (*connect.Response[v1.GetAccountByEmailResponse], error)
	// Create an API key for the authenticated user
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// List API keys for the authenticated user
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// Revoke an API key for the authenticated user
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := v1.File_libops_v1_organization_account_api_proto.Services().ByName("AccountService").Methods()
	accountServiceGetAccountByEmailHandler := connect.NewUnaryHandler(
		AccountServiceGetAccountByEmailProcedure,
		svc.GetAccountByEmail,
		connect.WithSchema(accountServiceMethods.ByName("GetAccountByEmail")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		AccountServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(accountServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceListApiKeysHandler := connect.NewUnaryHandler(
		AccountServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(accountServiceMethods.ByName("ListApiKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		AccountServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(accountServiceMethods.ByName("RevokeApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceGetAccountByEmailProcedure:
			accountServiceGetAccountByEmailHandler.ServeHTTP(w, r)
		case AccountServiceCreateApiKeyProcedure:
			accountServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case AccountServiceListApiKeysProcedure:
			accountServiceListApiKeysHandler.ServeHTTP(w, r)
		case AccountServiceRevokeApiKeyProcedure:
			accountServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) GetAccountByEmail(context.Context, *connect.Request[v1.GetAccountByEmailRequest]) (*connect.Response[v1.GetAccountByEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AccountService.GetAccountByEmail is not implemented"))
}

func (UnimplementedAccountServiceHandler) CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AccountService.CreateApiKey is not implemented"))
}

func (UnimplementedAccountServiceHandler) ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AccountService.ListApiKeys is not implemented"))
}

func (UnimplementedAccountServiceHandler) RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.AccountService.RevokeApiKey is not implemented"))
}
