// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: libops/v1/settings.proto

package libopsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/libops/proto/libops/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrganizationSettingServiceName is the fully-qualified name of the OrganizationSettingService
	// service.
	OrganizationSettingServiceName = "libops.v1.OrganizationSettingService"
	// ProjectSettingServiceName is the fully-qualified name of the ProjectSettingService service.
	ProjectSettingServiceName = "libops.v1.ProjectSettingService"
	// SiteSettingServiceName is the fully-qualified name of the SiteSettingService service.
	SiteSettingServiceName = "libops.v1.SiteSettingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrganizationSettingServiceCreateOrganizationSettingProcedure is the fully-qualified name of the
	// OrganizationSettingService's CreateOrganizationSetting RPC.
	OrganizationSettingServiceCreateOrganizationSettingProcedure = "/libops.v1.OrganizationSettingService/CreateOrganizationSetting"
	// OrganizationSettingServiceGetOrganizationSettingProcedure is the fully-qualified name of the
	// OrganizationSettingService's GetOrganizationSetting RPC.
	OrganizationSettingServiceGetOrganizationSettingProcedure = "/libops.v1.OrganizationSettingService/GetOrganizationSetting"
	// OrganizationSettingServiceListOrganizationSettingsProcedure is the fully-qualified name of the
	// OrganizationSettingService's ListOrganizationSettings RPC.
	OrganizationSettingServiceListOrganizationSettingsProcedure = "/libops.v1.OrganizationSettingService/ListOrganizationSettings"
	// OrganizationSettingServiceUpdateOrganizationSettingProcedure is the fully-qualified name of the
	// OrganizationSettingService's UpdateOrganizationSetting RPC.
	OrganizationSettingServiceUpdateOrganizationSettingProcedure = "/libops.v1.OrganizationSettingService/UpdateOrganizationSetting"
	// OrganizationSettingServiceDeleteOrganizationSettingProcedure is the fully-qualified name of the
	// OrganizationSettingService's DeleteOrganizationSetting RPC.
	OrganizationSettingServiceDeleteOrganizationSettingProcedure = "/libops.v1.OrganizationSettingService/DeleteOrganizationSetting"
	// ProjectSettingServiceCreateProjectSettingProcedure is the fully-qualified name of the
	// ProjectSettingService's CreateProjectSetting RPC.
	ProjectSettingServiceCreateProjectSettingProcedure = "/libops.v1.ProjectSettingService/CreateProjectSetting"
	// ProjectSettingServiceGetProjectSettingProcedure is the fully-qualified name of the
	// ProjectSettingService's GetProjectSetting RPC.
	ProjectSettingServiceGetProjectSettingProcedure = "/libops.v1.ProjectSettingService/GetProjectSetting"
	// ProjectSettingServiceListProjectSettingsProcedure is the fully-qualified name of the
	// ProjectSettingService's ListProjectSettings RPC.
	ProjectSettingServiceListProjectSettingsProcedure = "/libops.v1.ProjectSettingService/ListProjectSettings"
	// ProjectSettingServiceUpdateProjectSettingProcedure is the fully-qualified name of the
	// ProjectSettingService's UpdateProjectSetting RPC.
	ProjectSettingServiceUpdateProjectSettingProcedure = "/libops.v1.ProjectSettingService/UpdateProjectSetting"
	// ProjectSettingServiceDeleteProjectSettingProcedure is the fully-qualified name of the
	// ProjectSettingService's DeleteProjectSetting RPC.
	ProjectSettingServiceDeleteProjectSettingProcedure = "/libops.v1.ProjectSettingService/DeleteProjectSetting"
	// SiteSettingServiceCreateSiteSettingProcedure is the fully-qualified name of the
	// SiteSettingService's CreateSiteSetting RPC.
	SiteSettingServiceCreateSiteSettingProcedure = "/libops.v1.SiteSettingService/CreateSiteSetting"
	// SiteSettingServiceGetSiteSettingProcedure is the fully-qualified name of the SiteSettingService's
	// GetSiteSetting RPC.
	SiteSettingServiceGetSiteSettingProcedure = "/libops.v1.SiteSettingService/GetSiteSetting"
	// SiteSettingServiceListSiteSettingsProcedure is the fully-qualified name of the
	// SiteSettingService's ListSiteSettings RPC.
	SiteSettingServiceListSiteSettingsProcedure = "/libops.v1.SiteSettingService/ListSiteSettings"
	// SiteSettingServiceUpdateSiteSettingProcedure is the fully-qualified name of the
	// SiteSettingService's UpdateSiteSetting RPC.
	SiteSettingServiceUpdateSiteSettingProcedure = "/libops.v1.SiteSettingService/UpdateSiteSetting"
	// SiteSettingServiceDeleteSiteSettingProcedure is the fully-qualified name of the
	// SiteSettingService's DeleteSiteSetting RPC.
	SiteSettingServiceDeleteSiteSettingProcedure = "/libops.v1.SiteSettingService/DeleteSiteSetting"
)

// OrganizationSettingServiceClient is a client for the libops.v1.OrganizationSettingService
// service.
type OrganizationSettingServiceClient interface {
	// Create an organization setting
	CreateOrganizationSetting(context.Context, *connect.Request[v1.CreateOrganizationSettingRequest]) (*connect.Response[v1.CreateOrganizationSettingResponse], error)
	// Get an organization setting
	GetOrganizationSetting(context.Context, *connect.Request[v1.GetOrganizationSettingRequest]) (*connect.Response[v1.GetOrganizationSettingResponse], error)
	// List organization settings
	ListOrganizationSettings(context.Context, *connect.Request[v1.ListOrganizationSettingsRequest]) (*connect.Response[v1.ListOrganizationSettingsResponse], error)
	// Update an organization setting
	UpdateOrganizationSetting(context.Context, *connect.Request[v1.UpdateOrganizationSettingRequest]) (*connect.Response[v1.UpdateOrganizationSettingResponse], error)
	// Delete an organization setting
	DeleteOrganizationSetting(context.Context, *connect.Request[v1.DeleteOrganizationSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewOrganizationSettingServiceClient constructs a client for the
// libops.v1.OrganizationSettingService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrganizationSettingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrganizationSettingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	organizationSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("OrganizationSettingService").Methods()
	return &organizationSettingServiceClient{
		createOrganizationSetting: connect.NewClient[v1.CreateOrganizationSettingRequest, v1.CreateOrganizationSettingResponse](
			httpClient,
			baseURL+OrganizationSettingServiceCreateOrganizationSettingProcedure,
			connect.WithSchema(organizationSettingServiceMethods.ByName("CreateOrganizationSetting")),
			connect.WithClientOptions(opts...),
		),
		getOrganizationSetting: connect.NewClient[v1.GetOrganizationSettingRequest, v1.GetOrganizationSettingResponse](
			httpClient,
			baseURL+OrganizationSettingServiceGetOrganizationSettingProcedure,
			connect.WithSchema(organizationSettingServiceMethods.ByName("GetOrganizationSetting")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listOrganizationSettings: connect.NewClient[v1.ListOrganizationSettingsRequest, v1.ListOrganizationSettingsResponse](
			httpClient,
			baseURL+OrganizationSettingServiceListOrganizationSettingsProcedure,
			connect.WithSchema(organizationSettingServiceMethods.ByName("ListOrganizationSettings")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateOrganizationSetting: connect.NewClient[v1.UpdateOrganizationSettingRequest, v1.UpdateOrganizationSettingResponse](
			httpClient,
			baseURL+OrganizationSettingServiceUpdateOrganizationSettingProcedure,
			connect.WithSchema(organizationSettingServiceMethods.ByName("UpdateOrganizationSetting")),
			connect.WithClientOptions(opts...),
		),
		deleteOrganizationSetting: connect.NewClient[v1.DeleteOrganizationSettingRequest, emptypb.Empty](
			httpClient,
			baseURL+OrganizationSettingServiceDeleteOrganizationSettingProcedure,
			connect.WithSchema(organizationSettingServiceMethods.ByName("DeleteOrganizationSetting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// organizationSettingServiceClient implements OrganizationSettingServiceClient.
type organizationSettingServiceClient struct {
	createOrganizationSetting *connect.Client[v1.CreateOrganizationSettingRequest, v1.CreateOrganizationSettingResponse]
	getOrganizationSetting    *connect.Client[v1.GetOrganizationSettingRequest, v1.GetOrganizationSettingResponse]
	listOrganizationSettings  *connect.Client[v1.ListOrganizationSettingsRequest, v1.ListOrganizationSettingsResponse]
	updateOrganizationSetting *connect.Client[v1.UpdateOrganizationSettingRequest, v1.UpdateOrganizationSettingResponse]
	deleteOrganizationSetting *connect.Client[v1.DeleteOrganizationSettingRequest, emptypb.Empty]
}

// CreateOrganizationSetting calls libops.v1.OrganizationSettingService.CreateOrganizationSetting.
func (c *organizationSettingServiceClient) CreateOrganizationSetting(ctx context.Context, req *connect.Request[v1.CreateOrganizationSettingRequest]) (*connect.Response[v1.CreateOrganizationSettingResponse], error) {
	return c.createOrganizationSetting.CallUnary(ctx, req)
}

// GetOrganizationSetting calls libops.v1.OrganizationSettingService.GetOrganizationSetting.
func (c *organizationSettingServiceClient) GetOrganizationSetting(ctx context.Context, req *connect.Request[v1.GetOrganizationSettingRequest]) (*connect.Response[v1.GetOrganizationSettingResponse], error) {
	return c.getOrganizationSetting.CallUnary(ctx, req)
}

// ListOrganizationSettings calls libops.v1.OrganizationSettingService.ListOrganizationSettings.
func (c *organizationSettingServiceClient) ListOrganizationSettings(ctx context.Context, req *connect.Request[v1.ListOrganizationSettingsRequest]) (*connect.Response[v1.ListOrganizationSettingsResponse], error) {
	return c.listOrganizationSettings.CallUnary(ctx, req)
}

// UpdateOrganizationSetting calls libops.v1.OrganizationSettingService.UpdateOrganizationSetting.
func (c *organizationSettingServiceClient) UpdateOrganizationSetting(ctx context.Context, req *connect.Request[v1.UpdateOrganizationSettingRequest]) (*connect.Response[v1.UpdateOrganizationSettingResponse], error) {
	return c.updateOrganizationSetting.CallUnary(ctx, req)
}

// DeleteOrganizationSetting calls libops.v1.OrganizationSettingService.DeleteOrganizationSetting.
func (c *organizationSettingServiceClient) DeleteOrganizationSetting(ctx context.Context, req *connect.Request[v1.DeleteOrganizationSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteOrganizationSetting.CallUnary(ctx, req)
}

// OrganizationSettingServiceHandler is an implementation of the
// libops.v1.OrganizationSettingService service.
type OrganizationSettingServiceHandler interface {
	// Create an organization setting
	CreateOrganizationSetting(context.Context, *connect.Request[v1.CreateOrganizationSettingRequest]) (*connect.Response[v1.CreateOrganizationSettingResponse], error)
	// Get an organization setting
	GetOrganizationSetting(context.Context, *connect.Request[v1.GetOrganizationSettingRequest]) (*connect.Response[v1.GetOrganizationSettingResponse], error)
	// List organization settings
	ListOrganizationSettings(context.Context, *connect.Request[v1.ListOrganizationSettingsRequest]) (*connect.Response[v1.ListOrganizationSettingsResponse], error)
	// Update an organization setting
	UpdateOrganizationSetting(context.Context, *connect.Request[v1.UpdateOrganizationSettingRequest]) (*connect.Response[v1.UpdateOrganizationSettingResponse], error)
	// Delete an organization setting
	DeleteOrganizationSetting(context.Context, *connect.Request[v1.DeleteOrganizationSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewOrganizationSettingServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrganizationSettingServiceHandler(svc OrganizationSettingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	organizationSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("OrganizationSettingService").Methods()
	organizationSettingServiceCreateOrganizationSettingHandler := connect.NewUnaryHandler(
		OrganizationSettingServiceCreateOrganizationSettingProcedure,
		svc.CreateOrganizationSetting,
		connect.WithSchema(organizationSettingServiceMethods.ByName("CreateOrganizationSetting")),
		connect.WithHandlerOptions(opts...),
	)
	organizationSettingServiceGetOrganizationSettingHandler := connect.NewUnaryHandler(
		OrganizationSettingServiceGetOrganizationSettingProcedure,
		svc.GetOrganizationSetting,
		connect.WithSchema(organizationSettingServiceMethods.ByName("GetOrganizationSetting")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	organizationSettingServiceListOrganizationSettingsHandler := connect.NewUnaryHandler(
		OrganizationSettingServiceListOrganizationSettingsProcedure,
		svc.ListOrganizationSettings,
		connect.WithSchema(organizationSettingServiceMethods.ByName("ListOrganizationSettings")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	organizationSettingServiceUpdateOrganizationSettingHandler := connect.NewUnaryHandler(
		OrganizationSettingServiceUpdateOrganizationSettingProcedure,
		svc.UpdateOrganizationSetting,
		connect.WithSchema(organizationSettingServiceMethods.ByName("UpdateOrganizationSetting")),
		connect.WithHandlerOptions(opts...),
	)
	organizationSettingServiceDeleteOrganizationSettingHandler := connect.NewUnaryHandler(
		OrganizationSettingServiceDeleteOrganizationSettingProcedure,
		svc.DeleteOrganizationSetting,
		connect.WithSchema(organizationSettingServiceMethods.ByName("DeleteOrganizationSetting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.OrganizationSettingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrganizationSettingServiceCreateOrganizationSettingProcedure:
			organizationSettingServiceCreateOrganizationSettingHandler.ServeHTTP(w, r)
		case OrganizationSettingServiceGetOrganizationSettingProcedure:
			organizationSettingServiceGetOrganizationSettingHandler.ServeHTTP(w, r)
		case OrganizationSettingServiceListOrganizationSettingsProcedure:
			organizationSettingServiceListOrganizationSettingsHandler.ServeHTTP(w, r)
		case OrganizationSettingServiceUpdateOrganizationSettingProcedure:
			organizationSettingServiceUpdateOrganizationSettingHandler.ServeHTTP(w, r)
		case OrganizationSettingServiceDeleteOrganizationSettingProcedure:
			organizationSettingServiceDeleteOrganizationSettingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrganizationSettingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrganizationSettingServiceHandler struct{}

func (UnimplementedOrganizationSettingServiceHandler) CreateOrganizationSetting(context.Context, *connect.Request[v1.CreateOrganizationSettingRequest]) (*connect.Response[v1.CreateOrganizationSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.OrganizationSettingService.CreateOrganizationSetting is not implemented"))
}

func (UnimplementedOrganizationSettingServiceHandler) GetOrganizationSetting(context.Context, *connect.Request[v1.GetOrganizationSettingRequest]) (*connect.Response[v1.GetOrganizationSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.OrganizationSettingService.GetOrganizationSetting is not implemented"))
}

func (UnimplementedOrganizationSettingServiceHandler) ListOrganizationSettings(context.Context, *connect.Request[v1.ListOrganizationSettingsRequest]) (*connect.Response[v1.ListOrganizationSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.OrganizationSettingService.ListOrganizationSettings is not implemented"))
}

func (UnimplementedOrganizationSettingServiceHandler) UpdateOrganizationSetting(context.Context, *connect.Request[v1.UpdateOrganizationSettingRequest]) (*connect.Response[v1.UpdateOrganizationSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.OrganizationSettingService.UpdateOrganizationSetting is not implemented"))
}

func (UnimplementedOrganizationSettingServiceHandler) DeleteOrganizationSetting(context.Context, *connect.Request[v1.DeleteOrganizationSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.OrganizationSettingService.DeleteOrganizationSetting is not implemented"))
}

// ProjectSettingServiceClient is a client for the libops.v1.ProjectSettingService service.
type ProjectSettingServiceClient interface {
	// Create a project setting
	CreateProjectSetting(context.Context, *connect.Request[v1.CreateProjectSettingRequest]) (*connect.Response[v1.CreateProjectSettingResponse], error)
	// Get a project setting
	GetProjectSetting(context.Context, *connect.Request[v1.GetProjectSettingRequest]) (*connect.Response[v1.GetProjectSettingResponse], error)
	// List project settings
	ListProjectSettings(context.Context, *connect.Request[v1.ListProjectSettingsRequest]) (*connect.Response[v1.ListProjectSettingsResponse], error)
	// Update a project setting
	UpdateProjectSetting(context.Context, *connect.Request[v1.UpdateProjectSettingRequest]) (*connect.Response[v1.UpdateProjectSettingResponse], error)
	// Delete a project setting
	DeleteProjectSetting(context.Context, *connect.Request[v1.DeleteProjectSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewProjectSettingServiceClient constructs a client for the libops.v1.ProjectSettingService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectSettingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectSettingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("ProjectSettingService").Methods()
	return &projectSettingServiceClient{
		createProjectSetting: connect.NewClient[v1.CreateProjectSettingRequest, v1.CreateProjectSettingResponse](
			httpClient,
			baseURL+ProjectSettingServiceCreateProjectSettingProcedure,
			connect.WithSchema(projectSettingServiceMethods.ByName("CreateProjectSetting")),
			connect.WithClientOptions(opts...),
		),
		getProjectSetting: connect.NewClient[v1.GetProjectSettingRequest, v1.GetProjectSettingResponse](
			httpClient,
			baseURL+ProjectSettingServiceGetProjectSettingProcedure,
			connect.WithSchema(projectSettingServiceMethods.ByName("GetProjectSetting")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listProjectSettings: connect.NewClient[v1.ListProjectSettingsRequest, v1.ListProjectSettingsResponse](
			httpClient,
			baseURL+ProjectSettingServiceListProjectSettingsProcedure,
			connect.WithSchema(projectSettingServiceMethods.ByName("ListProjectSettings")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateProjectSetting: connect.NewClient[v1.UpdateProjectSettingRequest, v1.UpdateProjectSettingResponse](
			httpClient,
			baseURL+ProjectSettingServiceUpdateProjectSettingProcedure,
			connect.WithSchema(projectSettingServiceMethods.ByName("UpdateProjectSetting")),
			connect.WithClientOptions(opts...),
		),
		deleteProjectSetting: connect.NewClient[v1.DeleteProjectSettingRequest, emptypb.Empty](
			httpClient,
			baseURL+ProjectSettingServiceDeleteProjectSettingProcedure,
			connect.WithSchema(projectSettingServiceMethods.ByName("DeleteProjectSetting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectSettingServiceClient implements ProjectSettingServiceClient.
type projectSettingServiceClient struct {
	createProjectSetting *connect.Client[v1.CreateProjectSettingRequest, v1.CreateProjectSettingResponse]
	getProjectSetting    *connect.Client[v1.GetProjectSettingRequest, v1.GetProjectSettingResponse]
	listProjectSettings  *connect.Client[v1.ListProjectSettingsRequest, v1.ListProjectSettingsResponse]
	updateProjectSetting *connect.Client[v1.UpdateProjectSettingRequest, v1.UpdateProjectSettingResponse]
	deleteProjectSetting *connect.Client[v1.DeleteProjectSettingRequest, emptypb.Empty]
}

// CreateProjectSetting calls libops.v1.ProjectSettingService.CreateProjectSetting.
func (c *projectSettingServiceClient) CreateProjectSetting(ctx context.Context, req *connect.Request[v1.CreateProjectSettingRequest]) (*connect.Response[v1.CreateProjectSettingResponse], error) {
	return c.createProjectSetting.CallUnary(ctx, req)
}

// GetProjectSetting calls libops.v1.ProjectSettingService.GetProjectSetting.
func (c *projectSettingServiceClient) GetProjectSetting(ctx context.Context, req *connect.Request[v1.GetProjectSettingRequest]) (*connect.Response[v1.GetProjectSettingResponse], error) {
	return c.getProjectSetting.CallUnary(ctx, req)
}

// ListProjectSettings calls libops.v1.ProjectSettingService.ListProjectSettings.
func (c *projectSettingServiceClient) ListProjectSettings(ctx context.Context, req *connect.Request[v1.ListProjectSettingsRequest]) (*connect.Response[v1.ListProjectSettingsResponse], error) {
	return c.listProjectSettings.CallUnary(ctx, req)
}

// UpdateProjectSetting calls libops.v1.ProjectSettingService.UpdateProjectSetting.
func (c *projectSettingServiceClient) UpdateProjectSetting(ctx context.Context, req *connect.Request[v1.UpdateProjectSettingRequest]) (*connect.Response[v1.UpdateProjectSettingResponse], error) {
	return c.updateProjectSetting.CallUnary(ctx, req)
}

// DeleteProjectSetting calls libops.v1.ProjectSettingService.DeleteProjectSetting.
func (c *projectSettingServiceClient) DeleteProjectSetting(ctx context.Context, req *connect.Request[v1.DeleteProjectSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteProjectSetting.CallUnary(ctx, req)
}

// ProjectSettingServiceHandler is an implementation of the libops.v1.ProjectSettingService service.
type ProjectSettingServiceHandler interface {
	// Create a project setting
	CreateProjectSetting(context.Context, *connect.Request[v1.CreateProjectSettingRequest]) (*connect.Response[v1.CreateProjectSettingResponse], error)
	// Get a project setting
	GetProjectSetting(context.Context, *connect.Request[v1.GetProjectSettingRequest]) (*connect.Response[v1.GetProjectSettingResponse], error)
	// List project settings
	ListProjectSettings(context.Context, *connect.Request[v1.ListProjectSettingsRequest]) (*connect.Response[v1.ListProjectSettingsResponse], error)
	// Update a project setting
	UpdateProjectSetting(context.Context, *connect.Request[v1.UpdateProjectSettingRequest]) (*connect.Response[v1.UpdateProjectSettingResponse], error)
	// Delete a project setting
	DeleteProjectSetting(context.Context, *connect.Request[v1.DeleteProjectSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewProjectSettingServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectSettingServiceHandler(svc ProjectSettingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("ProjectSettingService").Methods()
	projectSettingServiceCreateProjectSettingHandler := connect.NewUnaryHandler(
		ProjectSettingServiceCreateProjectSettingProcedure,
		svc.CreateProjectSetting,
		connect.WithSchema(projectSettingServiceMethods.ByName("CreateProjectSetting")),
		connect.WithHandlerOptions(opts...),
	)
	projectSettingServiceGetProjectSettingHandler := connect.NewUnaryHandler(
		ProjectSettingServiceGetProjectSettingProcedure,
		svc.GetProjectSetting,
		connect.WithSchema(projectSettingServiceMethods.ByName("GetProjectSetting")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	projectSettingServiceListProjectSettingsHandler := connect.NewUnaryHandler(
		ProjectSettingServiceListProjectSettingsProcedure,
		svc.ListProjectSettings,
		connect.WithSchema(projectSettingServiceMethods.ByName("ListProjectSettings")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	projectSettingServiceUpdateProjectSettingHandler := connect.NewUnaryHandler(
		ProjectSettingServiceUpdateProjectSettingProcedure,
		svc.UpdateProjectSetting,
		connect.WithSchema(projectSettingServiceMethods.ByName("UpdateProjectSetting")),
		connect.WithHandlerOptions(opts...),
	)
	projectSettingServiceDeleteProjectSettingHandler := connect.NewUnaryHandler(
		ProjectSettingServiceDeleteProjectSettingProcedure,
		svc.DeleteProjectSetting,
		connect.WithSchema(projectSettingServiceMethods.ByName("DeleteProjectSetting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.ProjectSettingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectSettingServiceCreateProjectSettingProcedure:
			projectSettingServiceCreateProjectSettingHandler.ServeHTTP(w, r)
		case ProjectSettingServiceGetProjectSettingProcedure:
			projectSettingServiceGetProjectSettingHandler.ServeHTTP(w, r)
		case ProjectSettingServiceListProjectSettingsProcedure:
			projectSettingServiceListProjectSettingsHandler.ServeHTTP(w, r)
		case ProjectSettingServiceUpdateProjectSettingProcedure:
			projectSettingServiceUpdateProjectSettingHandler.ServeHTTP(w, r)
		case ProjectSettingServiceDeleteProjectSettingProcedure:
			projectSettingServiceDeleteProjectSettingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectSettingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectSettingServiceHandler struct{}

func (UnimplementedProjectSettingServiceHandler) CreateProjectSetting(context.Context, *connect.Request[v1.CreateProjectSettingRequest]) (*connect.Response[v1.CreateProjectSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.ProjectSettingService.CreateProjectSetting is not implemented"))
}

func (UnimplementedProjectSettingServiceHandler) GetProjectSetting(context.Context, *connect.Request[v1.GetProjectSettingRequest]) (*connect.Response[v1.GetProjectSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.ProjectSettingService.GetProjectSetting is not implemented"))
}

func (UnimplementedProjectSettingServiceHandler) ListProjectSettings(context.Context, *connect.Request[v1.ListProjectSettingsRequest]) (*connect.Response[v1.ListProjectSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.ProjectSettingService.ListProjectSettings is not implemented"))
}

func (UnimplementedProjectSettingServiceHandler) UpdateProjectSetting(context.Context, *connect.Request[v1.UpdateProjectSettingRequest]) (*connect.Response[v1.UpdateProjectSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.ProjectSettingService.UpdateProjectSetting is not implemented"))
}

func (UnimplementedProjectSettingServiceHandler) DeleteProjectSetting(context.Context, *connect.Request[v1.DeleteProjectSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.ProjectSettingService.DeleteProjectSetting is not implemented"))
}

// SiteSettingServiceClient is a client for the libops.v1.SiteSettingService service.
type SiteSettingServiceClient interface {
	// Create a site setting
	CreateSiteSetting(context.Context, *connect.Request[v1.CreateSiteSettingRequest]) (*connect.Response[v1.CreateSiteSettingResponse], error)
	// Get a site setting
	GetSiteSetting(context.Context, *connect.Request[v1.GetSiteSettingRequest]) (*connect.Response[v1.GetSiteSettingResponse], error)
	// List site settings
	ListSiteSettings(context.Context, *connect.Request[v1.ListSiteSettingsRequest]) (*connect.Response[v1.ListSiteSettingsResponse], error)
	// Update a site setting
	UpdateSiteSetting(context.Context, *connect.Request[v1.UpdateSiteSettingRequest]) (*connect.Response[v1.UpdateSiteSettingResponse], error)
	// Delete a site setting
	DeleteSiteSetting(context.Context, *connect.Request[v1.DeleteSiteSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewSiteSettingServiceClient constructs a client for the libops.v1.SiteSettingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSiteSettingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SiteSettingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	siteSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("SiteSettingService").Methods()
	return &siteSettingServiceClient{
		createSiteSetting: connect.NewClient[v1.CreateSiteSettingRequest, v1.CreateSiteSettingResponse](
			httpClient,
			baseURL+SiteSettingServiceCreateSiteSettingProcedure,
			connect.WithSchema(siteSettingServiceMethods.ByName("CreateSiteSetting")),
			connect.WithClientOptions(opts...),
		),
		getSiteSetting: connect.NewClient[v1.GetSiteSettingRequest, v1.GetSiteSettingResponse](
			httpClient,
			baseURL+SiteSettingServiceGetSiteSettingProcedure,
			connect.WithSchema(siteSettingServiceMethods.ByName("GetSiteSetting")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSiteSettings: connect.NewClient[v1.ListSiteSettingsRequest, v1.ListSiteSettingsResponse](
			httpClient,
			baseURL+SiteSettingServiceListSiteSettingsProcedure,
			connect.WithSchema(siteSettingServiceMethods.ByName("ListSiteSettings")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateSiteSetting: connect.NewClient[v1.UpdateSiteSettingRequest, v1.UpdateSiteSettingResponse](
			httpClient,
			baseURL+SiteSettingServiceUpdateSiteSettingProcedure,
			connect.WithSchema(siteSettingServiceMethods.ByName("UpdateSiteSetting")),
			connect.WithClientOptions(opts...),
		),
		deleteSiteSetting: connect.NewClient[v1.DeleteSiteSettingRequest, emptypb.Empty](
			httpClient,
			baseURL+SiteSettingServiceDeleteSiteSettingProcedure,
			connect.WithSchema(siteSettingServiceMethods.ByName("DeleteSiteSetting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// siteSettingServiceClient implements SiteSettingServiceClient.
type siteSettingServiceClient struct {
	createSiteSetting *connect.Client[v1.CreateSiteSettingRequest, v1.CreateSiteSettingResponse]
	getSiteSetting    *connect.Client[v1.GetSiteSettingRequest, v1.GetSiteSettingResponse]
	listSiteSettings  *connect.Client[v1.ListSiteSettingsRequest, v1.ListSiteSettingsResponse]
	updateSiteSetting *connect.Client[v1.UpdateSiteSettingRequest, v1.UpdateSiteSettingResponse]
	deleteSiteSetting *connect.Client[v1.DeleteSiteSettingRequest, emptypb.Empty]
}

// CreateSiteSetting calls libops.v1.SiteSettingService.CreateSiteSetting.
func (c *siteSettingServiceClient) CreateSiteSetting(ctx context.Context, req *connect.Request[v1.CreateSiteSettingRequest]) (*connect.Response[v1.CreateSiteSettingResponse], error) {
	return c.createSiteSetting.CallUnary(ctx, req)
}

// GetSiteSetting calls libops.v1.SiteSettingService.GetSiteSetting.
func (c *siteSettingServiceClient) GetSiteSetting(ctx context.Context, req *connect.Request[v1.GetSiteSettingRequest]) (*connect.Response[v1.GetSiteSettingResponse], error) {
	return c.getSiteSetting.CallUnary(ctx, req)
}

// ListSiteSettings calls libops.v1.SiteSettingService.ListSiteSettings.
func (c *siteSettingServiceClient) ListSiteSettings(ctx context.Context, req *connect.Request[v1.ListSiteSettingsRequest]) (*connect.Response[v1.ListSiteSettingsResponse], error) {
	return c.listSiteSettings.CallUnary(ctx, req)
}

// UpdateSiteSetting calls libops.v1.SiteSettingService.UpdateSiteSetting.
func (c *siteSettingServiceClient) UpdateSiteSetting(ctx context.Context, req *connect.Request[v1.UpdateSiteSettingRequest]) (*connect.Response[v1.UpdateSiteSettingResponse], error) {
	return c.updateSiteSetting.CallUnary(ctx, req)
}

// DeleteSiteSetting calls libops.v1.SiteSettingService.DeleteSiteSetting.
func (c *siteSettingServiceClient) DeleteSiteSetting(ctx context.Context, req *connect.Request[v1.DeleteSiteSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteSiteSetting.CallUnary(ctx, req)
}

// SiteSettingServiceHandler is an implementation of the libops.v1.SiteSettingService service.
type SiteSettingServiceHandler interface {
	// Create a site setting
	CreateSiteSetting(context.Context, *connect.Request[v1.CreateSiteSettingRequest]) (*connect.Response[v1.CreateSiteSettingResponse], error)
	// Get a site setting
	GetSiteSetting(context.Context, *connect.Request[v1.GetSiteSettingRequest]) (*connect.Response[v1.GetSiteSettingResponse], error)
	// List site settings
	ListSiteSettings(context.Context, *connect.Request[v1.ListSiteSettingsRequest]) (*connect.Response[v1.ListSiteSettingsResponse], error)
	// Update a site setting
	UpdateSiteSetting(context.Context, *connect.Request[v1.UpdateSiteSettingRequest]) (*connect.Response[v1.UpdateSiteSettingResponse], error)
	// Delete a site setting
	DeleteSiteSetting(context.Context, *connect.Request[v1.DeleteSiteSettingRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewSiteSettingServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSiteSettingServiceHandler(svc SiteSettingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	siteSettingServiceMethods := v1.File_libops_v1_settings_proto.Services().ByName("SiteSettingService").Methods()
	siteSettingServiceCreateSiteSettingHandler := connect.NewUnaryHandler(
		SiteSettingServiceCreateSiteSettingProcedure,
		svc.CreateSiteSetting,
		connect.WithSchema(siteSettingServiceMethods.ByName("CreateSiteSetting")),
		connect.WithHandlerOptions(opts...),
	)
	siteSettingServiceGetSiteSettingHandler := connect.NewUnaryHandler(
		SiteSettingServiceGetSiteSettingProcedure,
		svc.GetSiteSetting,
		connect.WithSchema(siteSettingServiceMethods.ByName("GetSiteSetting")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	siteSettingServiceListSiteSettingsHandler := connect.NewUnaryHandler(
		SiteSettingServiceListSiteSettingsProcedure,
		svc.ListSiteSettings,
		connect.WithSchema(siteSettingServiceMethods.ByName("ListSiteSettings")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	siteSettingServiceUpdateSiteSettingHandler := connect.NewUnaryHandler(
		SiteSettingServiceUpdateSiteSettingProcedure,
		svc.UpdateSiteSetting,
		connect.WithSchema(siteSettingServiceMethods.ByName("UpdateSiteSetting")),
		connect.WithHandlerOptions(opts...),
	)
	siteSettingServiceDeleteSiteSettingHandler := connect.NewUnaryHandler(
		SiteSettingServiceDeleteSiteSettingProcedure,
		svc.DeleteSiteSetting,
		connect.WithSchema(siteSettingServiceMethods.ByName("DeleteSiteSetting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/libops.v1.SiteSettingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SiteSettingServiceCreateSiteSettingProcedure:
			siteSettingServiceCreateSiteSettingHandler.ServeHTTP(w, r)
		case SiteSettingServiceGetSiteSettingProcedure:
			siteSettingServiceGetSiteSettingHandler.ServeHTTP(w, r)
		case SiteSettingServiceListSiteSettingsProcedure:
			siteSettingServiceListSiteSettingsHandler.ServeHTTP(w, r)
		case SiteSettingServiceUpdateSiteSettingProcedure:
			siteSettingServiceUpdateSiteSettingHandler.ServeHTTP(w, r)
		case SiteSettingServiceDeleteSiteSettingProcedure:
			siteSettingServiceDeleteSiteSettingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSiteSettingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSiteSettingServiceHandler struct{}

func (UnimplementedSiteSettingServiceHandler) CreateSiteSetting(context.Context, *connect.Request[v1.CreateSiteSettingRequest]) (*connect.Response[v1.CreateSiteSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.SiteSettingService.CreateSiteSetting is not implemented"))
}

func (UnimplementedSiteSettingServiceHandler) GetSiteSetting(context.Context, *connect.Request[v1.GetSiteSettingRequest]) (*connect.Response[v1.GetSiteSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.SiteSettingService.GetSiteSetting is not implemented"))
}

func (UnimplementedSiteSettingServiceHandler) ListSiteSettings(context.Context, *connect.Request[v1.ListSiteSettingsRequest]) (*connect.Response[v1.ListSiteSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.SiteSettingService.ListSiteSettings is not implemented"))
}

func (UnimplementedSiteSettingServiceHandler) UpdateSiteSetting(context.Context, *connect.Request[v1.UpdateSiteSettingRequest]) (*connect.Response[v1.UpdateSiteSettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.SiteSettingService.UpdateSiteSetting is not implemented"))
}

func (UnimplementedSiteSettingServiceHandler) DeleteSiteSetting(context.Context, *connect.Request[v1.DeleteSiteSettingRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("libops.v1.SiteSettingService.DeleteSiteSetting is not implemented"))
}
