// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/admin/organization.proto

package admin

import (
	common "github.com/libops/proto/libops/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminFolderConfig extends the organization-facing config with internal fields
type AdminFolderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization-safe fields (embedded)
	Config *common.FolderConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Parent resource: folders/{folder_id} or organizations/{org_id}
	// Defaults to folder format if not specified
	GcpParent string `protobuf:"bytes,2,opt,name=gcp_parent,json=gcpParent,proto3" json:"gcp_parent,omitempty"`
	// GCP-managed resources (output from orchestration)
	GcpFolderId   *string `protobuf:"bytes,3,opt,name=gcp_folder_id,json=gcpFolderId,proto3,oneof" json:"gcp_folder_id,omitempty"` // Set by orchestration after folder creation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFolderConfig) Reset() {
	*x = AdminFolderConfig{}
	mi := &file_libops_v1_admin_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFolderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFolderConfig) ProtoMessage() {}

func (x *AdminFolderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFolderConfig.ProtoReflect.Descriptor instead.
func (*AdminFolderConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_organization_proto_rawDescGZIP(), []int{0}
}

func (x *AdminFolderConfig) GetConfig() *common.FolderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AdminFolderConfig) GetGcpParent() string {
	if x != nil {
		return x.GcpParent
	}
	return ""
}

func (x *AdminFolderConfig) GetGcpFolderId() string {
	if x != nil && x.GcpFolderId != nil {
		return *x.GcpFolderId
	}
	return ""
}

var File_libops_v1_admin_organization_proto protoreflect.FileDescriptor

const file_libops_v1_admin_organization_proto_rawDesc = "" +
	"\n" +
	"\"libops/v1/admin/organization.proto\x12\x0flibops.v1.admin\x1a#libops/v1/common/organization.proto\"\xa5\x01\n" +
	"\x11AdminFolderConfig\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1e.libops.v1.common.FolderConfigR\x06config\x12\x1d\n" +
	"\n" +
	"gcp_parent\x18\x02 \x01(\tR\tgcpParent\x12'\n" +
	"\rgcp_folder_id\x18\x03 \x01(\tH\x00R\vgcpFolderId\x88\x01\x01B\x10\n" +
	"\x0e_gcp_folder_idB\xaf\x01\n" +
	"\x13com.libops.v1.adminB\x11OrganizationProtoP\x01Z'github.com/libops/proto/libops/v1/admin\xa2\x02\x03LVA\xaa\x02\x0fLibops.V1.Admin\xca\x02\x0fLibops\\V1\\Admin\xe2\x02\x1bLibops\\V1\\Admin\\GPBMetadata\xea\x02\x11Libops::V1::Adminb\x06proto3"

var (
	file_libops_v1_admin_organization_proto_rawDescOnce sync.Once
	file_libops_v1_admin_organization_proto_rawDescData []byte
)

func file_libops_v1_admin_organization_proto_rawDescGZIP() []byte {
	file_libops_v1_admin_organization_proto_rawDescOnce.Do(func() {
		file_libops_v1_admin_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_admin_organization_proto_rawDesc), len(file_libops_v1_admin_organization_proto_rawDesc)))
	})
	return file_libops_v1_admin_organization_proto_rawDescData
}

var file_libops_v1_admin_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_libops_v1_admin_organization_proto_goTypes = []any{
	(*AdminFolderConfig)(nil),   // 0: libops.v1.admin.AdminFolderConfig
	(*common.FolderConfig)(nil), // 1: libops.v1.common.FolderConfig
}
var file_libops_v1_admin_organization_proto_depIdxs = []int32{
	1, // 0: libops.v1.admin.AdminFolderConfig.config:type_name -> libops.v1.common.FolderConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libops_v1_admin_organization_proto_init() }
func file_libops_v1_admin_organization_proto_init() {
	if File_libops_v1_admin_organization_proto != nil {
		return
	}
	file_libops_v1_admin_organization_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_admin_organization_proto_rawDesc), len(file_libops_v1_admin_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_admin_organization_proto_goTypes,
		DependencyIndexes: file_libops_v1_admin_organization_proto_depIdxs,
		MessageInfos:      file_libops_v1_admin_organization_proto_msgTypes,
	}.Build()
	File_libops_v1_admin_organization_proto = out.File
	file_libops_v1_admin_organization_proto_goTypes = nil
	file_libops_v1_admin_organization_proto_depIdxs = nil
}
