// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: libops/v1/admin/site.proto

package admin

import (
	common "github.com/libops/proto/libops/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminSiteConfig extends the organization-facing config with internal GCP details
type AdminSiteConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization-safe fields (embedded)
	Config *common.SiteConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// GitHub integration
	GithubWebhookUrl    *string `protobuf:"bytes,2,opt,name=github_webhook_url,json=githubWebhookUrl,proto3,oneof" json:"github_webhook_url,omitempty"`
	GithubWebhookSecret *string `protobuf:"bytes,3,opt,name=github_webhook_secret,json=githubWebhookSecret,proto3,oneof" json:"github_webhook_secret,omitempty"` // Sensitive
	GithubTeamId        *string `protobuf:"bytes,7,opt,name=github_team_id,json=githubTeamId,proto3,oneof" json:"github_team_id,omitempty"`                      // GitHub team ID for access control
	// Computed/managed fields (output from orchestration)
	GcpInstanceName *string `protobuf:"bytes,4,opt,name=gcp_instance_name,json=gcpInstanceName,proto3,oneof" json:"gcp_instance_name,omitempty"` // GCE instance name
	GcpExternalIp   *string `protobuf:"bytes,5,opt,name=gcp_external_ip,json=gcpExternalIp,proto3,oneof" json:"gcp_external_ip,omitempty"`       // External IP address
	GcpInternalIp   *string `protobuf:"bytes,6,opt,name=gcp_internal_ip,json=gcpInternalIp,proto3,oneof" json:"gcp_internal_ip,omitempty"`       // Internal IP address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminSiteConfig) Reset() {
	*x = AdminSiteConfig{}
	mi := &file_libops_v1_admin_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSiteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSiteConfig) ProtoMessage() {}

func (x *AdminSiteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_libops_v1_admin_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSiteConfig.ProtoReflect.Descriptor instead.
func (*AdminSiteConfig) Descriptor() ([]byte, []int) {
	return file_libops_v1_admin_site_proto_rawDescGZIP(), []int{0}
}

func (x *AdminSiteConfig) GetConfig() *common.SiteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AdminSiteConfig) GetGithubWebhookUrl() string {
	if x != nil && x.GithubWebhookUrl != nil {
		return *x.GithubWebhookUrl
	}
	return ""
}

func (x *AdminSiteConfig) GetGithubWebhookSecret() string {
	if x != nil && x.GithubWebhookSecret != nil {
		return *x.GithubWebhookSecret
	}
	return ""
}

func (x *AdminSiteConfig) GetGithubTeamId() string {
	if x != nil && x.GithubTeamId != nil {
		return *x.GithubTeamId
	}
	return ""
}

func (x *AdminSiteConfig) GetGcpInstanceName() string {
	if x != nil && x.GcpInstanceName != nil {
		return *x.GcpInstanceName
	}
	return ""
}

func (x *AdminSiteConfig) GetGcpExternalIp() string {
	if x != nil && x.GcpExternalIp != nil {
		return *x.GcpExternalIp
	}
	return ""
}

func (x *AdminSiteConfig) GetGcpInternalIp() string {
	if x != nil && x.GcpInternalIp != nil {
		return *x.GcpInternalIp
	}
	return ""
}

var File_libops_v1_admin_site_proto protoreflect.FileDescriptor

const file_libops_v1_admin_site_proto_rawDesc = "" +
	"\n" +
	"\x1alibops/v1/admin/site.proto\x12\x0flibops.v1.admin\x1a\x1blibops/v1/common/site.proto\"\xeb\x03\n" +
	"\x0fAdminSiteConfig\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.libops.v1.common.SiteConfigR\x06config\x121\n" +
	"\x12github_webhook_url\x18\x02 \x01(\tH\x00R\x10githubWebhookUrl\x88\x01\x01\x127\n" +
	"\x15github_webhook_secret\x18\x03 \x01(\tH\x01R\x13githubWebhookSecret\x88\x01\x01\x12)\n" +
	"\x0egithub_team_id\x18\a \x01(\tH\x02R\fgithubTeamId\x88\x01\x01\x12/\n" +
	"\x11gcp_instance_name\x18\x04 \x01(\tH\x03R\x0fgcpInstanceName\x88\x01\x01\x12+\n" +
	"\x0fgcp_external_ip\x18\x05 \x01(\tH\x04R\rgcpExternalIp\x88\x01\x01\x12+\n" +
	"\x0fgcp_internal_ip\x18\x06 \x01(\tH\x05R\rgcpInternalIp\x88\x01\x01B\x15\n" +
	"\x13_github_webhook_urlB\x18\n" +
	"\x16_github_webhook_secretB\x11\n" +
	"\x0f_github_team_idB\x14\n" +
	"\x12_gcp_instance_nameB\x12\n" +
	"\x10_gcp_external_ipB\x12\n" +
	"\x10_gcp_internal_ipB\xa7\x01\n" +
	"\x13com.libops.v1.adminB\tSiteProtoP\x01Z'github.com/libops/proto/libops/v1/admin\xa2\x02\x03LVA\xaa\x02\x0fLibops.V1.Admin\xca\x02\x0fLibops\\V1\\Admin\xe2\x02\x1bLibops\\V1\\Admin\\GPBMetadata\xea\x02\x11Libops::V1::Adminb\x06proto3"

var (
	file_libops_v1_admin_site_proto_rawDescOnce sync.Once
	file_libops_v1_admin_site_proto_rawDescData []byte
)

func file_libops_v1_admin_site_proto_rawDescGZIP() []byte {
	file_libops_v1_admin_site_proto_rawDescOnce.Do(func() {
		file_libops_v1_admin_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libops_v1_admin_site_proto_rawDesc), len(file_libops_v1_admin_site_proto_rawDesc)))
	})
	return file_libops_v1_admin_site_proto_rawDescData
}

var file_libops_v1_admin_site_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_libops_v1_admin_site_proto_goTypes = []any{
	(*AdminSiteConfig)(nil),   // 0: libops.v1.admin.AdminSiteConfig
	(*common.SiteConfig)(nil), // 1: libops.v1.common.SiteConfig
}
var file_libops_v1_admin_site_proto_depIdxs = []int32{
	1, // 0: libops.v1.admin.AdminSiteConfig.config:type_name -> libops.v1.common.SiteConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libops_v1_admin_site_proto_init() }
func file_libops_v1_admin_site_proto_init() {
	if File_libops_v1_admin_site_proto != nil {
		return
	}
	file_libops_v1_admin_site_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libops_v1_admin_site_proto_rawDesc), len(file_libops_v1_admin_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libops_v1_admin_site_proto_goTypes,
		DependencyIndexes: file_libops_v1_admin_site_proto_depIdxs,
		MessageInfos:      file_libops_v1_admin_site_proto_msgTypes,
	}.Build()
	File_libops_v1_admin_site_proto = out.File
	file_libops_v1_admin_site_proto_goTypes = nil
	file_libops_v1_admin_site_proto_depIdxs = nil
}
